### ISSUE TITLE
Why there isn't `ZPOPMAX` in Sorted Set?

### ISSUE THREAD

**Issue by kingname** [andymccurdy/redis-py#1003]
I'd like to pop the value with the max score, but redis-py does not have `zpopmax` nor `zpopmin`.

So what are the suitable replaces of `ZPOPMAX` and `ZPOPMIN`?

**Comment by ramwin** [comment]
See [this?](https://github.com/andymccurdy/redis-py/pull/989). Zpopmin and Zpopmax is new command in redis 5.0.0, maybe the command is in release. 
I use `zrevrange('yourkey', 0, 1)` to get the max value and then `zrem('yourkey')` to delete the element.

**Comment by kingname** [comment]
@ramwin Your method is a workaround way. However, it is not thread safe. two threads may get the same value.

**Comment by ramwin** [comment]
Yes, if you want to ensure the thread safe, you should do some extra work using [pipelining](https://redis.io/topics/pipelining).

**Comment by itamarhaber** [comment]
This should be resolved via #1037

**Comment by namanjain2707** [comment]
> Yes, if you want to ensure the thread safe, you should do some extra work using [pipelining](https://redis.io/topics/pipelining) or [transactions](https://redis.io/topics/transactions).

You need to use both pipelining **AND** transactions. Pipelining just ensures that the commands are executed in order and also reduces the RTT(Round Trip Time). Transactions are the ones that ensure atomicity of the commands in execution.
