### ISSUE TITLE
ConnectionError while ussing scan_iter

### ISSUE THREAD

**Issue by pabloariasmora** [andymccurdy/redis-py#1008]
Hi.

I have a large amount of keys (over 60000) with a similar pattern, and I want to retrieve all of them. So I'm using `scan_iter` function.

Here is the general idea.
```
 for key in rediscluster.scan_iter("pattern:*"):
       print(key)
      # Other heavy operations
```

But the keys that matched are so many, and the code inside the loop is long an heavy that, there are some cases that I received this error, so the execution ends.

```
Traceback (most recent call last):
 File "/usr/lib/python3.4/site-packages/redis/connection.py", line 392, in read_response
   raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
OSError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "observer.py", line 53, in joborchestrator.status_report.observer.ObserverThread.run
 File "/usr/lib/python3.4/site-packages/rediscluster/client.py", line 639, in scan_iter
   raw_resp = conn.read_response()
 File "/usr/lib/python3.4/site-packages/redis/connection.py", line 624, in read_response
   response = self._parser.read_response()
 File "/usr/lib/python3.4/site-packages/redis/connection.py", line 403, in read_response
   (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)
```

Is there any that I could do to avoid this, as part of the module configuration? Besides trying to manually reconnect every time that I got the error? Like a retry_amount of times?

PD: I know that I'm using redis-py-cluster, but they used the base raw config from this module.

Thank
JP

**Comment by Grokzen** [comment]
Please try to set the `COUNT` option on the call to possibly narrow down the number of items returned each itteration if you get into a case where it tries to return all 60k items in a single call and cause a socket timeout. https://redis.io/commands/scan#number-of-elements-returned-at-every-scan-call

**Comment by andymccurdy** [comment]
As @Grokzen said, this is exactly what the `count` argument is for. You can change your code to:

```python
for key in rediscluster.scan_iter('pattern:*', count=1000):
    print(key)
    # other heavy operations
```

**Comment by pabloariasmora** [comment]
Thanks @Grokzen and @andymccurdy .
Only one more question, so count is storing like a cursor or something? Asking because what happens if between 2 scan_iter calls, none of the keys are removed, both times it will return the same ones?

**Comment by andymccurdy** [comment]
Take a look at: https://redis.io/commands/scan

The server maintains a cursor. The count parameter tells the server how many keys you want per command.

In redis-py, `scan_iter` is a generator that maintains the cursor reference so you don't have to. So at the end of the loop, you should see all the keys.
