### ISSUE TITLE
multi Python version on my machine

### ISSUE THREAD

**Issue by kinggggg** [andymccurdy/redis-py#1010]
i have python 3.x and 2.x in my centos，when i execute the following command, 

$ sudo pip install redis
$ sudo easy_install redis
$ sudo python setup.py install

it just install python redis module for python 3.x not for python 2.x
is there anyone help me ?

**Comment by grumps** [comment]
I don't recommend installing redis module under root, this seems like a bad idea to pollute system packages via root. Eitherway, you can execute `pip` via a python module from the binary. e.g.
```shell
python2.7 -m pip install redis-py
```
I've seen python 2.6 have issues with this and you're on Centos which might still have 2.6.
That being said this isn't  a redis-py issue and is best answered on Stackoverflow.

**Comment by Grokzen** [comment]
@andymccurdy This is not an issue for redis-py, no need to keep it open.
