### ISSUE TITLE
Do you have any plan to implement bzpopmax ?

### ISSUE THREAD

**Issue by zivziv77** [andymccurdy/redis-py#1011]

**Comment by Grokzen** [comment]
Best way to get support into this lib is to open up a MR for it to get into the codebase.

**Comment by RoeyPrat** [comment]
I see the following sorted set commands that were added in redis5 are missing:
- BZPOPMAX
- BZPOPMIN
- ZPOPMAX
- ZPOPMIN

I plan to implement them around the beginning of November, if no one beats me to it ;)

**Comment by itamarhaber** [comment]
This should be resolved via #1037

**Comment by itamarhaber** [comment]
This should be resolved via #1037

**Comment by andymccurdy** [comment]
There have been merged in
