### ISSUE TITLE
unclosed clients grows. Dubiety in client.py

### ISSUE THREAD

**Issue by Alex-vz** [andymccurdy/redis-py#1012]
I've found, that amount of opened connection unexpectedly grows.
I guess, that the reason of it may found in that:
in `clients.py`, in `StrictRedis.execute_command`, line 673 presents `raise` when `ConnectionError` or `TimeoutError`. But in case of that `raise`, the `final` section will not execute. So, I guess, current connection will remain "pended".

**Comment by andymccurdy** [comment]
Statements within a `finally:` block are ALWAYS executed. That's the whole point of `finally:`. I'm not saying you're not seeing the number of connections grow but I'm pretty confident it's not a result of the `finally:` code.
