### ISSUE TITLE
No reference to API documentation from github project / pypi homepage.

### ISSUE THREAD

**Issue by fake-name** [andymccurdy/redis-py#1021]
Basically, I was trying to find API documentation for `ConnectionPool` (the quickstart doesn't document how you release a connection you acquired from a pool). 

Apparently, https://redis-py.readthedocs.io/en/latest/ is the documentation for this project, but I had to use google to get there. 

It seems to me that the README at https://github.com/andymccurdy/redis-py and https://pypi.org/project/redis/ should probably have at least a *reference* to the generated autodocs.

**Comment by RoeyPrat** [comment]
Hi @fake-name, is this what you meant?

**Comment by fake-name** [comment]
Spot on!

**Comment by Grokzen** [comment]
This issue could be closed after merge of #1026
