### ISSUE TITLE
AWS ElastiCache exception

### ISSUE THREAD

**Issue by macklus** [andymccurdy/redis-py#1030]
Not sure if this is really a problem, but:

When i connect to ElastiCache Clustered Redis, sometimes it hangs a redis.exceptions.ResponseError (MOVED 2246 OTHER_CLUSTER_IP:6379)

code sample:
```
r = redis.StrictRedis(host=host, port=6379, db=0)
  for _ in range(1000):
    key = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(12))
    print( key + '...', end='', flush=True)
    try:
      r.set(key, 'bar')
      print("OK")
    except redis.exceptions.ResponseError as err:
      print("ERROR: ", err)
```
its possible use aws cluster ? or only single node ?

**Comment by Grokzen** [comment]
`MOVED` error is only a feature that is enabled in a cluster envrionment. This lib do not support a clustered redis envrionment to deal with the sharding behaviour in a cluster env. This is the docs/specification for redis cluster https://redis.io/topics/cluster-spec

**Comment by macklus** [comment]
ok, thanks
