### ISSUE TITLE
count=-1 will stop working for XPENDING (xpending_range)

### ISSUE THREAD

**Issue by coleifer** [andymccurdy/redis-py#1046]
Relevant method in redis-py: https://github.com/andymccurdy/redis-py/blob/d14f929ef024d62148b317f5e4197349d548e6a2/redis/client.py#L1925-L1926

Here's the Redis commit which changed this behavior:

https://github.com/antirez/redis/commit/edeaf85cab10b2d9bc151363779f70822d679472

Conversation here:

https://github.com/antirez/redis/pull/5459#issuecomment-433929399

**Comment by gyermolenko** [comment]
fixed in 977e739e386b4085086c14d2cde4007761f36566

**Comment by andymccurdy** [comment]
Thanks. Closing this since it was already fixed.
