### ISSUE TITLE
Please release a new version~

### ISSUE THREAD

**Issue by LKI** [andymccurdy/redis-py#1048]
The latest version on PyPI is 2.10.6 (which is released on 2017-08-17).
Lots of useful features and various bugfixes are added after that.

`pip install https://github.com...` is ok, but it's not good as `pip install redis`~

Please release a new version on PyPI~
Thanks 😸

**Comment by itamarhaber** [comment]
Hello @LKI 

The release of a new version is indeed what we're working on - please stay tuned.

**Comment by LKI** [comment]
@itamarhaber thanks~
