### ISSUE TITLE
CLIENT KILL options are not supported

### ISSUE THREAD

**Issue by itamarhaber** [andymccurdy/redis-py#1060]
Only the old form of `ip:address` is currently supported. Need to implement ADDR (for multiple kills), TYPE and SKIPME.

**Comment by theodesp** [comment]
Is that OK if I attempt to implement this?

**Comment by itamarhaber** [comment]
Hello @theodesp - sure, please free to do so.

**Comment by theodesp** [comment]
All comments welcome
https://github.com/andymccurdy/redis-py/pull/1098

**Comment by andymccurdy** [comment]
Oops, forgot to close this after #1098 was merged. Thanks again for the patch @theodesp
