### ISSUE TITLE
How can I preheat ConnectionPool?

### ISSUE THREAD

**Issue by ethe** [andymccurdy/redis-py#1065]
`ConnectionPool`'s initializer does not create connections immediately, in some cases this strategy  causes some problem, so is there anyway to preheat connection pool (create some IDLE connections in pool initializing)?

**Comment by andymccurdy** [comment]
Short answer, there's no automatic way to do this. You could do this manually by acquiring N number of connections, running a common on each of them, then releasing them all back to the connection pool.

**Comment by tzickel** [comment]
What problems does it cause ?

**Comment by tzickel** [comment]
Not sure how it's related to your problem ? If you preheat tons of connections at start won't that just make it crash sooner ?

**Comment by ethe** [comment]
> Not sure how it's related to your problem ? If you preheat tons of connections at start won't that just make it crash sooner ?

The problem is, if there is no connection at the beginning, server's performance decreased heavily (cause connection pool should make connection before every request, it is a heavy overhead).

**Comment by ethe** [comment]
Lots of Redis driver accepts optional `max_idle_connections` param let user choose if keep connections in idle time (includes beginning). Yeah there is a manual way to do this in redis-py (call `make_connection` I think), but I think it is more convenience if this feature is integrated in driver.

**Comment by theodesp** [comment]
Hey how can we implement this? Having a initial capacity property that will invoke the make_connection so many times and keep that number in the _available_connections ?

**Comment by antsbean** [comment]
> Short answer, there's no automatic way to do this. You could do this manually by acquiring N number of connections, running a common on each of them, then releasing them all back to the connection pool.

why not do add max_idle_connections  feature
