### ISSUE TITLE
Why is Token needed at all ?

### ISSUE THREAD

**Issue by tzickel** [andymccurdy/redis-py#1066]
Couldn't all non space containing Token usages simply be replaced with b'' ? for example instead of Token.get_token('TYPE') just type b'TYPE' ?

The space containing ones (command names with spaces) could be replaced with a tuple that in the execution phase can simple untupled.

**Comment by andymccurdy** [comment]
Token was introduced in response to #430 

Perhaps our Py3 support wasn't great at that point. I'm not entirely sure I didn't just use bytes 5 years ago.

**Comment by andymccurdy** [comment]
Did a little more digging. At the time `Token` was released, redis-py still supported Python 2.5 which did now allow for byte strings defined with `b''`. This may not be the only reason, but it likely was at least part of it.

**Comment by tzickel** [comment]
Looking at the code that seems to be the only reason. Might be worth trying to remove it totally from the code base.

**Comment by itamarhaber** [comment]
Deleted code is the best code...

**Comment by andymccurdy** [comment]
The Token class has been completely removed. We're now using bytestrings for all non-command-name literals. Command names continue to be special.

I know of at least a few users who call `Redis.execute_command()` directly, e.g., `r.execute_command('get', 'foo')`. Requiring that the command name be a bytestring might break those users. We could potentially clean that up within `execute_command`, but then we're just moving the complexity around the codebase.
