### ISSUE TITLE
redis-py should start it's own redis-server in tests

### ISSUE THREAD

**Issue by tzickel** [andymccurdy/redis-py#1072]
https://gist.github.com/tzickel/27ef7bbc459ce70be850c2407fbd0091

This way tests can be run on several redis server versions (via docker) and/or also check unix domain (which the current tests don't do).

Some tests currently are hardcoded to port 6379 (and db 9) and don't get them from a fixture.

**Comment by andymccurdy** [comment]
I'm don't think we should be starting server process(es) from the test runner. That seems very brittle and something that will easily break.

However I do agree that more configurability would be nice. Perhaps using environment variables with localhost/6379 fallback?

**Comment by tzickel** [comment]
Why is it brittle / easily break? that's what I do in my workflow and it works great.

**Comment by andymccurdy** [comment]
1. Not everyone has docker or wants to use it.
2. The redis-server binaries could be installed anywhere on the system. How would the tests magically find them?
3. Some people may rely on a remote redis-server to test against. Especially folks contributing to redis-py while working on a Windows machine.

**Comment by tzickel** [comment]
1. The tests could start with a docker version (and you can specify which version in an environment version), docker works on windows and can run redis there as well. This way you can even test against different versions of the server (like CI tests today with and without hiredis).
2. As a fallback it can try running redis-server via the PATH settings (usually people install redis via package manager means it's in PATH, which is why I use shell=True there) (in windows it can even run redis from WSL I would think).
3. In the end if it couldn't do both, it can simply do as today and use an existing server.
4. When we control the server we can try things like starting it with a unixsocket and test that code path we missed and that isn't tested today like #1069 
5. Some tests like all of test_sentinal (but not only) are hardcoded to the params inside the tests (localhost/6379/9).

**Comment by theodesp** [comment]
Nearly all the major Redis clients (redigo, node-redis, jedis, etc) avoid using a setup like that and opt-in for a simple approach like the one this library uses. I'm not convinced that we should use that now.

**Comment by andymccurdy** [comment]
I've thought about this some more and I continue to believe it's not a good idea.
