### ISSUE TITLE
TestRedisCommands.test_xpending_range fails with Redis 5.0.1

### ISSUE THREAD

**Issue by felixonmars** [andymccurdy/redis-py#1073]
I am running the test suite with the latest 3.0.1 tag, and got the following test failure. Am I missing something here?

```
=================================== FAILURES ===================================
____________________ TestRedisCommands.test_xpending_range _____________________

self = <tests.test_commands.TestRedisCommands object at 0x7f612efbdeb8>
r = Redis<ConnectionPool<Connection<host=localhost,port=6379,db=9>>>

    @skip_if_server_version_lt('5.0.0')
    def test_xpending_range(self, r):
        stream = 'stream'
        group = 'group'
        consumer1 = 'consumer1'
        consumer2 = 'consumer2'
        m1 = r.xadd(stream, {'foo': 'bar'})
        m2 = r.xadd(stream, {'foo': 'bar'})
        r.xgroup_create(stream, group, 0)

        # xpending range on a group that has no consumers yet
        assert r.xpending_range(stream, group) == []

        # read 1 message from the group with each consumer
        r.xreadgroup(group, consumer1, streams={stream: 0}, count=1)
        r.xreadgroup(group, consumer2, streams={stream: m1}, count=1)

        response = r.xpending_range(stream, group)
>       assert len(response) == 2
E       assert 0 == 2
E        +  where 0 = len([])

tests/test_commands.py:2027: AssertionError
=============== 1 failed, 382 passed, 1 skipped in 9.83 seconds ================
```

```
platform linux -- Python 3.7.1, pytest-4.0.0, py-1.7.0, pluggy-0.8.0
```

**Comment by lamby** [comment]
I can [reproduce this issue on the Debian continuous integration platform](https://ci.debian.net/data/autopkgtest/testing/amd64/p/python-redis/1389088/log.gz).

**Comment by lamby** [comment]
I ended up [marking these (and others) as "strict" `XFAIL` for now](https://salsa.debian.org/lamby/pkg-python-redis/commit/3444c92433e0d383916fac86fb19ae351c415a50) as the test regression was preventing the latest version of `redis-py` entering Debian testing.

**Comment by andymccurdy** [comment]
What version of Redis server are you using?

**Comment by lamby** [comment]
`5.0.3`, but could reproduce with `5.0.1` and `5.0.2` at the very least.

**Comment by andymccurdy** [comment]
It looks like something changed from Redis server 5.0.0 - 5.0.1 as all the tests pass on 5.0.0.

**Comment by andymccurdy** [comment]
Tracked this down to a server change in Redis 5.0.1 and beyond with the XREADGROUP command. The redis-py test suite is now updated to work all versions of Redis.

**Comment by lamby** [comment]
Thanks; looking forward to the next release. :)
