### ISSUE TITLE
redis.Lock.acquire should take a timeout kwarg just like threading.Lock

### ISSUE THREAD

**Issue by macbeth322** [andymccurdy/redis-py#1079]
https://github.com/andymccurdy/redis-py/blob/master/redis/lock.py#L135 as the title says `redis.Lock.acquire` should take a `timeout` kwarg to match the behavior of `threading.Lock`.

**Comment by andymccurdy** [comment]
`Lock.acquire` accepts `blocking_timeout`, which I believe is what you're looking for.
