### ISSUE TITLE
What version of Redis does redis-py 2.10.6 support? where can I find this info?

### ISSUE THREAD

**Issue by storm2013ak** [andymccurdy/redis-py#1081]
What version of redis does redis-py 2.10.6 support? Can redis-py 2.10.6 support redis 4.0.11 for example? I couldn't find it in project description.

**Comment by andymccurdy** [comment]
2.10.6 can talk to any version of Redis server. However 2.X is missing implementation for some commands found in Redis 4.0 and 5.0.

**Comment by storm2013ak** [comment]
Thanks for clarification
