### ISSUE TITLE
Redis Subscriber not responsing

### ISSUE THREAD

**Issue by WoodProgrammer** [andymccurdy/redis-py#1088]
I've got a nodejs webclient communicate with redis pubsub with other middleware services .

Middleware service written with Python .First hours we have no any problem but after several hours , when I PUBLISH a channel from nodeJs client python service did not response anything .

NodeJs ------> (PUB) |-----CHANNEL -----| -----> (SUB) Python Service

How I can handle this problem .

My python code is shown as below ,

def RedisCheck():
  try:

    r = redis.StrictRedis(host=os.environ["REDIS_HOST"], port=6379)

    p = r.pubsub(

    if __name__ == "__main__":

          RedisCheck()
That is my redis connection code .

Why py-redis connection is sleeping when connection time up . 

Best Regards .

**Comment by andymccurdy** [comment]
Can you try to post your Python code again? It looks like there was a formatting error and some of it got cut off.

**Comment by WoodProgrammer** [comment]
Sorry , 

      import sys
      import time
      import os
      from redis import StrictRedis

      HOST = os.environ["REDIS_HOST"]
      redis = StrictRedis(host=HOST, port=6379)

      pubsub = redis.pubsub()
      pubsub.psubscribe('__key*__:*')

      print('Starting message loop')
      while True:
          message = pubsub.get_message()
          print(message["data"])

That is the full of my code block . When I run this code 2 3 days at production server , when send a message from redis publisher I've no response from any consumers (this code block is consumer's).

**Comment by andymccurdy** [comment]
I suspect that the TCP connection between the client and server is getting dropped after some amount of inactivity. Several ways you could fix this:

1. Use TCP keepalive options when creating the client connection. See here: https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L588 The options depend on your OS.

Have you upgraded to redis-py 3.0 yet? If so, you might try adding a `pubsub.ping()` in your loop after so many iterations. This will force data to be sent and received over the connection to help make sure the connection is still active. `pubsub.ping()` was added in redis-py 3.0.

**Comment by theodesp** [comment]
@WoodProgrammer There is a relevant article about that:
https://hackernoon.com/keeping-your-connections-alive-a-clojure-redis-story-3b226b91a3d5

**Comment by WoodProgrammer** [comment]
I think this problem is about network structure , for example when if any event appear at network traffic, connection will down at RabbitMQ so we are using simple heartbeat packages so that network is always live up .

I've changed my own architect so I implemented to new livenessProbe and healthcheck of my consumer service which using Redis-py .

**Comment by andymccurdy** [comment]
It sounds like you've determined this is an issue on your network and not a redis-py issue. I'm going to close this for now. If I'm incorrect and you still believe this to be a redis-py isssue, please feel free to reopen this issue. Thanks!

**Comment by FrostyTheSouthernSnowman** [comment]
I have some similar code on localhost, but it also won't run.
