### ISSUE TITLE
Lock.release() always fails in python 3.6.6 (Redis-py 2.10.5)

### ISSUE THREAD

**Issue by benileo** [andymccurdy/redis-py#1091]
```
>>> import sys
>>> sys.version_info
sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
>>> import redis
>>> redis.__version__
'2.10.5'
>>> redis_connection = redis.StrictRedis(host='redis', port=6379, decode_responses=True)
>>> lock = redis.lock.Lock(redis_connection, 'aa29f76d-f2be-4acb-abd8-7e74a336ceda')
>>> lock.acquire()
True
>>> lock.release()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/redis/lock.py", line 135, in release
    self.do_release(expected_token)
  File "/usr/local/lib/python3.6/dist-packages/redis/lock.py", line 146, in do_release
    self.redis.transaction(execute_release, name)
  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 490, in transaction
    func_value = func(pipe)
  File "/usr/local/lib/python3.6/dist-packages/redis/lock.py", line 143, in execute_release
    raise LockError("Cannot release a lock that's no longer owned")
redis.exceptions.LockError: Cannot release a lock that's no longer owned
>>> 
```

Redis-py Version: 2.10.5
Python Version: 3.6.6

The functionality used to work in python 2.7, but now simply acquiring and releasing a lock fails. I tried in with block as well with same result.

Am I doing something wrong or is this a bug?
Thank you.

**Comment by benileo** [comment]
FWIW the issue is not found in redis-py 3.0+

**Comment by andymccurdy** [comment]
Perhaps this is a bug in an old version. 2.10.5 is 3 years old. I'd suggest upgrading to at least 2.10.6 and testing with that.

3.0.1 has numerous lock improvements, especially if you use the lock as a context manager. 3.x does have a few backwards incompatibilities however, so make sure you understand those before upgrading.

**Comment by benileo** [comment]
I observe same behaviour in 2.10.6. I think an upgrade to 3.0+ is very likely :)

**Comment by theodesp** [comment]
I can replicate this on that version. The reason is a type mismatch when comparing the local token with the expected token here. For example:
```
lock_value
'532d532cf74b11e89bc0a45e60d2bdff'
expected_token
b'532d532cf74b11e89bc0a45e60d2bdff'

lock_value != expected_token
True
```
I suspect a newer version fixes this issue.

**Comment by andymccurdy** [comment]
This has in fact been fixed in newer versions of redis-py. I would suggest upgrading. Apologies for the confusion.
