### ISSUE TITLE
Error 111, connection refused

### ISSUE THREAD

**Issue by abylikhsanov** [andymccurdy/redis-py#1092]
Hi,

I have an app running on Heroku and I am using Python 3.6 with Redis + Celery. Whenever, I connect to my app via socket and try to run some command (commands go to the celery tasks) I get this error that the connection refused:

`{"message": "Error 111 connecting to ec2-54-158-35-36.compute-1.amazonaws.com:8029. ECONNREFUSED.", "asctime": "2018-12-02T12:56:52Z+0000", "name": "socket_routes", "processName": "MainProcess", "filename": "socket_routes.py", "funcName": "error_handler", "levelname": "ERROR", "lineno": 325, "module": "socket_routes", "threadName": "MainThread", "exc_info": "Traceback (most recent call last):\n  File \"/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py\", line 484, in connect\n    sock = self._connect()\n  File \"/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py\", line 541, in _connect\n    raise err\n  File \"/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py\", line 529, in _connect\n    sock.connect(socket_address)\n  File \"/app/.heroku/python/lib/python3.6/site-packages/eventlet/greenio/base.py\", line 261, in connect\n    socket_checkerr(fd)\n  File \"/app/.heroku/python/lib/python3.6/site-packages/eventlet/greenio/base.py\", line 50, in socket_checkerr\n    raise socket.error(err, errno.errorcode[err])\nConnectionRefusedError: [Errno 111] ECONNREFUSED\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/app/.heroku/python/lib/python3.6/site-packages/redis/client.py\", line 2408, in _execute\n    return command(*args)\n  File \"/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py\", line 610, in send_command\n    self.send_packed_command(self.pack_command(*args))\n  File \"/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py\", line 585, in send_packed_command\n    self.connect()\n  File \"/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py\", line 489, in connect\n    raise ConnectionError(self._error_message(e))\nredis.exceptions.ConnectionError: Error 111 connecting to ec2-54-158-35-36.compute-1.amazonaws.com:8029. ECONNREFUSED.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py\", line 484, in connect\n    sock = self._connect()\n  File \"/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py\", line 541, in _connect\n    raise err\n  File \"/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py\", line 529, in _connect\n    sock.connect(socket_address)\n  File \"/app/.heroku/python/lib/python3.6/site-packages/eventlet/greenio/base.py\", line 261, in connect\n    socket_checkerr(fd)\n  File \"/app/.heroku/python/lib/python3.6/site-packages/eventlet/greenio/base.py\", line 50, in socket_checkerr\n    raise socket.error(err, errno.errorcode[err])\nConnectionRefusedError: [Errno 111] ECONNREFUSED\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py\", line 626, in _handle_event\n    ret = handler(*args)\n  File \"/app/socket_routes.py\", line 40, in inner\n    return f(wheelme_id, other_arg, **kwargs)\n  File \"/app/socket_routes.py\", line 292, in rotateDirection\n    rotate.delay(wheelme_id, change_in_direction_left_is_positive)\n  File \"/app/.heroku/python/lib/python3.6/site-packages/celery/app/task.py\", line 413, in delay\n    return self.apply_async(args, kwargs)\n  File \"/app/.heroku/python/lib/python3.6/site-packages/celery/app/task.py\", line 536, in apply_async\n    **options\n  File \"/app/.heroku/python/lib/python3.6/site-packages/celery/app/base.py\", line 736, in send_task\n    self.backend.on_task_call(P, task_id)\n  File \"/app/.heroku/python/lib/python3.6/site-packages/celery/backends/redis.py\", line 189, in on_task_call\n    self.result_consumer.consume_from(task_id)\n  File \"/app/.heroku/python/lib/python3.6/site-packages/celery/backends/redis.py\", line 75, in consume_from\n    return self.start(task_id)\n  File \"/app/.heroku/python/lib/python3.6/site-packages/celery/backends/redis.py\", line 57, in start\n    self._consume_from(initial_task_id)\n  File \"/app/.heroku/python/lib/python3.6/site-packages/celery/backends/redis.py\", line 82, in _consume_from\n    self._pubsub.subscribe(key)\n  File \"/app/.heroku/python/lib/python3.6/site-packages/redis/client.py\", line 2482, in subscribe\n    ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))\n  File \"/app/.heroku/python/lib/python3.6/site-packages/redis/client.py\", line 2404, in execute_command\n    self._execute(connection, connection.send_command, *args)\n  File \"/app/.heroku/python/lib/python3.6/site-packages/redis/client.py\", line 2415, in _execute\n    connection.connect()\n  File \"/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py\", line 489, in connect\n    raise ConnectionError(self._error_message(e))\nredis.exceptions.ConnectionError: Error 111 connecting to ec2-54-158-35-36.compute-1.amazonaws.com:8029. ECONNREFUSED.", "timestamp": "2018-12-02T12:56:52Z+0000"}
`

I have tried to go and see the source code of Redis but still can't get what is going on. Why the connection is getting refused by Redis?

**Comment by itamarhaber** [comment]
Hello @abylikhsanov 

Are you sure that your Redis server is running on the same instance as your app? AFAIR this isn't the Heroku way, and that means you can't use socket connections - stick with TCP.

**Comment by abylikhsanov** [comment]
@itamarhaber How can I check that Redis is running? I might be doing it wrong

**Comment by abylikhsanov** [comment]
I went to the REDIS credentials and they have been changed. Thanks for that, I will go and change to a new URI on my app

**Comment by itamarhaber** [comment]
Sure - closing this issue as it isn't related to redis-py.
