### ISSUE TITLE
StrictRedis blocked if socket_timeout=None

### ISSUE THREAD

**Issue by rebornfxx** [andymccurdy/redis-py#1094]
This is my code snippet:
`redis_client = redis.StrictRedis(host=redis_ip, port=redis_port, db=redis_no, password=passwd)`
`while(True): {`
`	id = get_item_from_kafka() #get id from kafka`
`	redis_client.get(id)`
`	time.sleep(1)`
`	print id`
`}`
Is there any condition that this code snippnet blocked and never print id again(At the beginning, the code works fine and print id for several time). The socket_timeout parameter by default is None. 

Ps:this code is run in k8s

**Comment by andymccurdy** [comment]
There's not enough information here to figure out what's going on. Are you sure the `redit_client.get()` call is the one blocked? Could the call to get the ID from kafka be the culprit?

**Comment by rebornfxx** [comment]
Thanks for the analysis, I'll add more log info to find the real culprit

**Comment by andymccurdy** [comment]
No info has been added for 6 months. I'm going to close this issue. If you're still having this issue and can provide more info, please feel free to reopen.
