### ISSUE TITLE
add 'overflow' type connection pool

### ISSUE THREAD

**Issue by nerdvegas** [andymccurdy/redis-py#1103]
**Version**: all

**Platform**: all

**Description**: Standard connpool errors when max conns hit. Blocking pool blocks. However there is no option for an 'overflow' type pool, akin to urllib3's HTTPConnectionPool, where conns outside of the pool are created when max conns is hit, and a warning message is printed.

**Comment by andymccurdy** [comment]
I'm going to comment #1104

**Comment by theodesp** [comment]
I've also added a comment

**Comment by andymccurdy** [comment]
Closing this as #1104 says.
