### ISSUE TITLE
Does the redis-py multiprocessing safe when share a connection pool?

### ISSUE THREAD

**Issue by HDong0714** [andymccurdy/redis-py#1107]
**Version**: 3.0

**Platform**: Python2.7 on MacOS10.13.6

**Description**: 
Multiprocessing will share one redis connection pool, is that ok?

**Comment by itamarhaber** [comment]
Hello @HDong0714 

Yes, pools are thread-safe.

**Comment by guidog** [comment]
Thread != Process

Inheriting open connections across processes is a bad idea.

**Comment by andymccurdy** [comment]
Starting with redis-py 3.2.0, Connection Pools are safe to share across forks/multiprocessing environments.
