### ISSUE TITLE
**ValueError: filedescriptor out of range in select()**

### ISSUE THREAD

**Issue by Fux002** [andymccurdy/redis-py#1115]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: What redis-py and what redis version is the issue happening on?
latest one

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
py3.5 on ubuntu

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue
**ValueError: filedescriptor out of range in select()**
i cant have more that 1024 streams open and i need a lot more. how can i resolve this please?
this link helps but doesn t give me the answer. whats is a good work around?
https://stackoverflow.com/questions/14250751/how-to-increase-filedescriptors-range-in-python-select

thx a lot!

**Comment by Fux002** [comment]
Hi thank you for the reply!

I run the scripts on:
(Ubuntu 16.04 64bit / Linux 4.4.0-1074-aws)

And use python 3.5

See this link please:

https://stackoverflow.com/questions/14250751/how-to-increase-filedescriptors-range-in-python-select

*"There is a limit to the number of file descriptors that select() supports
- the easiest solution is to simply use poll() instead, which doesn't
suffer from this limit.*

*Strictly speaking, select() is limited in the highest file descriptor it
can support, as opposed to the number of them in a given call - see the
start of the Notes section of the select() manpage. I'm not sure
what FD_SETSIZE is on OSX, but on Linux it's 1024. There's no practical way
to increase this limit from Python.As an aside, if you want to keep things
portable you might consider using something like pyevwhich is a Python
wrapper around libev library which uses the optimal method of waiting for
IO on a given platform."*

What do you suggest I should do? I was thinking of Celery and use these
workers on the Redis streams.

**Comment by Fux002** [comment]
Hi any thoughts on this please?

**Comment by andymccurdy** [comment]
@Fux002 Are you using pubsub or Redis streams? I'm not sure based on the report.

I'd first try increasing the number of file descriptors on the OS. You can do this with the `ulimit` command. I'm not sure whether this will help but it's where I'd start.

**Comment by Fux002** [comment]
Hi Andy,

I use pubsub and the eventhandler on threads.

I did that and run in to the error as per the link that has to do with
select not allowing more file descriptors. The solution i read about is use
poll or epoll. Is this implemented in your library?

Is is possible to implement.

Kind regards,

Fons

**Comment by andymccurdy** [comment]
Currently only `select()` is implemented. PRs are accepted however :)

**Comment by Fux002** [comment]
ok! thank you!,

Is it difficult to convert it to use epoll for example?
Would anyone be willing to do this? :)

**Comment by andymccurdy** [comment]
Off the top of my head I have no idea how simple or difficult this would be. I wrote the `select()` implementation because I was familiar with it and it was straight forward.

**Comment by Fux002** [comment]
If im not mistaking its the _compat.py

So ill have to rewrite that for using epoll?

**Comment by andymccurdy** [comment]
ya, the `Connection.can_read()` method specifically.

**Comment by Fux002** [comment]
ok got it. its not my specialty this far from but will give it a go :s

**Comment by andymccurdy** [comment]
This issue has been resolved in 3.2.0 assuming your OS has `select.poll` available.

**Comment by zhaianbang** [comment]
将/anaconda3/envs/genesis/lib/python3.9/site-packages/pyglet/app/xlib.py中的class XlibEventLoopIni(PlatformEventLoop):替换为以下内容，就可以解决    pending_devices, _, _ = select.select(self.select_devices, (), (), timeout)
ValueError: filedescriptor out of range in select()的问题：

import selectors

class XlibEventLoop(PlatformEventLoop):
    def __init__(self):
        super(XlibEventLoop, self).__init__()
        self._notification_device = NotificationDevice()
        self.select_devices = set()
        self.select_devices.add(self._notification_device)

        # 初始化 selectors.DefaultSelector
        self.selector = selectors.DefaultSelector()

        # 注册初始设备（如通知设备）到 selector
        for device in self.select_devices:
            self.selector.register(device, selectors.EVENT_READ)

    def notify(self):
        """
        通知事件循环有新事件需要处理（用于唤醒事件循环）。
        """
        self._notification_device.set()

    def step(self, timeout=None):
        """
        执行事件循环的一个步骤，处理所有准备好的事件。

        :param timeout: 超时时间（秒）。None 表示阻塞直到有事件。
        :return: 如果有事件被处理则返回 True，否则返回 False。
        """
        # 预先检查已准备好的设备
        pending_devices = []
        for device in self.select_devices:
            if device.poll():  # 检查设备是否有事件需要处理
                pending_devices.append(device)

        # 如果没有设备准备好，使用 selector 阻塞等待事件
        if not pending_devices:
            # timeout 传递给 selector.select，用于设置等待时间（秒）
            events = self.selector.select(timeout)

            # 将所有触发事件的设备添加到 pending_devices
            for key, _ in events:
                pending_devices.append(key.fileobj)

        # 如果仍然没有准备好的设备，则返回 False（超时或无事件）
        if not pending_devices:
            return False

        # 对每个准备好的设备，调用其 select() 方法处理事件
        for device in pending_devices:
            device.select()

        # 返回 True 表示成功处理了至少一个事件
        return True

    def register_device(self, device):
        """
        向事件循环中注册新的设备。

        :param device: 要注册的设备对象。
        """
        if device not in self.select_devices:
            self.select_devices.add(device)
            self.selector.register(device, selectors.EVENT_READ)

    def unregister_device(self, device):
        """
        从事件循环中移除设备。

        :param device: 要移除的设备对象。
        """
        if device in self.select_devices:
            self.select_devices.remove(device)
            self.selector.unregister(device)
