### ISSUE TITLE
Inconsistent / confusing results for XREADGROUP

### ISSUE THREAD

**Issue by johntmyers** [andymccurdy/redis-py#1118]
**Version**: What redis-py and what redis version is the issue happening on?

3.0.1 / 5.0.3

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)

Docker

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

Results sent from XREADGROUP are confusing since it's all just a bunch of nested lists. The results seem like they should fit nicely into a dict.

First, using `>` as the special ID vs any other ID yields a different data structure back.

```python
In [446]: r.xreadgroup('group', 'c', {'test': '>'})
Out[446]: []

In [447]: r.xreadgroup('group', 'c', {'test': '0'})
Out[447]: [['test', []]]
```

Since we are providing a dict as arguments, why aren't we getting a dict back where the keys are always the names of the streams and the values are then lists containing results? It seems way more consistent to parse.

More examples:

```python
In [457]: r.xreadgroup('group', 'c', {'test': '>', 'test2': '0'})
Out[457]:
[['test',
  [('1547076388340-0', {'msg': 'foo'}),
   ('1547076390789-0', {'msg': 'foo2'}),
   ('1547076393514-0', {'msg': 'foo3'}),
   ('1547128615067-0', {'msg': 'foo3'}),
   ('1547128617820-0', {'msg': 'foo2'}),
   ('1547128620451-0', {'msg': 'foo1'})]],
 ['test2', []]]

In [458]: r.xreadgroup('group', 'c', {'test': '>', 'test2': '0'})
Out[458]: [['test2', []]]

In [459]: r.xreadgroup('group', 'c', {'test': '>', 'test2': '>'})
Out[459]: [['test2', [('1547128779169-0', {'msg': 'foo'})]]]
```

**Comment by itamarhaber** [comment]
Hello @johntmyers 

Definitely agreeing here /cc @RoeyPrat

**Comment by andymccurdy** [comment]
The thinking on the return format is so you can easily iterate with:

```
for stream, messages in r.xreadgroup(...):
    for message in messages:
        ...
```

The first implementation of `XREAD` and `XREADGROUP` did in fact return a dict of stream_name -> list_of_messages. However after discussing with @RoeyPrat I believe (and please correct me if I'm wrong) you almost always want look at every message being returned by these commands (e.g., some form of the iteration above). Returning them as a dict just meant slightly more typing (you need to call `dict.items()`) to do the same iteration as above.

**Comment by andymccurdy** [comment]
@johntmyers Your example above with asking for ID `0` (vs. `>`) is intended behavior. The server docs state:

```
Any other ID, that is, 0 or any other valid ID or incomplete ID (just the millisecond time part), will have the effect of returning entries that are pending for the consumer sending the command. So basically if the ID is not >, then the command will just let the client access its pending entries: delivered to it, but not yet acknowledged.
```

So you're getting an empty list back when you pass `0` as the ID because you don't have any messages pending for your consumer that aren't already acknowledged.

**Comment by johntmyers** [comment]
Right but my point was that when using ‘>’ and you get back empty results the stream name isn’t included but when using any other ID the stream name is always included. 

It’s inconsistent with how redis-py is presenting the results.

**Comment by itamarhaber** [comment]
The inconsistency is problematic - that's what I meant by "agreeing" but rereading I see how I missed making my point clear :)

I'd be very comfortable with having the client render the `>` reply to a data structure consistent with the expected reply format.

**Comment by gyermolenko** [comment]
Let me try to sum discussion up

1.
> why aren't we getting a dict back where the keys are always the names of the streams and the values are then lists containing results?

This one was addressed by @andymccurdy above 4 comments above.

2. `redis-py` returns results as `redis-cli` does, which is inconsistent in case like
```
127.0.0.1:6375> XREADGROUP GROUP mygroup Alice STREAMS mystream 0
1) 1) "mystream"
   2) (empty list or set)
127.0.0.1:6375> XREADGROUP GROUP mygroup Alice STREAMS mystream >
(nil)
```

Which can be addressed by changing return format of `r.xreadgroup`, passing additional argument or with helper function.
