### ISSUE TITLE
Documentation needs example

### ISSUE THREAD

**Issue by fabltd** [andymccurdy/redis-py#1121]
I am updating our code base and have hit an error with zadd.

It seems the new version of redis-py has altered the operation of zadd.

**There is a note to this effect:**
> def zadd(self, name, mapping, nx=False, xx=False, ch=False, incr=False):

The documentation lacks any example of how **mapping** should be formed!

**A simple example would be great.**

Please can some one give me a complete example and may also add this to the documentation for any one else with this issue.

Thank you

**Comment by andymccurdy** [comment]
https://github.com/andymccurdy/redis-py/blob/master/README.rst#mset-msetnx-and-zadd

ZADD's `mapping` is a dict of element name -> score.
