### ISSUE TITLE
Inconsistent handling of empty generator arguments.

### ISSUE THREAD

**Issue by jenstroeger** [andymccurdy/redis-py#1122]
#### Version and platform
```
Python 3.7.1 (default, Oct 21 2018, 09:01:26) 
[Clang 10.0.0 (clang-1000.11.45.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import redis
>>> redis.__version__
'2.10.6'
>>> 
```
and
```
127.0.0.1:6379> help
redis-cli 4.0.11
```
#### Issue
I have noticed an inconsistency between the `delete()` and `mget()` client wrapper functions, but the issue might extend to other wrapper functions as well.

Looking at how Redis itself behaves:
```
127.0.0.1:6379> del 'a'
(integer) 0
127.0.0.1:6379> del
(error) ERR wrong number of arguments for 'del' command
127.0.0.1:6379> mget 'a'
1) (nil)
127.0.0.1:6379> mget
(error) ERR wrong number of arguments for 'mget' command
```
Note that both, `del` and `mget` commands require at least one key argument. However, the `delete()` wrapper function for `del` accepts an empty generator and returns—expectedly so—an empty result set:
```
>>> r = redis.Redis()  # Works the same with StrictRedis().
>>> r.delete(range(0))
0
```
In contrast, the `mget()` wrapper function for `mget` raises an exception instead of returning an empty result set:
```
>>> r.mget(range(0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/…/redis-2.10.6-py3.7.egg/redis/client.py", line 1039, in mget
    return self.execute_command('MGET', *args)
  File "/…/redis-2.10.6-py3.7.egg/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/…/redis-2.10.6-py3.7.egg/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/…/redis-2.10.6-py3.7.egg/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: wrong number of arguments for 'mget' command
```
It would make sense (and would be more “pythonic”) if wrapper functions would handle empty generators more consistently and gracefully, if possible.

**Comment by andymccurdy** [comment]
This should be resolved in redis-py 3.0

**Comment by jenstroeger** [comment]
Great, thanks @andymccurdy! Do you have a guesstimated timeline for v3.0 already?

**Comment by andymccurdy** [comment]
3.0 was released 2 months ago :)

**Comment by jenstroeger** [comment]
Hah! Well hot diggity, I need to update. Closing this issue then… 🙃

**Comment by jenstroeger** [comment]
@andymccurdy, looks like a regression (and failure reversal) since I have opened the original issue:
```
>>> import redis
>>> redis.__version__
'3.1.0'
>>> r = redis.Redis()  # Same problem with StrictRedis.
>>> r.delete(range(0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/…/lib/python3.7/site-packages/redis/client.py", line 1225, in delete
    return self.execute_command('DEL', *names)
  File "/…/lib/python3.7/site-packages/redis/client.py", line 774, in execute_command
    connection.send_command(*args)
  File "/…/lib/python3.7/site-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/…/lib/python3.7/site-packages/redis/connection.py", line 659, in pack_command
    for arg in imap(self.encoder.encode, args):
  File "/…/lib/python3.7/site-packages/redis/connection.py", line 124, in encode
    "byte, string or number first." % typename)
redis.exceptions.DataError: Invalid input of type: 'range'. Convert to a byte, string or number first.
>>> r.delete(f"bla-{_}" for _ in range(0))
  …
redis.exceptions.DataError: Invalid input of type: 'generator'. Convert to a byte, string or number first.
```
Looking at the code, a quick-hack crummy solution would be to add something like the following to [`pack_command()`](https://github.com/andymccurdy/redis-py/blob/2f3afb0a2b6adaa7287173f07ea5b7fee8551083/redis/connection.py#L641):
```python
arghs = []
for a in args:
    if isinstance(a, (range, types.GeneratorType)):
        arghs += list(a)
    else:
        arghs.append(a)
args = arghs
```
I don’t know about unexpected side-effects of this addition especially for empty generators, but it looks to me as if the fix would be to unpack generators to produce the list of actual argument values for the Redis command.

However, now `mget` works as expected:
```
>>> r.mget(range(0))
[]
```

**Comment by andymccurdy** [comment]
`mget` works as you expect it to because of https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L1325. We could do the same for `delete` and other variadic commands. Or you could pass your generator as `*args` which would also work.

**Comment by jenstroeger** [comment]
> `mget` works as you expect it to […]

It does with v3 now, yes 👍🏼

> We could do the same for `delete` and other variadic commands. 

For consistency’s sake and to keep client code pythonic, yes please. Also note that `delete` used to work like that, but not anymore!

> Or you could pass your generator as `*args` which would also work.

That would also work, yes. It’s just not as perfectly pretty and pythonic as it could be 😉

One point though is the following:
```python
>>> r.mget(range(2))
[None, None]
>>> r.mget(range(0))
[]
>>> r.delete(*range(2))  # I think just range(2) would be nicer.
0
>>> r.delete(*range(0))
  …
redis.exceptions.ResponseError: wrong number of arguments for 'del' command
```
I would have expected a `0` return here as well. Again, it’s somewhat inconsistent behavior compared to `mget`: on Redis itself, _both_ fail with _ERR wrong number of arguments_ (see my comment [above](https://github.com/andymccurdy/redis-py/issues/1122#issue-398197054)); however, in the Python client code only `delete` now fails and `mget` works (previously it was the other way around: `delete` succeeded without arguments and `mget` failed).
