### ISSUE TITLE
Code'4b91837c-d276-4a2c-af7b-9427532a92ff

### ISSUE THREAD

**Issue by xtranophilist** [andymccurdy/redis-py#1123]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: What redis-py and what redis version is the issue happening on?

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

**Comment by andymccurdy** [comment]
Nothing here. Closing. If you have an issue, please provide some context.
