### ISSUE TITLE
Connections are left in an invalid state on interrupt

### ISSUE THREAD

**Issue by Chronial** [andymccurdy/redis-py#1128]
**Version**: Starting with 3.0.0, introduced by this commit: 04784cb2ecb0847198aaf64102e5129868c17da6

Thanks to the github related feature, I noticed that this is in fact a duplicate of #360 from 2013 – it was fixed back then in 80baa99. But 04784cb2ecb0847198aaf64102e5129868c17da6 (which was released as part of 3.0.0) accidentally reversed that change, so the bug is back.

## How to reproduce
```py
r = redis.Redis(host='localhost', port=6379, db=0)
try:
    print("Press Ctrl-C now")
    r.brpop(['nonexist'])
finally:
    print("This hangs:")
    r.set('status', 'down')
    print("We never get here")
```

**Comment by andymccurdy** [comment]
This was fixed, closing.
