### ISSUE TITLE
xinfo_stream 

### ISSUE THREAD

**Issue by chaotic1988** [andymccurdy/redis-py#1135]
**Version**: redis-py version 3.1.0, Redis: 5.0.3

**Platform**: Python3.6.5 on CentOS 7

**Description**: redis-py fails to parse `xinfo_stream` replies if the stream is emptied by XTRIM command.

For example,
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 2119, in xinfo_stream
    return self.execute_command('XINFO STREAM', name)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 775, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 795, in parse_response
    return self.response_callbacks[command_name](response, **options)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 278, in parse_xinfo_stream
    data['first-entry'] = (first[0], pairs_to_dict(first[1]))
TypeError: 'NoneType' object is not subscriptable
```

After inspecting the source code, I believe this issue is platform-independent. `parse_xinfo_stream` function in `client.py` assumes that `first-entry` and `last-entry` in the reply are valid enties. However, after `XTRIM STREAM <stream name> MAXLEN 0`, those two fields will become nil, which leads to the parse error.

**Comment by tarikki** [comment]
Ran into the same issue when created a consumer group and an empty stream with 

```   
    r = redis.Redis()  
    r.xgroup_create(STREAM_NAME, CONSUMER_GROUP, id='0', mkstream=True)
```

and then 

```
info = r.xinfo_stream(STREAM_NAME)
```

**Comment by andymccurdy** [comment]
@aachurin's fix has been merged. It will go out with the next release. Thanks for reporting this.
