### ISSUE TITLE
How to handle hang up in pubsub listen() after redis restart in some senario

### ISSUE THREAD

**Issue by zjqzero** [andymccurdy/redis-py#1137]
**Version**: 2.10.6

**Platform**: python 3.6.5 on windows

**Description**: 

steps to reappear this issue:

> 192.168.99.10 is redis server, runs on ubuntu 18.04 in vm

1. run pubsub listen
```
from redis import StrictRedis

r = StrictRedis('192.168.99.10')

ps = r.pubsub()

ps.subscribe('test')

for item in ps.listen():
	if item['type'] == 'message':
		print(item['data'])
```
2. change redis server's ip from 192.168.99.10/24 to 192.168.9.10/24
3. restart redis server instance; client will not recieve TCP Fin, because of no route to client
4. restore redis server's ip
5. client won't receive any redis message, except restart the python script, actual hung up, no any Exception

Is there any mechanism to prevent this senario?

thanks a lot.

**Comment by andymccurdy** [comment]
Can you try upgrading to redis-py 3.2.0? It does a much better job at ensuring connections are healthy.

**Comment by zjqzero** [comment]
thanks, 3.2.0 will raise ConnectionError, fixed this issue

**Comment by zjqzero** [comment]
sorry, I made mistake.  This issue exists in Version 3.2.0

**Comment by andymccurdy** [comment]
Do you know of a way that I could easily test this behavior?

**Comment by zjqzero** [comment]
it's very easy.

**Comment by andymccurdy** [comment]
I'll try to work on this over the next few days. I'm away for a bit but will have sporadic downtime to investigate.

**Comment by andymccurdy** [comment]
@zjqzero If you're still seeing this issue, I have a patch in a branch that may resolve the issue. Could you try running with the code here: https://github.com/andymccurdy/redis-py/tree/nonblocking

**Comment by zjqzero** [comment]
@andymccurdy I tested with the patch, but it seems this issue still exists.

**Comment by andymccurdy** [comment]
Is there anyway you can put together a sample project that reproduces the issue you're seeing?

**Comment by zjqzero** [comment]
I think the easiest way to reproduce this issue as following: 

1. redis server run on a virtual machine such as virtualbox
2. subscribe something,  python sample code as following:
```
from redis import StrictRedis

r = StrictRedis.from_url('redis://192.168.1.70/0', decode_responses=True)

ps = r.pubsub()
ps.subscribe('test')

for e in ps.listen():
    print(e)
```
3. close the virtual machine; just kill the process
4. check whether the python script stopped

now I use get_message with a timeout instead of listen to prevent hanging up forever

**Comment by andymccurdy** [comment]
I just tried this with the `nonblocking` branch and Virtualbox. I used `kill -9` from the host system to kill the Virtualbox processes. In all cases, the pubsub listen loop was immediately broken and a `ConnectionError` was raised, which seems like exactly what we want.

The only difference in my scenario is that I'm running the pubsub client on the host OS (mac osx) and connecting to the redis server running within the Virtualbox VM through a port to the host via Virtualbox.

**Comment by zjqzero** [comment]
I tried on windows and ubuntu with the nonblocking branch. The issue reproduced both your scenario and my scenario. I check site-packages the redis lib has been replaced. Even I uninstall the old version and copy redis directory to site-packages. Could you add some version info to nonblocking, at this time the same with redis 3.2.1

**Comment by andymccurdy** [comment]
I updated the package version to `3.3.dev1` in the `nonblocking` branch.

```python
In [1]: import redis                                                                                                                                           

In [2]: redis.__version__                                                                                                                                      
Out[2]: '3.3.dev1'
```

**Comment by zjqzero** [comment]
If I reboot the vm, a ConnectionError was raised: 
![reboot link](https://github.com/zjqzero/tmp/blob/master/reboot.png)

If I kill the vm, i waited 1 minute, no Error was raised:
![kill link](https://github.com/zjqzero/tmp/blob/master/kill.png)

**Comment by andymccurdy** [comment]
How are you killing the VM? When I tested I `kill -9` the VirtualBox process and got the ConnectionError.

**Comment by zjqzero** [comment]
I kill the vm the same. click the 'kill link' you will see. I have no idea what's the difference

**Comment by andymccurdy** [comment]
Is the redis-py client running within a VM as well? Or is it running on the host OS? I've tried a couple more times and can't repro this.

**Comment by zjqzero** [comment]
redis-py client runs on Host-OS and redis server runs on Gest-OS in docker.  Virtualbox version 6.0.8

**Comment by andymccurdy** [comment]
Without being able to reproduce this I can't really tell what's going on. If this is still an issue with redis-py 3.5.x+, feel free to re-open and please include instructions to reproduce the issue.
