### ISSUE TITLE
PubSub unsubscribe race condition

### ISSUE THREAD

**Issue by Raab70** [andymccurdy/redis-py#1150]
When unsubscribing from a `PubSubWorkerThread`, ie., using `PubSubWorkerThread.stop()` the unsubscribe message can be handled before the `PubSub.pending_unsubscribed_channels` set is updated. 

**Version**: redis-py 3.1.0+, Introduced in #1105 which fixed #764 

**Platform**: Ubuntu 14.04 trusty, OSX 10.12.6

**Description**: When stopping a pubsub thread a race condition exists where the `unsubscribe` message can be handled in `PubSub.handle_message` before `PubSub.pending_unsubscribed_channels` is updated. This can be reproduced with the following code, note that this does not happen every time. It appears to happen more when running similar code from within `nosetests` and happened predictably when running in Travis. Interesting also is if you remove the `q.put` channel callback it doesn't happen. 

`hang.py`:
```
import redis
from six.moves.queue import Queue

rc = redis.StrictRedis()
q = Queue()
idx = 1
while True:
    print(idx)
    idx += 1
    pubsub = rc.pubsub()
    pubsub.subscribe(channel=q.put)
    pubsub_thread = pubsub.run_in_thread()
    msg = b"Hello World"
    rc.publish("channel", msg)
    pubsub_thread.stop()
    pubsub_thread.join(timeout=1)
    assert pubsub_thread.is_alive() is False
```

One way to reliably get this working is with docker as follows:
```
$ docker run -it -v $(pwd):/usr/src/app ubuntu:trusty bash
root@74130d0f69de:/# apt-get update
root@74130d0f69de:/# apt-get install python3-pip redis-server
root@74130d0f69de:/# python3 -m pip install --upgrade pip
root@74130d0f69de:/# pip install redis==3.1.0
root@74130d0f69de:/# service redis-server start
Starting redis-server: redis-server.
root@74130d0f69de:/# cd /usr/src/app
root@74130d0f69de:/usr/src/app# python3 hang.py
1
Traceback (most recent call last):
  File "hang.py", line 17, in <module>
    assert pubsub_thread.is_alive() is False
AssertionError
^CException ignored in: <module 'threading' from '/usr/lib/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.4/threading.py", line 1060, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.4/threading.py", line 1076, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by andymccurdy** [comment]
Thanks for reporting this. I finally tracked down what was happening here and pushed a fix. Can you verify the new code works in your environment?

**Comment by Raab70** [comment]
Thanks @andymccurdy, I was able to install master and confirm that I can no longer reproduce this.
