### ISSUE TITLE
[Question] Order of Subscription callback execution

### ISSUE THREAD

**Issue by AlexEshoo** [andymccurdy/redis-py#1151]
I just have a simple question about the use of subscription objects. Is the order of execution of the callback handlers for subscriptions in the pubsub object guaranteed to be in order?

ie: if I define subscriptions like

```python
def myHandler1():
    ...

def myHandler2():
    ...

r = redis.StrictRedis()
p = r.pubsub()
p.subscribe(**{"myChannel": myHandler1, "myChannel": myHandler2})
```

When a publish to `myChannel` is made, are `myHandler1` and `myHandler2` guaranteed to be called in the order they appear in the dict literal?

**Comment by tselepakis** [comment]
Hi @AlexEshoo . This will probably call only one handler, because you assign them in the same dict key. A python dictionary have unique keys.

**Comment by AlexEshoo** [comment]
Woops, my mistake. Is there a way to register multiple call backs against a
single channel (without the use of a wrapper function that calls both)? If
so what would be the order of execution?

**Comment by tselepakis** [comment]
One simple solution would be to define one handler and call handler1 and
handler2 in there.

**Comment by andymccurdy** [comment]
The current design doesn't offer the ability to register more than one callback per channel. @tselepakis's solution is easy and I would suggest following that advice.

**Comment by AlexEshoo** [comment]
@andymccurdy Thanks, I will implement something similar to that then. You can close this now
