### ISSUE TITLE
Redis 5.0 with redis==3.2.0 doesn't update value sent by setex command

### ISSUE THREAD

**Issue by dusze** [andymccurdy/redis-py#1155]
**Version**: redis==3.2.0 & Redis 5.0.3

**Platform**: CentOS 7.5

**Description**: I have a key-value, stored in Redis, e.g. "key1" : "value1".
From Python 3.6 using python module "redis" I change this pair using setex command, e.g.

client.setex("key1", TTLvalue, "value2")

and always get OK from redis-server. 

But sometimes "key1" value isn't updated to "value2" and stay "value1".

Nothing special in any logs.

Ideas?

**Comment by andymccurdy** [comment]
Sorry for the late reply on this. Looks like you're calling SETEX correctly. I don't believe this is a redis-py error.

Perhaps another thread/process is updating the value back to "value1"?

**Comment by theodesp** [comment]
@dusze you could run a redis monitor command and verify that nothing else resets that value

**Comment by andymccurdy** [comment]
No reply in a month and I'm very confident this isn't a redis-py issue. Closing this issue. If you believe this to be a redis-py issue, please reopen with additional information.
