### ISSUE TITLE
Keyspace event notification is not sent

### ISSUE THREAD

**Issue by hiltja** [andymccurdy/redis-py#1157]
**Version**: 2.10.6
**Platform**: Linux/Python 2.7.14
**Description**: SETting keyword doesn't trigger keyspace event notification.

Example:
db = redis.StrictRedis(db=1,unix_socket_path="/tmp/redis.sock")
self.pubsub = db.pubsub()
self.pubsub.subscribe(**{'__keyspace@0__:FooBarValue':change_value_cb})
self.thread = self.pubsub.run_in_thread(sleep_time=1)

Above code works fine when FooBarValue is changed from Redis cli.
eg. set FooBarValue 255
And callback is triggered.

But if set is done using Redis py instance keyspace event is not sent and callback method is not called.
eg. db.set("FooBarValue,254)
Nothing happens.

**Comment by hiltja** [comment]
Reproducible with latest master (1.April 2019)

**Comment by andymccurdy** [comment]
From the snippet above, you're connecting the Python client to database 1 but listening for events on the "FooBarValue" key in database 0.

**Comment by hiltja** [comment]
Well, that pretty much explains all. Thanks. :)
