### ISSUE TITLE
[Redis 3.2.1] AttributeError: 'float' object has no attribute 'items'

### ISSUE THREAD

**Issue by sshnakamoto** [andymccurdy/redis-py#1158]
### Wasn't yet fixed in v3.2.1?

**Version**: 
pip 19.0.3  
redis==3.2.1
[Docker Official Image Redis version=5.0.4 
](https://github.com/docker-library/redis/blob/dcc0a2a343ce499b78ca617987e8621e7d31515b/5.0/Dockerfile)
**Platform**: 
Python 3.7.2 Virtualenv 
OSX High Sierra 10.13.4

PyCharm 2019.1.1 (Community Edition)
Build #PC-191.6605.12, built on April 3, 2019
JRE: 11.0.2+9-b159.34 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4

**Description**:
PyDev console: starting.
Python 3.7.2 (default, Feb 12 2019, 08:16:38) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
```python
import redis
db = redis.Redis()
db.zadd(name='foo', mapping=200, nx=True)

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/mimimi/PycharmProjects/foobar/venv/lib/python3.7/site-packages/redis/client.py", line 2320, in zadd
    for pair in iteritems(mapping):
  File "/Users/mimimi/PycharmProjects/foobar/venv/lib/python3.7/site-packages/redis/_compat.py", line 109, in iteritems
    return iter(x.items())
AttributeError: 'int' object has no attribute 'items'
```

**Comment by andymccurdy** [comment]
The `mapping` argument in the `ZADD` command must be a Python dictionary where the keys represent the element names in the sorted set and their values represent the score of each element name.

**Comment by sshnakamoto** [comment]
Thanks for clarify, you're right!
But that isn't clear neither in [Redis](https://redis.io/commands/zadd) nor [Redis-Py](https://redis-py.readthedocs.io/en/latest/#redis.Redis.zadd) documentation.

**Comment by andymccurdy** [comment]
What would make it more clear? The first line of the redis-py documentation says:

"Set any number of element-name, score pairs to the key name. Pairs are specified as a dict of element-names keys to score values."

**Comment by sshnakamoto** [comment]
I need check my eyes!
