### ISSUE TITLE
 Create key in _incr method with timeout

### ISSUE THREAD

**Issue by jadhavmanoj** [andymccurdy/redis-py#1163]
Currently, _incr function if key is not available then nothing is happen.

I feel incr_() should create key if not available and set expiry given in incr method.

In my use case I increment counter in async using celery & rabbitmq, in this scenario there is chances of losing data as key is not set if multiple process call same function at a time.

Can anyone help me how to fix this issue? or I will create PR for the same (Add key creation in incr() method).

**Comment by andymccurdy** [comment]
Could you provide a code example please? If a key doesn't exist in Redis `incr` will automatically create it and initialize it's value to zero.

**Comment by jadhavmanoj** [comment]
Yes. I see key is created but the custom timeout for that key not able to set. Is there a way to pass timeout while creating key?

**Comment by andymccurdy** [comment]
No, you have to issue a second command to expire the key. If the incr and expire need to be atomic, wrap the two calls in a pipeline or create a Lua script with the two calls together.

**Comment by jadhavmanoj** [comment]
Ohk. Got it.

Thanks for the help.
