### ISSUE TITLE
Import Error with non-admin ipython shell

### ISSUE THREAD

**Issue by nirvana1122** [andymccurdy/redis-py#1164]
**Version**: Redis-py version 3.2

**Platform**: Windows 10

Hi - I am getting an error when I try to import redis-py module. The error only happens when I do the import in an ipython shell running in a non-administrative command prompt on Windows 10. A command prompt running as an administrator doesn't give the import error.

C:\Users\john>ipython
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import redis
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-1fa5a3a95ebb> in <module>
----> 1 import redis

C:\Anaconda3\lib\site-packages\redis\__init__.py in <module>
----> 1 from redis.client import Redis, StrictRedis
      2 from redis.connection import (
      3     BlockingConnectionPool,
      4     ConnectionPool,
      5     Connection,

C:\Anaconda3\lib\site-packages\redis\client.py in <module>
     10 from redis._compat import (basestring, bytes, imap, iteritems, iterkeys,
     11                            itervalues, izip, long, nativestr, safe_unicode)
---> 12 from redis.connection import (ConnectionPool, UnixDomainSocketConnection,
     13                               SSLConnection, Token)
     14 from redis.lock import Lock

C:\Anaconda3\lib\site-packages\redis\connection.py in <module>
     36     import hiredis
     37
---> 38     hiredis_version = StrictVersion(hiredis.__version__)
     39     HIREDIS_SUPPORTS_CALLABLE_ERRORS = \
     40         hiredis_version >= StrictVersion('0.1.3')

AttributeError: module 'hiredis' has no attribute '__version__'

In [2]:

**Comment by andymccurdy** [comment]
It looks like you have hiredis-py installed but a well known attribute of the hiredis-py module is missing. How did you install hiredis-py?

You mentioned this happens on non-administrative shells. Does everything work fine when you run in an administrative shell? If so, perhaps you installed hiredis-py as an admin and for some reason it’s inaccessible to your non-privileged user.

**Comment by nirvana1122** [comment]
I looked at my installation and hiredis was missing. It started working in non-admin shell after hiredis was installed. 

I  used Anaconda/conda to install redis. I am not sure why it missed the hiredis, or why it worked in admin shell but not in non-admin without hiredis.
