### ISSUE TITLE
execute_command() and response callbacks

### ISSUE THREAD

**Issue by itamarhaber** [andymccurdy/redis-py#1168]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: all

**Platform**: all

**Description**: there is quirkiness in how the response from `execute_command` is handled, which is case- (pun intended) dependent. When calling `execute_command('info')`, the callback is skipped and the result is returned as a newline-separated string. Calling `execute_command('INFO')` returns it as a parsed dict. The same would possibly happen with any custom response callback.

That said, changing this (e.g. upper() on the command's name) would break existing code relying on this behavior.

Credit: @oranagra

**Comment by andymccurdy** [comment]
Is there ever a reason to using `client.execute_command('info')` over `client.info()`?

**Comment by oranagra** [comment]
yes, i think so.
in my case, the code that decide how / when / where to run the command is complicated, and i call it like `find_replica(tips).query(command_args)`.
or in fact: `info = find_replica(tips).query('info', 'memory')`

**Comment by andymccurdy** [comment]
I don't really know how common this is, but my guess is that most people use the client methods. However, I don't think it would impact many users if we changed the response callback lookup to be case insensitive. I'll work on a patch.

FYI: this will likely require any multi-word command name to be specified as a single string, just like the existing client methods. e.g., `.query('config get', ...)` instead of `.query('config', 'get', ...)`.

**Comment by oranagra** [comment]
I don't follow... 
we use `.query('config', 'get', ...)`
are you saying your fix will somehow affect this?

**Comment by andymccurdy** [comment]
The client assumes the first argument is the full command name. e.g.: https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L904

That command name is what's used to look up the appropriate response callback. 2-word commands are stored as a single string in the lookup dict.

**Comment by andymccurdy** [comment]
I started implementing this and realized there's a second issue. There's a handful of commands that pass extra parsing options to the response callbacks. For example, look at `ZRANGE`: https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L2413

The `withscores` and `score_cast_func` are extra options that be supplied to the `ZRANGE` function and are passed though to the callback function via keyword arguments. A user would have to pass these explicitly along with the command to get the same behavior as calling the `client.zrange()`.

**Comment by oranagra** [comment]
I suppose that if someone's using `execute_command` he can't expect to be able to pass these special (command specific) arguments.

IMHO the only thing to fix is the odd behavior that execute_command returns different value on uppercase vs lowercase.

**Comment by andymccurdy** [comment]
@oranagra Just pushed a branch with the case insensitive command names. Would you mind trying it out before I merge it?

**Comment by oranagra** [comment]
@andymccurdy basic feature of case insensitive `execute_command` obviously works fine.
I'm not sure if you intended for me to test for any regression, if so, i'm not able to do that at the moment. hope you have a good test coverage.

**Comment by andymccurdy** [comment]
Merged this into master.
