### ISSUE TITLE
the from_url(urlparse) does not parse the correct password

### ISSUE THREAD

**Issue by pingf** [andymccurdy/redis-py#1171]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**:  3.2 (redis-server 4.0.9)

**Platform**: What platform / version? (For example Python 3.7.3 on Ubuntu 18.04 / local)

**Description**: 
when I use the special chars as the password `!#$%^&*()[]`,  I can connect to the redis and ping with command `redis-cli -a '!@#$%^&*()[]'`

however when I use redis-py's  from_url, it does not work!

```python
password = '!#$%^&*()[]'
url = 'redis://:{}@localhost:6379/0'.format(password)
r=redis.from_url(url)
result = r.ping()
print(result)
```

maybe https://github.com/andymccurdy/redis-py/issues/799 is related

**Comment by andymccurdy** [comment]
A number of those characters aren't valid in URLs. You need to urlencode the password section. You can then tell `from_url()` to use urldecode with:

`redis.from_url('redis://:%21%23%24%25%5E%26%2A%28%29%5B%5D@localhost:6379/0')`

**Comment by pingf** [comment]
do we have one method that can auto parse this “invalid” url?
we have a system which let users input this url, 
if we use the above solution, we need to parse the password first, and then quote it and format it into the url, finally use from_url.
though it's an invalid url , but tools like sqlalchemy do provide way to connect to db directly.

**Comment by pingf** [comment]
and another thing is， one of our machine configure the password as `[1,%#@./-8`, 
if we use the code below, it doesn't work
```python
from urllib.parse import urlparse

import redis

import urllib
password = '[1,%#@./-8'
password = urllib.parse.quote(password, safe='/', encoding=None, errors=None)
url = 'redis://:{}@localhost:6379/0'.format(password)
print('url is {}'.format(url))
r=redis.from_url(url, decode_components=True)
r.set('hello', 'world')
result = r.get('hello')
print('result is {}'.format(result)
```

**Comment by andymccurdy** [comment]
It's not safe to allow "/" in the password section of a URL. The following code does what you want:

```python
from urllib.parse import quote
import redis

password = '[1,%#@./-8'
encoded_password = quote(password, safe="")
r = redis.from_url('redis://:{}@localhost:6379/0'.format(encoded_password), decode_components=True)
print(r.connection_pool.connection_kwargs)
```

**Comment by pingf** [comment]
Thx a lot!
