### ISSUE TITLE
sentinel requirepass

### ISSUE THREAD

**Issue by yushizhao** [andymccurdy/redis-py#1172]
As stated on https://redis.io/topics/sentinel:

You can also configure the Sentinel instance itself in order to require client authentication via the AUTH command, however this feature is only available starting with Redis 5.0.1.

In order to do so, just add the following configuration directive to all your Sentinel instances:

requirepass "your_password_here"

So, in order to interact with such a sentinel, how can we send the AUTH command to Sentinel instances using redis-py?

**Comment by andymccurdy** [comment]
You should be able to pass `sentinel_kwargs={'password': 'my-password'}` to the Sentinel object.

This does assume that all of you sentinels share the same password.

**Comment by yushizhao** [comment]
It works! Thank you very much. 
I am closing this issue.

**Comment by jgwinner** [comment]
The only example in the docs doesn't show this:

![image](https://user-images.githubusercontent.com/10425170/153142588-b6d535d7-538f-404b-ad12-6179f61e169c.png)

This REALLY needs to be in the docs. Should I open a separate doc bug?

Thanks, fantastic product!

== John ==
