### ISSUE TITLE
Working with RedisGraph

### ISSUE THREAD

**Issue by EdLeafe** [andymccurdy/redis-py#1176]
This is not an issue per se, but just a question. Is there support in redis-py for working with RedisGraph? I don't see any graph-specific methods, so how would I work with graph queries using redis-py?

P.S. as an SDK-developer, I totally understand if the answer is "you can't". ;-)

**Comment by andymccurdy** [comment]
At the moment, redis-py only supports standard Redis commands out of the box.

However, it's pretty easy to make it work with Redis modules too. One option would be to call `execute_command()` directly. Something like:

```python
r = redis.Redis(...)
r.execute_command('redis-graph-command', 'arg1', 'arg2', ...)
```

You can call `r.set_response_callback('redis-graph-command', my_callback)` to register a function that will parse the response of the command into whatever format you want.

You could also subclass the redis-py `Redis` class and add methods for each RedisGraph command and the appropriate callbacks.

**Comment by EdLeafe** [comment]
Thanks for the quick response! I've been working with Neo4j for a while, and when I found out about RedisGraph, I wanted to check that out. I'll try playing around with this.
