### ISSUE TITLE
UnicodeDecodeError: 'utf8' on Windows

### ISSUE THREAD

**Issue by alexsilva** [andymccurdy/redis-py#1181]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: What redis-py and what redis version is the issue happening on? `v3.2.1`

**Platform**: What platform / version?  `Windows 10 64bits`

**Description**: A connection failure does not display the error message correctly.
```
import redis
conn = redis.Redis(host='localhost', port=6379, db=0)
conn.set('key', 'value')

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "Python2.7\lib\site-packages\redis\client.py", line 1451, in set
    return self.execute_command('SET', *pieces)
  File "Python2.7\lib\site-packages\redis\client.py", line 772, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "Python2.7\lib\site-packages\redis\connection.py", line 994, in get_connection
    connection.connect()
  File "Python2.7\lib\site-packages\redis\connection.py", line 497, in connect
    raise ConnectionError(self._error_message(e))
  File "Python2.7\lib\site-packages\redis\connection.py", line 561, in _error_message
    (exception.args[0], self.host, self.port, exception.args[1])
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe3 in position 13: invalid continuation byte
``` 

Possible correction:
```
return "Error %s connecting to %s:%s. %s." % \
                (exception.args[0], self.host, self.port, exception.args[1].decode('utf8', 'ignore'))
```

The error message is a str object and therefore needs to be decoded in some way.

**Comment by Skymemory** [comment]
It seems socket.error raise (errno, string) and string not utf8 encode.

Try look at the value of  os.strerror(exception.args[0]) on your platform.

**Comment by alexsilva** [comment]
On a connection failure redis is raising the `UnicodeDecodeError` exception instead of `ConnectionError`. This generates a side effect that is denied when it is used with the `Celery` library because it waits for `ConnectionError`.

**Comment by alexsilva** [comment]
1 year and problem has not been solved. I give up.

**Comment by andymccurdy** [comment]
Sorry, I don't run on Windows and could never reproduce this. If you submit a test that shows the breaking behavior, we can likely fix it.
