### ISSUE TITLE
Redisgraph parameter insertion

### ISSUE THREAD

**Issue by LWprogramming** [andymccurdy/redis-py#1183]
I'm working with redisgraph and would like to insert parameters into my Cypher queries programmatically. Is there a way to do this? 

For instance, given the query
```cypher
MATCH (Foo:Bar)
WHERE Foo.name = $name
RETURN Foo
```
where `name` is a parameter, say `{'name': 'hello'}`, I'd like to write some python to execute this query by passing `name` as a parameter.

The [neo4j tutorial](https://neo4j.com/developer/python/) has an example of doing this programmatically.

```python
tx.run("CREATE (a:Greeting) "
    "SET a.message = $message "
    "RETURN a.message + ', from node ' + id(a)", message=message)
```
Here we have `message` being passed in as an argument.

Things that I tried that didn't work because it said that `x` is still not defined:

* Running this:
 
```python
import redis
r = redis.Redis(host=u'localhost', port=6379)
query = 'match(n) return $x'
r.execute_command('GRAPH.QUERY animals', query, x='hello')
```

* Attempting to set `x` by running `SET 'x' 'hello'`, and then running the python above but without the `x` named parameter.

* Using redisgraph-py but this sort of query parameter insertion doesn't seem to be an option there. 

* Reading the docs-- there's no mention of this anywhere. It doesn't say it's not supported either, there's just no mention whatsoever.

**Version**: redis-py- '3.2.1', redis: docker container version 1.2.2

**Platform**: Python 3.6.7 on Ubuntu 18.04

**Comment by andymccurdy** [comment]
redis-py doesn't support this inherently. But really all you're doing is string interpolation which Python can solve in many different ways.

You could define dict-style placeholders in your query, such as: `query = 'match(n) return %(x)s'`, and then execute it like: `r.execute_command('GRAPH.QUERY animals', query % {'x': 'hello'})`.

If you want something a little fancier, make your own wrapping function that accepts the redis client, the query, and **kwargs. The function would do the string interpolation with whichever Python syntax you prefer, call the client's `execute_command()` and return the result.

**Comment by LWprogramming** [comment]
I may have misphrased my original question-- we could interpolate the arguments into the string, but would prefer something along the lines of setting the parameter value in Redisgraph itself.

In other words, I'm looking for the equivalent of `:params name: 'hello'` in the [Neo4j browser](https://stackoverflow.com/a/42398794) so it's possible to run 
```cypher
MATCH (Foo:Bar)
WHERE Foo.name = $name
RETURN Foo
```
without replacing "$name" with "hello" in the query first.

That makes it more of a redisgraph than a redis-py question, but if you have any suggestions for that it would be greatly appreciated!

**Comment by andymccurdy** [comment]
I don't see any evidence that RedisGraph supports query placeholders here: https://oss.redislabs.com/redisgraph/commands/

From a very brief scan, it seems like the client must do any required string interpolation prior to sending the query to the server.

**Comment by LWprogramming** [comment]
Update for future reference: Redisgraph currently does not support this functionality but there are plans to support it at some point.

https://github.com/RedisGraph/RedisGraph/issues/544#issuecomment-507963576

Thanks for your help!
