### ISSUE TITLE
Why does ConnectionPool.get_connection() take a command name and additional arguments?

### ISSUE THREAD

**Issue by coleifer** [andymccurdy/redis-py#1190]
**Version**: 3.2.1

**Platform**: N/A

**Description**: I apologize that this is not a bug, per-se, but more a question.

I noticed that ConnectionPool.get_connection() has the signature:

```python
def get_connection(self, command_name, *keys, **options):
```

But none of these parameters seem to be used within the method itself. Is there a reason for this? If so, a comment might be helpful, as it struck me as very odd. Especially as in places in `client` it appears to be attempting to use these parameters.

Thanks!

**Comment by andymccurdy** [comment]
Hi, sorry for not commenting sooner. `command_name` and `keys` was originally intended to provide information to move advanced `ConnectionPool` implementations. For instance, you would probably want both of these things if you were making a client-side sharded `ConnectionPool`.

**Comment by coleifer** [comment]
Cool thanks that's kinda what I figured, but wasn't sure if it was vestigial or just future-proofing.
