### ISSUE TITLE
import redis slow on FreeBSD / Python3.6 / related to uuid

### ISSUE THREAD

**Issue by Brampie66** [andymccurdy/redis-py#1193]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: 3.2.1, 2.10 ?

**Platform**: Freebsd, python 3.6.7

**Description**: import redis takes 6 seconds on python3.6, this is because import uuid takes this long.
With the uuid.py file from python3.7 importing goes faster but generating the first uuid1() takes long, uuid4() goes a lot faster.
I found this example, https://redislabs.com/ebook/part-2-core-concepts/chapter-6-application-components-in-redis/6-2-distributed-locking/6-2-3-building-a-lock-in-redis/
this uses uuid4(), is it of any importance that it is uuid1 ?

**Comment by adamantike** [comment]
Related CPython pull request, which wasn't back-ported to 3.6: python/cpython#3796

**Comment by andymccurdy** [comment]
This seems like a bug in the FreeBSD Python 3.6 implementation so there's not a lot we can do here.

There's no reason that `uuid1` must be used -- any unique token will work. We could easily add a hook to make it easy to swap out the usage of `uuid1` for something else.
