### ISSUE TITLE
Cannot seem to get values from remote machine

### ISSUE THREAD

**Issue by Neuroforge** [andymccurdy/redis-py#1198]
**Version**: What redis-py and what redis version is the issue happening on?
3.3.4

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
Windows 10 Python 3.7
MacOS Redis  5.0.4

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

I have a Macbook running 'redis-server --protected-mode no'.
Using redis-py on my Windows machine, i can connect, store data and retireve data using the Redis server running on the mac. This data can be stored and retrieved by the Windows machine.

However, using the redis-cli on the Macbook, i am unable to see the keys added by the Windows client. 

1) Add a value to redis with key "321" on the client.
2) Add a value to redis with the key "ABC" on the cli, on the same machine as redis server.
3) Try and get the two clients to both see the same keys and fetch the data.

```
import redis
db = redis.Redis("XXXXXXXX",6379,0)
db.set("321","A Value")
r = db.get("321")
print(r)
```
Redis Cli Commands.
```
127.0.0.1:6379> SET "ABC" "Another value"
127.0.0.1:6379> KEYS *
1) "ABC"
127.0.0.1:6379> 
```
The host, port and db value are the same for both the cli and Windows python client.

Regards,

**Comment by andymccurdy** [comment]
I’d double check your host/port/db settings. Perhaps you have two servers running on the Mac where one is bound to the loopback interface and the other to your network IP?

You could run the MONITOR command within the redis-cli client and see if it shows the commands that the python client is executing. If not, that’s a very good indication that you’re connecting to different servers.

**Comment by Neuroforge** [comment]
Yup. MONITOR is not showing anything when the Windows client sends data. 

Thank you for pointing me in the right direction.
