### ISSUE TITLE
No new clients created while using connection pooling

### ISSUE THREAD

**Issue by mjmanav4** [andymccurdy/redis-py#1204]
So i am running my redis server on port 3001
and my python script initiates redis cli connection as the following
` redis_pool = redis.ConnectionPool(port=port, db=0) `
  ` r = redis.Redis(connection_pool=redis_pool,socket_keepalive=True,max_connections=100)`

while checking cli `info` from after logging in to `redis-cli -p 3001`
i see 

# Clients
connected_clients:2
client_recent_max_input_buffer:2
client_recent_max_output_buffer:0
blocked_clients:0

Here only two clients are available, one is form my terminal and other one from script

Why isn't it using 100 clients ??

**Comment by andymccurdy** [comment]
As @richjrader said, connections are only created when an already-connected connection isn't available.
