### ISSUE TITLE
Cluster Support?

### ISSUE THREAD

**Issue by sazima** [andymccurdy/redis-py#1209]

**Comment by andymccurdy** [comment]
You can use https://github.com/Grokzen/redis-py-cluster for cluster support

**Comment by rokcarl** [comment]
Are there plans for this repo to support Redis Cluster?

**Comment by andymccurdy** [comment]
Perhaps, but I don't have a timeline.

**Comment by rokcarl** [comment]
Fair enough. Thank you.
