### ISSUE TITLE
blpop with timeout=0 get stuck after a long idle time

### ISSUE THREAD

**Issue by captainst** [andymccurdy/redis-py#1210]
I am using redis server v3.2.100 on windows, and redis-py v3.3.8 from both windows and ubuntu 18.04.

I got a similar problem described here: https://github.com/andymccurdy/redis-py/issues/1199

I made the redis server public on internet, and use the redis-py to blpop the elements and process.

The redis-py code I used is like:

```
#import redis
db = redis.StrictRedis(host='xx.xx.xx.xx', port=6379, db=0)
while True:
queue = db.blpop('detection_queue', timeout=5)
if queue is not None:
    # process the queue
```

If I leave the redis queue empty, then after a long time **t**, the blpop seems to get stuck. It does not return even I push new elements into the queue.
If I specify timeout=0 in db.blpop (no timeout, wait indefinitely) call, then the **t** is about 30 minutes
If I specify timeout=5 in db.blpop (5 seconds timeout), then the **t** is around a couple of hours.

I could share the redis IP and port, if anybody is interested to make a test.

Thanks.

**Comment by andymccurdy** [comment]
Sounds like something between the client and server is stalling the connection. You can add the `socket_timeout=X` option when constructing the client instance. If the client waits longer than `socket_timeout` seconds a `TimeoutError` exception is raised.

**Comment by captainst** [comment]
@andymccurdy Many thanks. I also saw your reply in this issue: https://github.com/andymccurdy/redis-py/issues/1210#issuecomment-526804585

I'll add both socket_timeout and socket_keepalive to check if any difference occur.

**Comment by andymccurdy** [comment]
Just make sure your `socket_timeout` is higher than the timeout you're passing to `BLPOP`.

**Comment by captainst** [comment]
@andymccurdy Got it. Thanks again. Up to now I made a "rustic" test: Feed the queue with some element every hour. From earlier this morning till now, the client is still responding.
So it seems that it is the a network keep-alive related issue.

**Comment by captainst** [comment]
@andymccurdy For the moment I managed to keep the connection running for at least 8 hours in idle.
I used the following code:
```
db = redis.StrictRedis(host='xx.xx.xx.xx', port=6379, db=0, socket_keepalive=True, socket_timeout=300)
while True:
  try:
    queue = db.blpop('detection_queue', timeout=60)
  except Exception as err:
    print(err)
  if queue is not None:
    # do some stuff here
```
Many thanks to you and I think that the problem could be considered as "closed"

**Comment by kingname** [comment]
thanks for your issue, also solved my problem.
