### ISSUE TITLE
hello，What causes redis to have too many idle connections

### ISSUE THREAD

**Issue by pyh007** [andymccurdy/redis-py#1212]
I used celery to processing tasks, the task of redis connection, when running after a period of time, will quote us was forced to shut down a remote connection error, I view the Windows port usage, found that there are a lot of TCP connections, I doubt is free connection too much.What do you think

**Comment by andymccurdy** [comment]
Celery uses multiple connections to Redis so that tasks can be consumed in parallel. If you have more questions about how Celery uses redis-py, I would suggest posting on the Celery or Kombu issues list.
