### ISSUE TITLE
Setting up redistogo in Heroku

### ISSUE THREAD

**Issue by deloquito** [andymccurdy/redis-py#1213]
i am developing a flask webapp with sessions and i want to develop it in heroku. I want to store the sessions in redistogo bacause Heroku often forgets sessions as its filesystem is ephimeral. I am a bit lost setting redistogo in Heroku, i installed the plugin and followed the steps but it throws 2 errors in logs (this 2 errors are given in heroku logs, in localhost everything works fine): 
1st
`2019-09-07T02:15:56.714758+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py", line 583, in _connect
2019-09-07T02:15:56.714760+00:00 app[web.1]:     sock.connect(socket_address)
2019-09-07T02:15:56.714762+00:00 app[web.1]: ConnectionRefusedError: [Errno 111] Connection refused
2019-09-07T02:15:56.714764+00:00 app[web.1]: 
2019-09-07T02:15:56.714766+00:00 app[web.1]: During handling of the above exception, another exception occurred:`
2d:
`2019-09-06T21:26:19.779199+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py", line 543, in connect
2019-09-06T21:26:19.779201+00:00 app[web.1]:     raise ConnectionError(self._error_message(e))
2019-09-06T21:26:19.779208+00:00 app[web.1]: redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.`

As i want to test my app in localhost i also dowloaded redis locally but i dont know if it is a good idea to have redis locally and redistogo in heroku as some variables might get mixed up. I am almost certain that my error is because of that, i must have mixed or missed something but i cant figure it out. Here is my code:
`from redissession import RedisSessionInterface
import redis

app = Flask(__name__)

login_manager = LoginManager()

login_manager.login_view = "login"
login_manager.init_app(app)

app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY')
redis_url = os.getenv('REDISTOGO_URL', 'redis://localhost:6379')
redis = redis.from_url(redis_url)

app.config["SESSION_FILE_DIR"] = mkdtemp()
app.config["SESSION_PERMANENT"] = False
app.config["SESSION_TYPE"] = 'redis'
#app.config["SESSION_TYPE"] = "filesystem"
Session(app)
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SQLALCHEMY_DATABASE_URI'] = os.environ['DATABASE_URL']`
Just to clarify, the environment variable 'REDISTOGO_URL' is properly setted in heroku Edit: Trying to narrow down the problem i adde a print statement to print the 'redis_url' variable. when i am in localhost it prints 'redis://localhost:6379'

and when on heroku it prints 'redis://redistogo:7d43a0c94e09a7d3701f86e16e6602dc@pearlfish.redistogo.com:9873/' So the variables are setted correctly.

Then here is my login section with the sessions:

`@app.route("/login", methods=["GET", "POST"])
def login():
    """Log user in"""

    # Forget any user_id
    session.clear()

    # User reached route via POST (as by submitting a form via POST)
    if request.method == "POST":
        username=request.form.get("username").upper()

        # Ensure username was submitted
        if not request.form.get("username"):
            return apology("Debe ingresar un nombre de usuario.", 403)

        # Ensure password was submitted
        elif not request.form.get("password"):
            return apology("Debe ingresar una contraseña.", 403)

        if rows is None or not check_password_hash(rows.hash, request.form.get("password")):
            return apology("Usuario o contraseña incorrectos", 403)

        else:
            session["nombrescuela"] = rows.nombrescuela
            login_user(rows)
            flash("Sesión Iniciada!")
            return redirect(url_for('index'))

        # Redirect user to home page

    # User reached route via GET (as by clicking a link or via redirect)
    else:
        return render_template("login.html")

@app.route("/logout")
def logout():
    """Log user out"""

    # Forget any user_id

    session.clear()
    logout_user()
    # Redirect user to login form
    return redirect(url_for('index'))`

Any clues? thanks

**Comment by andymccurdy** [comment]
The `ConnectionRefused` error indicates that a tcp connection could not be established between the client and server.

Generally this means either that the redis server isn’t running or that you have the wrong connection information.

I would try attempting to connect to the RedisToGo instance from your local development environment to make sure your connection string works. If it does then either you’re not using the same connection string in heroku or something in the heroku env is preventing outbound connections.

If the RedisToGo connection string does not work in your dev environment make sure the server is actually running and make sure you copied the connection string correctly.

**Comment by andymccurdy** [comment]
This doesn't seem to be an issue with redis-py. If you have more information to report feel free to reopen.
