### ISSUE TITLE
Can't pass a bytearray to SET

### ISSUE THREAD

**Issue by red-lithium** [andymccurdy/redis-py#1214]
**Version**: redis-py 3.3.8 and redis 5.0.5

**Platform**: Python 3.6.8 on Ubuntu 18.04

**Description**: Redis strings are should be binary safe, but `redis.set(key, value)` doesn't accept a bytearray as a valid type. Passing a bytearray in as a value, results in the following exception:
`Invalid input of type: 'bytearray'. Convert to a byte, string or number first.`

I understand that this might be a limitation of Python or perhaps I've misunderstood the [Redis documentation](https://redis.io/topics/data-types). Thanks in advance.

Example code:
```python
#!/usr/bin/python3
import redis

redis = redis.Redis(host="localhost", port=6379, db=0)

# This will result in an exception
redis.set("my-key", bytearray(10))
```

**Comment by andymccurdy** [comment]
Improved the error message to be more obvious.

**Comment by earonesty** [comment]
fyi, for certain workflows, using a bytearray directly can be significantly more performant for high-speed ops.   all c++ functions and mypy, etc should automatically promote.   i think it's easy to support
