### ISSUE TITLE
redis.StrictRedis.lock release doesn't actually check redis

### ISSUE THREAD

**Issue by yshaban** [andymccurdy/redis-py#1221]
**Version**: What redis-py and what redis version is the issue happening on?
redis-py==3.3.8
redis==3.2.8

Python 3.5.1

**Description**: 
I can create a redis.StrictRedis.lock object, check that its locked. If it is locked, I will try to release it. Releasing it throws a redis.exceptions.LockError saying that the lock cannot be released as it is already unlocked. This is in fact not true. I can verify it by using redis-cli and inspecting the lock. The lock is still in use.

```
if queue_lock.locked():
            try:
                queue_lock.release()
            except redis.exceptions.LockError as le:
                # received error, lock is already unlocked
                # this is not true, we know the lock is actually locked
                print("Received lock error: {0}.".format(str(le)))
                sys.stdout.flush()
                # Delete the lock
                print("Deleting lock....{0}".format(queue_lock.name))
                sys.stdout.flush()
                r.delete(queue_lock.name)
                print("{0} deleted".format(queue_lock.name))
                sys.stdout.flush()```

**Comment by yshaban** [comment]
I can tell the issue is because you are checking the self.local.token.
I can solve the issue by catching the redis.exceptions.LockError exception and then deleting the lock from Redis.

**Comment by andymccurdy** [comment]
If the token on the server doesn't match the token that Client A's lock has then Client A can not release the lock.

Such a case could happen if the Client A's lock was expired and Client B then acquired the lock with its own token.

**Comment by yshaban** [comment]
This is happening on a restart of a service. So service is started, acquires lock, service is restarted and the lock was not released. On restart we release the locks, for this exact reason because the lock could still be acquired by a process that no longer exists, but we are unable to release the lock because the implemented method only checks self.local.token.

**Comment by andymccurdy** [comment]
Ah I see. It sounds like you need to figure out how to restart your service gracefully in such a way where the lock is cleanly released and any other resources the service is using are cleaned up appropriately.

You could try using the lock as a context manager. Depending on how the service restarts that might help. For example:

```python
with redis_client.lock(..):
    # do stuff while the lock is acquired...
```

**Comment by yshaban** [comment]
We are using a context manager. I'll see what I can do on releasing it gracefully on shutdown.
