### ISSUE TITLE
[3.3.11] some test fails

### ISSUE THREAD

**Issue by tuxmaster5000** [andymccurdy/redis-py#1226]
Environment: CentOS 7.7, Python 3.6, Redis 3.2.12 
Here the log:
 cd /builddir/build/BUILD
+ cd redis-3.3.11
+ /usr/bin/python3 setup.py test
+ redis-server
149:C 17 Oct 14:03:50.560 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
149:M 17 Oct 14:03:50.561 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
149:M 17 Oct 14:03:50.561 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
149:M 17 Oct 14:03:50.561 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 3.2.12 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                   
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 149
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           http://redis.io        
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

149:M 17 Oct 14:03:50.562 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
149:M 17 Oct 14:03:50.562 # Server started, Redis version 3.2.12
149:M 17 Oct 14:03:50.562 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
149:M 17 Oct 14:03:50.562 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
149:M 17 Oct 14:03:50.562 * The server is now ready to accept connections on port 6379
running test
running egg_info
writing redis.egg-info/PKG-INFO
writing dependency_links to redis.egg-info/dependency_links.txt
writing requirements to redis.egg-info/requires.txt
writing top-level names to redis.egg-info/top_level.txt
reading manifest file 'redis.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching '__pycache__'
warning: no previously-included files matching '*.pyc' found under directory 'tests'
writing manifest file 'redis.egg-info/SOURCES.txt'
running build_ext
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
rootdir: /builddir/build/BUILD/redis-3.3.11
plugins: cov-2.7.1, hypothesis-3.12.0
collected 437 items

tests/test_commands.py ....sss...................................ss..... [ 11%]
........................................................................ [ 27%]
...........................ssss......................................... [ 44%]
..................................s..........ssssssssssssssssssss.s..... [ 60%]
                                                                         [ 60%]
tests/test_connection_pool.py .......................................... [ 70%]
...............                                                          [ 73%]
tests/test_encoding.py ........                                          [ 75%]
tests/test_lock.py ........................                              [ 81%]
tests/test_monitor.py FFFFF                                              [ 82%]
tests/test_multiprocessing.py .........                                  [ 84%]
tests/test_pipeline.py .................                                 [ 88%]
tests/test_pubsub.py .................................                   [ 95%]
tests/test_scripting.py .......                                          [ 97%]
tests/test_sentinel.py ............                                      [100%]

=================================== FAILURES ===================================
___________________ TestPipeline.test_wait_command_not_found ___________________

self = <tests.test_monitor.TestPipeline object at 0x7fe27ec65f60>
r = Redis<ConnectionPool<Connection<host=localhost,port=6379,db=9>>>

    def test_wait_command_not_found(self, r):
        "Make sure the wait_for_command func works when command is not found"
        with r.monitor() as m:
>           response = wait_for_command(r, m, 'nothing')

tests/test_monitor.py:23: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_monitor.py:9: in wait_for_command
    key = '__REDIS-PY-%s__' % str(client.client_id())
redis/client.py:934: in client_id
    return self.execute_command('CLIENT ID')
redis/client.py:839: in execute_command
    return self.parse_response(conn, command_name, **options)
redis/client.py:853: in parse_response
    response = connection.read_response()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = Connection<host=localhost,port=6379,db=9>

    def read_response(self):
        "Read the response from a previously sent command"
        try:
            response = self._parser.read_response()
        except socket.timeout:
            self.disconnect()
            raise TimeoutError("Timeout reading from %s:%s" %
                               (self.host, self.port))
        except socket.error:
            self.disconnect()
            e = sys.exc_info()[1]
            raise ConnectionError("Error while reading from %s:%s : %s" %
                                  (self.host, self.port, e.args))
        except:  # noqa: E722
            self.disconnect()
            raise
    
        if self.health_check_interval:
            self.next_health_check = time() + self.health_check_interval
    
        if isinstance(response, ResponseError):
>           raise response
E           redis.exceptions.ResponseError: Syntax error, try CLIENT (LIST | KILL | GETNAME | SETNAME | PAUSE | REPLY)

redis/connection.py:718: ResponseError
______________________ TestPipeline.test_response_values _______________________

self = <tests.test_monitor.TestPipeline object at 0x7fe27ec69c50>
r = Redis<ConnectionPool<Connection<host=localhost,port=6379,db=9>>>

    def test_response_values(self, r):
        with r.monitor() as m:
            r.ping()
>           response = wait_for_command(r, m, 'PING')

tests/test_monitor.py:29: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_monitor.py:9: in wait_for_command
    key = '__REDIS-PY-%s__' % str(client.client_id())
redis/client.py:934: in client_id
    return self.execute_command('CLIENT ID')
redis/client.py:839: in execute_command
    return self.parse_response(conn, command_name, **options)
redis/client.py:853: in parse_response
    response = connection.read_response()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = Connection<host=localhost,port=6379,db=9>

    def read_response(self):
        "Read the response from a previously sent command"
        try:
            response = self._parser.read_response()
        except socket.timeout:
            self.disconnect()
            raise TimeoutError("Timeout reading from %s:%s" %
                               (self.host, self.port))
        except socket.error:
            self.disconnect()
            e = sys.exc_info()[1]
            raise ConnectionError("Error while reading from %s:%s : %s" %
                                  (self.host, self.port, e.args))
        except:  # noqa: E722
            self.disconnect()
            raise
    
        if self.health_check_interval:
            self.next_health_check = time() + self.health_check_interval
    
        if isinstance(response, ResponseError):
>           raise response
E           redis.exceptions.ResponseError: Syntax error, try CLIENT (LIST | KILL | GETNAME | SETNAME | PAUSE | REPLY)

redis/connection.py:718: ResponseError
__________________ TestPipeline.test_command_with_quoted_key ___________________

self = <tests.test_monitor.TestPipeline object at 0x7fe27ec536a0>
r = Redis<ConnectionPool<Connection<host=localhost,port=6379,db=9>>>

    def test_command_with_quoted_key(self, r):
        with r.monitor() as m:
            r.get('foo"bar')
>           response = wait_for_command(r, m, 'GET foo"bar')

tests/test_monitor.py:40: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_monitor.py:9: in wait_for_command
    key = '__REDIS-PY-%s__' % str(client.client_id())
redis/client.py:934: in client_id
    return self.execute_command('CLIENT ID')
redis/client.py:839: in execute_command
    return self.parse_response(conn, command_name, **options)
redis/client.py:853: in parse_response
    response = connection.read_response()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = Connection<host=localhost,port=6379,db=9>

    def read_response(self):
        "Read the response from a previously sent command"
        try:
            response = self._parser.read_response()
        except socket.timeout:
            self.disconnect()
            raise TimeoutError("Timeout reading from %s:%s" %
                               (self.host, self.port))
        except socket.error:
            self.disconnect()
            e = sys.exc_info()[1]
            raise ConnectionError("Error while reading from %s:%s : %s" %
                                  (self.host, self.port, e.args))
        except:  # noqa: E722
            self.disconnect()
            raise
    
        if self.health_check_interval:
            self.next_health_check = time() + self.health_check_interval
    
        if isinstance(response, ResponseError):
>           raise response
E           redis.exceptions.ResponseError: Syntax error, try CLIENT (LIST | KILL | GETNAME | SETNAME | PAUSE | REPLY)

redis/connection.py:718: ResponseError
__________________ TestPipeline.test_command_with_binary_data __________________

self = <tests.test_monitor.TestPipeline object at 0x7fe27f9f55c0>
r = Redis<ConnectionPool<Connection<host=localhost,port=6379,db=9>>>

    def test_command_with_binary_data(self, r):
        with r.monitor() as m:
            byte_string = b'foo\x92'
            r.get(byte_string)
>           response = wait_for_command(r, m, 'GET foo\\x92')

tests/test_monitor.py:47: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_monitor.py:9: in wait_for_command
    key = '__REDIS-PY-%s__' % str(client.client_id())
redis/client.py:934: in client_id
    return self.execute_command('CLIENT ID')
redis/client.py:839: in execute_command
    return self.parse_response(conn, command_name, **options)
redis/client.py:853: in parse_response
    response = connection.read_response()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = Connection<host=localhost,port=6379,db=9>

    def read_response(self):
        "Read the response from a previously sent command"
        try:
            response = self._parser.read_response()
        except socket.timeout:
            self.disconnect()
            raise TimeoutError("Timeout reading from %s:%s" %
                               (self.host, self.port))
        except socket.error:
            self.disconnect()
            e = sys.exc_info()[1]
            raise ConnectionError("Error while reading from %s:%s : %s" %
                                  (self.host, self.port, e.args))
        except:  # noqa: E722
            self.disconnect()
            raise
    
        if self.health_check_interval:
            self.next_health_check = time() + self.health_check_interval
    
        if isinstance(response, ResponseError):
>           raise response
E           redis.exceptions.ResponseError: Syntax error, try CLIENT (LIST | KILL | GETNAME | SETNAME | PAUSE | REPLY)

redis/connection.py:718: ResponseError
_________________________ TestPipeline.test_lua_script _________________________

self = <tests.test_monitor.TestPipeline object at 0x7fe27ec74160>
r = Redis<ConnectionPool<Connection<host=localhost,port=6379,db=9>>>

    def test_lua_script(self, r):
        with r.monitor() as m:
            script = 'return redis.call("GET", "foo")'
            assert r.eval(script, 0) is None
>           response = wait_for_command(r, m, 'GET foo')

tests/test_monitor.py:54: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_monitor.py:9: in wait_for_command
    key = '__REDIS-PY-%s__' % str(client.client_id())
redis/client.py:934: in client_id
    return self.execute_command('CLIENT ID')
redis/client.py:839: in execute_command
    return self.parse_response(conn, command_name, **options)
redis/client.py:853: in parse_response
    response = connection.read_response()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = Connection<host=localhost,port=6379,db=9>

    def read_response(self):
        "Read the response from a previously sent command"
        try:
            response = self._parser.read_response()
        except socket.timeout:
            self.disconnect()
            raise TimeoutError("Timeout reading from %s:%s" %
                               (self.host, self.port))
        except socket.error:
            self.disconnect()
            e = sys.exc_info()[1]
            raise ConnectionError("Error while reading from %s:%s : %s" %
                                  (self.host, self.port, e.args))
        except:  # noqa: E722
            self.disconnect()
            raise
    
        if self.health_check_interval:
            self.next_health_check = time() + self.health_check_interval
    
        if isinstance(response, ResponseError):
>           raise response
E           redis.exceptions.ResponseError: Syntax error, try CLIENT (LIST | KILL | GETNAME | SETNAME | PAUSE | REPLY)

redis/connection.py:718: ResponseError
=============== 5 failed, 401 passed, 31 skipped in 9.13 seconds ===============

**Comment by andymccurdy** [comment]
I suspect that these failures are from commands that your version of Redis server doesn't have. Feel free to put some `@skip_if_server_version_lt` decorators in a pull request.

**Comment by tuxmaster5000** [comment]
Testing with 5.0 all tests are passed.
Only one test is skipped.

**Comment by andymccurdy** [comment]
PR Merged. Thanks!
