### ISSUE TITLE
Connections is CLOSE_WAIT state

### ISSUE THREAD

**Issue by aasifalam** [andymccurdy/redis-py#1235]
redis-py-cluster = 1.3.6
server = 4.0.14
redis = 2.10.6
Ubuntu (Kubernetes POD)

we are seeing many connection at the application in CLOSE_WAIT state. So many that application pod runs of all the file descriptors. Restart is the only option.
At the Redis server there are no dangling connection to the clients however. We are seeing this issue with multiple application clients.

**Comment by andymccurdy** [comment]
What were of redis-py?

**Comment by aasifalam** [comment]
2.10.6

**Comment by andymccurdy** [comment]
I would suggest upgrading to the latest 3.3.x. I believe this has been fixed.

**Comment by aasifalam** [comment]
Hi Andy

I was trying with latest redis-py (3.3.8), however i don't seems to get getting the compatible redis-py-cluster version for it.
The latest redis-py-cluster  version 2.0.0 has requirement of "redis>=3.0.0,<3.1.0"

How should i move to redis-py 3.3.x ?

Asif

**Comment by andymccurdy** [comment]
I don't know why redis-py-cluster doesn't like redis-py > 3.1.0. I would suggest asking @grokzen.

**Comment by inewlife** [comment]
I also encountered this problem, is there any solution

**Comment by RoeyPrat** [comment]
looks like [redis-py-cluster](https://github.com/grokzen/redis-py-cluster) now supports all v3 versions of redis-py.
https://github.com/Grokzen/redis-py-cluster/commit/0d6dc5ed10ca77784142c8eda8252f8005058b4d
please try updating to the latest redis-py v3. I'm closing this issue, but feel free to re-open or open a new one if the issue re-occurs in redis-py >= v3.5.3
