### ISSUE TITLE
Disable transactions for pipeline

### ISSUE THREAD

**Issue by corydolphin** [andymccurdy/redis-py#1236]
Hello,

The default behavior of `client.pipeline` is to execute the pipeline in a transaction. In our use case, we use redis-py behind an Envoy proxy, which disallows transactions (it presents itself as a non-clustered redis server, but proxies to both cluster and non clustered redis). 
We need to disable transactions in pipelines by default, while we can code-mod a change to all callers of pipeline, I am wondering if you have advice for a better approach?

Would you accept a patch which adds another parameter to client.init, a `pipelines_transactional_by_default` which would control the default behavior of pipelines. 
For backwards compatibility, this config would be true, and the default argument for `pipeline` would be updated to `None`.

**Comment by andymccurdy** [comment]
Can you not just pass `transaction=False` when instantiating a pipeline object?

**Comment by corydolphin** [comment]
> Can you not just pass `transaction=False` when instantiating a pipeline object?

We can, but it is error-prone, as it is so easy to have a caller make a mistake, and allow the defaults. 
We were honestly surprised to learn that a pipeline is executed in a transaction by default, since those are orthogonal features. 
Essentially what we want is either a configurable default, or a more explicit API around pipeline transactions.

**Comment by andymccurdy** [comment]
I guess my initial thought then is that you could easily subclass `redis.Redis` and override the `pipeline()` method to make pipelines non-transactional by default. That seems trivial with only a few lines of code.
