### ISSUE TITLE
[Redis 6] RESP 3 will be GA, plans to support the new protocol?

### ISSUE THREAD

**Issue by AngusP** [andymccurdy/redis-py#1246]
Redis' underlying protocol, RESP is getting an overhaul in Redis 6 - [RESP3](https://github.com/antirez/RESP3)

The new protocol is opt-in, so this and other clients will still work with RESP2 on all recent versions of Redis and Redis 6, however the new protocol includes new return types (maps, sets, explicit error strings, booleans, attributes, streamed-strings, etc.), with the aim of making it easier for clients to return sensible native data types to the user when calling commands they don't have a custom parser for, such as any [Module](https://redis.io/modules) commands, or future types added to Redis.

Hopefully this will be great for the user, but unfortunately this will require a fair bit of implementation effort for all the client libraries, unless new ones that only support RESP3 are written. Also note that there's a tree for dependencies, such as [redis-py-cluster](https://github.com/Grokzen/redis-py-cluster) depending on  support appearing here first.

So I'm wondering what a realistic plan for adding support would look like - who has availability, and how RESP2 vs RESP3 should be designed-in. Of course I'm happy to contribute where I can, but probably can't do the whole thing in a reasonable time-period

**Comment by andymccurdy** [comment]
I would very much like to support RESP3 in redis-py, but I agree that there's a fair bit of effort to make that work. Most notably is making sure to keep the return types in sync between the RESP2 and RESP3 implementations.

I hope many commands will have an identical RESP3 response structure to what redis-py is already returning. However I have to assume that some of the commands will differ. These commands will add complexity we'll need response callbacks for both RESP2 and RESP3 to keep both in sync.

I think the first step is to go through every command and and compare the response types of redis-py + RESP2 to the command's native RESP3 response type. This will give us an idea of how much work it will be to sync these up.

**Comment by AngusP** [comment]
That makes a lot of sense as a place to start - and would also be useful to all the other client implementers to have a list of command -> response type in RESP3 to check against. I'm not sure where would be best to put such a list, my guess would be in [redis-doc](https://github.com/antirez/redis-doc) (cc @itamarhaber ), otherwise in [RESP3](https://github.com/antirez/RESP3)

**Comment by Harrison88** [comment]
If it helps any, I've been working on a RESP3 implementation [here](https://github.com/Harrison88/respy3).

You may also be interested in the (currently incomplete) list of commands with their RESP3 responses I'm making for the tests: https://github.com/Harrison88/respy3/blob/main/tests/redis_commands.py

**Comment by judahrand** [comment]
Has any of this changed in the meantime?

**Comment by judahrand** [comment]
@chayim Perhaps you have some insight?
