### ISSUE TITLE
where did you reduced the value of _created_connections

### ISSUE THREAD

**Issue by wuxie2015** [andymccurdy/redis-py#1247]
https://github.com/andymccurdy/redis-py/blob/656b551eb247c491976646092a71320407c0fa03/redis/connection.py#L1112

`def make_connection(self):
        "Create a new connection"
        if self._created_connections >= self.max_connections:
            raise ConnectionError("Too many connections")
        self._created_connections += 1
        return self.connection_class(**self.connection_kwargs)

    def release(self, connection):
        "Releases the connection back to the pool"
        self._checkpid()
        if connection.pid != self.pid:
            return
        self._in_use_connections.remove(connection)
        self._available_connections.append(connection)`
since you increased the value of self._created_connections but didn't reduce it in self.release(connection) , also I didn't see its value has been reduced in anywhre ,where did you reduced the value of _created_connections?  if you hadn't reduced the value of self._created_connections,how did you make sure that method make_connection run without exception?

**Comment by andymccurdy** [comment]
Created connections are never destroyed. `release()` just returns the connection to the pool so that it can be reused. Therefore `_created_connections` never gets decremented.
