### ISSUE TITLE
Exception Catching 

### ISSUE THREAD

**Issue by the-c0d3r** [andymccurdy/redis-py#1248]
**Version**: 3.3.11

**Description**: `catching classes that do not inherit from BaseException is not allowed`

**Sample code**

```python
try:
    r = redis.Redis(...)
except redis.exceptions as error:
    print("Operation failed due to error: ", error)
```

This way of catching exceptions return an exception from python complaining the aforementioned exception message. I know that one can catch it as a broad `Exception` and check the erorr type, but that is a very broad exception. Is there any way to catch all the exceptions under `redis.exceptions`? I think this can be resolved if the `exceptions` in `redis/exceptions.py` are inheriting from `BaseException` class. 

Please let me know your thoughts on this, how to catch all the redis exceptions. I can put up a PR if my solution is deemed to be correct.

**Comment by andymccurdy** [comment]
`redis.exceptions` is a module, not an iterable of possible exceptions that redis-py raises. I believe what you're looking for is the `RedisError` exception, which is the base class for all of redis-py's exceptions. See here:

https://github.com/andymccurdy/redis-py/blob/master/redis/exceptions.py#L4

**Comment by the-c0d3r** [comment]
Sorry, I should have looked more thoroughly before opening the issue. Your suggestion works.
