### ISSUE TITLE
[Question] redis.exceptions.ConnectionError: Error while reading from socket: (54, 'Connection reset by peer')

### ISSUE THREAD

**Issue by tony-is-coding** [andymccurdy/redis-py#1250]
hi, i need help, it was suddenly happend to my program that was never before, i would think it beause of too many connections make the connectionpool overflowed, but i can not find how to deal it , pls help me!!

![image](https://user-images.githubusercontent.com/34122761/69313718-537eaa00-0c6d-11ea-9e73-9cfb0a37771d.png)

**Comment by david-alm** [comment]
I also just experienced this issue after a `dist-upgrade` and a full system reboot fixed this for me.

**Comment by andymccurdy** [comment]
"Connection reset by peer" simply means that the TCP connection between the client and server was interrupted by something. The server could have gone down or a network device between the client and server could have closed the connection.

Using the `health_check_interval` option can help alleviate these issues.

**Comment by arturs706** [comment]
I have a redis docker instance, Axum Rust backend, and I am experiencing the same issue while doing a stress test. Does anyone know how to work around this? Thank you
