### ISSUE TITLE
sentinel authentication

### ISSUE THREAD

**Issue by dashng** [andymccurdy/redis-py#1256]
**Version**: 5.0.5
**Platform**: centos7

**Description**: 

Customer requires to set the redis sentinel authentication.

I add the below configuration to 'sentinel.conf'.

```
protected-mode yes
requirepass "sentinelpass"
```

When I execute the testing command:
the sentinel password is different from the redis master password.
```
import redis
from redis.sentinel import Sentinel

sentinel = Sentinel([('10.124.51.34', 5000), ('10.124.51.35', 5000)], password='sentinelpass')
master = sentinel.master_for('redis-cluster', socket_timeout=25, password='redis-master-pass')
print(master.keys())
```

The error shows below:

![image](https://user-images.githubusercontent.com/13565116/71348447-8804bf00-25a7-11ea-8f93-442c7e7f5f3c.png)

Any help or suggestions will be appreciated! thanks!!!

**Comment by lework** [comment]
```python
from redis.sentinel import Sentinel
sentinel = Sentinel([
    ('192.168.77.130',26379),
    ('192.168.77.130',26380),
    ('192.168.77.130',26381),
],sentinel_kwargs={'password': '123456'}) 

sentinel.discover_master('lerep')
```

**Comment by dashng** [comment]
@lework  Thanks for the comments. The issue was raised last year, we find the solution by reading the source code in last year project release. But now we have find another solution, use haproxy and VIP to call master instance directly. As some package not support sentinel connection string very well.
The HA steups:
https://github.com/dashng/Operation-Deployment/blob/master/redis/Haproxy-Redis-Sentinel-Docker.md
