### ISSUE TITLE
why get_message() return None when I use the custom callback functions to handle published messages?

### ISSUE THREAD

**Issue by Adhders** [andymccurdy/redis-py#1259]
get_message() return None when I use the custom callback functions whose return value is not None  , How can I accquire the return value from the custom callback functions ?
I have tried  get_message, parse_response and listen ,but all can't get return value!

**` 
  def my_handler(message):
      print(message)
      return "ok"
`
p.subscribe(**{'my-channel': my_handler})
>>> message = p.get_message()
>>> print message
None**

**Comment by andymccurdy** [comment]
The message is only delivered to the callback function.
