### ISSUE TITLE
a new release of zipp breaks installation

### ISSUE THREAD

**Issue by GergelyKalmar** [andymccurdy/redis-py#1260]
I've been trying to install redis-py on Ubuntu 16.04 LTS (has Python 3.5.2), however, the installation breaks:

```
pip install redis
...
ERROR: Package 'zipp' requires a different Python: 3.5.2 not in '>=3.6'
```

It seems there has been a [new version of zipp](https://pypi.org/project/zipp/#history) released about 10 hours ago that causes the problem by requiring Python 3.6+. A workaround for now is pinning to `zipp==1.0.0`, which seems to resolve the issue.

**Comment by andymccurdy** [comment]
redis-py has no external python dependencies. I have no idea what the “zipp” package is.

**Comment by GergelyKalmar** [comment]
Hm, indeed, it was actually a dependency coming from pytest through importlib-metadata which already [has an issue](https://gitlab.com/python-devs/importlib_metadata/issues/107) for this, it's only that this surfaced when I updated my requirements.txt for installing redis-py. Sorry for the spam and thanks for the clarification! :)
