### ISSUE TITLE
ConnectionError when channel holds many messages each below buffer limit

### ISSUE THREAD

**Issue by kunadawa** [andymccurdy/redis-py#1261]
**Version**: What redis-py and what redis version is the issue happening on?
* redis-py - 3.3.11
* redis - 5:4.0.9-1ubuntu0.2

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
`Python 3.7.5 on Ubuntu 18.04.2`

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

When I publish many messages to a channel (each of them below the pubsub buffer limit) I get a connection closed error in python and `subscribe scheduled to be closed ASAP for overcoming of output buffer limits` in the redis log.

I resolved the error by setting `client-output-buffer-limit pubsub 0 0 0` in redis.conf. Is there an alternative configuration or work around to this?

Please my test case here - https://github.com/kunadawa/video-object-detection/commit/76913165a6517784dc6c60b5bf300cff0b0ae9bf

**Comment by andymccurdy** [comment]
Perhaps you've already looked at it but this behavior is described in the Redis docs here: https://redis.io/topics/clients (See the section titled "Output Buffer Limits". The Redis server imposes limits on the amount of data that can be buffered on the server side awaiting transport to the client.

In your test, the pubsub client is subscribed to a channel that has incoming data. That incoming data continues to grow as you're publishing more messages to it and eventually exceeds the limit defined in Redis.

You could instead do something like:

```python

for _ in range(100):
        redis_client.publish(channel_name, binary_string)

        # you need a wait_for_message like function that blocks until data is received
        # as you're trying to test async-like code synchronously.
        # see here: https://github.com/andymccurdy/redis-py/blob/master/tests/test_pubsub.py#L13

        message = wait_for_message(pubsub)
        # verify that message contains the data 

```

This way the server doesn't have to buffer all of the client output.

**Comment by kunadawa** [comment]
Thanks for the response Andy.

If the limits are on the amount of data that can be buffered on the server
side, I think the error could have happened during publish() which is not
the case.

The error occurs on the first get_message()

**Comment by andymccurdy** [comment]
You're using 2 separate TCP connections, one for publishing and the other for consuming. You're won't see the subscribed pubsub client become disconnected until you try to use it.

**Comment by andymccurdy** [comment]
Closing this for now. If I've overlooked something and you really believe this is a redis-py issue, please reopen.

**Comment by kunadawa** [comment]
Added some logging that appears to show the reddis error being logged during a publish(). 

Thanks for the help!

## Captured log call
DEBUG    root:detect_video_stream_utils_test.py:235 2020-01-29 15:25:30.683313: published message to reddis
DEBUG    root:detect_video_stream_utils_test.py:235 2020-01-29 15:25:31.698663: published message to reddis
**...**
DEBUG    root:detect_video_stream_utils_test.py:235 2020-01-29 15:25:47.904685: published message to reddis
DEBUG    root:detect_video_stream_utils_test.py:235 2020-01-29 **15:25:48.912894**: published message to reddis
DEBUG    root:detect_video_stream_utils_test.py:235 2020-01-29 15:25:49.927790: published message to reddis
**...**
DEBUG    root:detect_video_stream_utils_test.py:240 2020-01-29 **15:26:01.009169**: retrieving essage from reddis

## Reddis Log
1442:M 29 Jan **15:25:48.912** # Client id=7 addr=127.0.0.1:51504 fd=8 name= age=18 idle=18 flags=N db=0 sub=1 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=36 omem=34566138 events=rw cmd=subscribe scheduled to be closed ASAP for overcoming of output buffer limits.
