### ISSUE TITLE
Support memoryviews instead of explicitly requiring data to be bytes type

### ISSUE THREAD

**Issue by Cody-G** [andymccurdy/redis-py#1265]
**Version**: master
**Platform**: Python 3.6.1 Ubuntu 18.04
**Description**: memoryview objects are currently unsupported

Since Python's [memoryview](https://docs.python.org/3/library/stdtypes.html#memoryview) objects support Python's [buffer protocol](https://docs.python.org/3/c-api/buffer.html#bufferobjects) I think it makes sense for redis-py to accept memoryviews instead of explicitly requiring bytes types.  This can eliminate an unnecessary memory copy incurred by calling `tobytes()` on a memoryview.  In our case this is useful for interfacing with libraries like [pyarrow](https://arrow.apache.org/docs/python/).  This is just a one-line change since Python sockets already support memoryviews, I'll make a PR shortly.

**Comment by dpipemazo** [comment]
PR in question for where this feature would be useful:

https://github.com/elementary-robotics/atom/pull/234

We send high-frequency, low-latency, sometimes-serialized data through redis streams. Thanks for considering!
