### ISSUE TITLE
Unrecoverable error: TypeError("unhashable type: 'Redis'")

### ISSUE THREAD

**Issue by spockoyno** [andymccurdy/redis-py#1267]
**Version**: > 3.3.11 (current master)

**Platform**:  Python 3.7.1 and 3.8.1 on MacOS 10.14.6, Celery 4.4.0, Redis 5.0.7, Pycharm 2019.3

**Description**: I have a Celery app setup with a redis broker and backend. Running celery worker gives me the error. Using the previous  v3.3.11 in Python 3.7.1 works fine. 
Thanks!

![StackTrace](https://user-images.githubusercontent.com/18262815/73126037-8ca50480-3fa5-11ea-94ec-d21fdf9740ba.png)

**Comment by andymccurdy** [comment]
This looks like a celery/kombu issue. No part of the stack trace touches redis-py.

**Comment by spockoyno** [comment]
Hmm. Interesting. When I tried the  redis.py 3.3.11 version currently at pypi with Python 3.7.1 and Celery 4.4.0, everything worked fine. The error only appeared  when I tried the latest redis.py master, with everything else being the same. So I assumed that was the source of the error. My apologies for being  annoying.

**Comment by pawelad** [comment]
Hiya!

Release 3.4.0 also broke our Celery with Redis setup. The versions of `celery` and `kombu` didn't change, the only change between working setup and a broken one was `redis-py` was updated from `3.3.11` to `3.4.0`. The stacktrace is exactly the same as @spockoyno.

**Comment by pawelad** [comment]
Related issue on `kombu` side: https://github.com/celery/kombu/issues/1152

**Comment by Psayker** [comment]
@andymccurdy This issue looks like, all is break because before `3.4.0` `Redis`, have default `__eq__` and `__hash__`, in `3.4.0` only custom `__eq__` was added.

**Comment by lalvarezguillen** [comment]
> @andymccurdy This issue looks like, all is break because before `3.4.0` `Redis`, have default `__eq__` and `__hash__`, in `3.4.0` only custom `__eq__` was added.

Precisely. Domol's explanation here provides further context: https://github.com/celery/kombu/issues/1152#issuecomment-580681288

@andymccurdy does it make sense to you?
