### ISSUE TITLE
request to support memory_stats method

### ISSUE THREAD

**Issue by microprediction** [andymccurdy/redis-py#1268]
**Version**: redis==3.3.11  (using redis labs)

**Platform**: Py 3.8 

**Description**: It would be nice to support the memory_stats method

**Comment by andymccurdy** [comment]
Just implemented it in master. It'll go out in the next version.

**Comment by microprediction** [comment]
Thank you good Sir !








Peter Cotton





Senior Vice President, Chief Data Scientist





M 646-637-1338





intechinvestments.com















 





This message, including its attachments, contains information from Intech Investment Management LLC or one of its affiliates, which may be confidential and/or privileged. If it has been sent to you
 in error, please reply to advise the sender of the error and immediately delete this message. Thank you.
l
