### ISSUE TITLE
hmset() uses deprecated command HMSET

### ISSUE THREAD

**Issue by mirekphd** [andymccurdy/redis-py#1269]
Redis command HMSET is [deprecated](https://redis.io/commands/hmset) (its functionality was [moved](https://redis.io/commands/hset) to HSET command) since version 4.0.0 (July 2017) but `redis-py` still executes this deprecated command [in its hmset() function](https://redis-py.readthedocs.io/en/latest/_modules/redis/client.html#Redis.hmset). So the function should probably updated to use HSET without waiting for HMSET command to be entirely removed from Redis API.

**Comment by laixintao** [comment]
Hi @mirekphd 

I make a PR, please take a look, what does the new api looks to you?

https://github.com/andymccurdy/redis-py/pull/1271/files#diff-085cbe85ef9bc2ad832d79163eb39172R2990

I have to keep the `key, value` position args for backwards compatibility.

@andymccurdy Please also take a look :)
