### ISSUE TITLE
Change from time.time() to time.monotonic()

### ISSUE THREAD

**Issue by rolette** [andymccurdy/redis-py#1290]
redis-py 3.4.1

There are a few places in redis-py where it uses `time.time()` to check for elapsed time (health checks, timeouts on locks, etc.). I believe these are going to malfunction when daylight savings kicks in and moves the clock back an hour. Since it is only intervals being measured, switching to `time.monotonic()` would fix the problem nicely.

The biggest problems are in `Lock().acquire()` and `ConnectionPool()._checkpid()`. 

My tree has some local changes, so you won't be able to use this patch directly, but it's a small diff, so should still be helpful (hopefully):

[monotonic_diff.txt](https://github.com/andymccurdy/redis-py/files/4237159/monotonic_diff.txt)

**Comment by andymccurdy** [comment]
Sadly `time.monotonic()` is unavailable in Python 2.7 and we're still supporting that (for now). Is there a port or alternative that accomplishes the same thing in Py27?

**Comment by rolette** [comment]
The `monotonic` package on PyPI can be used on Python 2.x and Python 3 (pre-3.3). It falls back to an alias of `time.monotonic()` on Python 3.3+.

**Comment by nickgaya** [comment]
> I believe these are going to malfunction when daylight savings kicks in and moves the clock back an hour.

`time.time()` returns a Unix timestamp which is not affected by daylight savings time.

**Comment by rolette** [comment]
Well crap. Hate when I do that. @nickgaya is right on `time.time()`. It can still move around (including going backwards) when the RTC is set, so not fully trustworthy for measuring elapsed wall clock time. But yeah, likely not worth the extra dependency given you are keeping support for older versions of Python.
