### ISSUE TITLE
Procure a list of keys

### ISSUE THREAD

**Issue by TondiToday** [andymccurdy/redis-py#1292]
**Version**: redis 3.4.1

**Platform**: python 3.8.1/Debian linux 10
**Description**: Is there any method available (or in the pipeline) to view a list of locks in redis? I cant use redis-cli for this particular use case i want to be able to list out and delete keys via an api call using django framework (allow me to control my locks in a disaster relief event from outside a container)

**Comment by andymccurdy** [comment]
No. Locks (from the redis-py perspective) are simple Redis strings. If you happen to name all of your locks with a specific prefix, you could use the `KEYS` or `SCAN` command to identify them. Outside of that you’d have to look at how you’re naming the locks within your code base and query for them individually.

**Comment by TondiToday** [comment]
I will go with the keys/scan method. Thanks for the swift response
