### ISSUE TITLE
How to connect to a remote redis server through a squid proxy?

### ISSUE THREAD

**Issue by Hanny2010** [andymccurdy/redis-py#1295]
**Version**: redis-py 3.3.8 and redis 5.0.7.

**Platform**:  Python 3.7.4 on Mac

**Description**: 
Hi experts, 
I am trying to connect to a remote redis server through a squid proxy.
Can I set the proxy_server_url when creating a redis client? 
For example, `redis.Redis(host=host, password=password, proxies=SQUID_PROXY_SERVER_URL)`.
I didn't find any parameters for this, then how should I set the connection over some proxy server?

Thank you so much!

**Comment by andymccurdy** [comment]
I've never heard of anyone using a web proxy in front of Redis. I don't see how that could actually work as Redis isn't an HTTP service and provides no HTTP interface. As such there is no HTTP proxy support in redis-py.

**Comment by Hanny2010** [comment]
Hi Andy, thanks for helping! I've noticed that redis-py use a TCP socket to connect to redis server. And there seems a way to [establish a socket connection through an HTTP proxy in Python](https://gist.github.com/frxstrem/4487802). Is it possible we can use similar solution in redis-py?

Thanks and have a nice weekend!

**Comment by andymccurdy** [comment]
I don’t think that this is a good idea. Adding additional HTTP overhead will significantly impact performance. If you want to use a proxy, use a tcp proxy such as HA Proxy.

If you really need this to work with an HTTP proxy, you can subclass redis.Connection in your own code.

**Comment by Hanny2010** [comment]
Okay, I see. `Subclass redis.Connection` sounds reasonable. I'll give a try. Thanks!

**Comment by Hanny2010** [comment]
https://gist.github.com/Hanny2010/2ebee61894c661b0cab91fd131e2ef6e This is a feasible solution. It works for me. I'll close this issue and thanks Andy!
