### ISSUE TITLE
hmset deprecation wrongly in 3.4.1 section of release notes, but landed post-3.4.1

### ISSUE THREAD

**Issue by darkrain42** [andymccurdy/redis-py#1296]
**Version**: redis-py 3.4.1

**Description**: #1269 / #1271 deprecated `hmset` in the client, and added support for a `mapping` to the `hset` command.

That deprecation incorrectly shows up in the 3.4.1 section of the release notes (https://github.com/andymccurdy/redis-py/blob/e57daf554d6a4a66373de6605d13fb7a185852e9/CHANGES#L33-L34), even though it was merged in post-3.4.1:

```
* 7c023d2 - Enable warnings during tests and fix discovered cases (#1283) (3 weeks ago)
* 07e1c4b - Improve Redis.hmset() warning message (3 weeks ago)
* 3d8d523 - Make hset support multiple field/value pairs. (#1271) (3 weeks ago)
* 4b7f562 - (tag: 3.4.1) 3.4.1 (4 weeks ago)
```

**Comment by laixintao** [comment]
Sorry, my fault. I will open a PR fix to this.
