### ISSUE TITLE
Unexpected UNWATCH after pipeline EXEC

### ISSUE THREAD

**Issue by nickgaya** [andymccurdy/redis-py#1299]
**Version**:
Redis-py 3.4.1
Redis 5.0.7

**Platform**:
Python 3.8.2
Mac OS 10.13.6

**Description**:
When executing a transaction with watched keys, `Pipeline.execute()` does not clear the watching state of the pipeline object, so a subsequent call to `Pipeline.reset()` will send an extra `UNWATCH` command to the server.

Example:
```
from redis import Redis
redis = Redis(...)

with redis.pipeline() as pipe:
    pipe.watch("key")
    pipe.get("key")
    pipe.multi()
    pipe.set("key", "value")
    pipe.execute()
```

Redis monitor output:
```
1583397021.463844 [0 172.17.0.1:50360] "WATCH" "key"
1583397021.465269 [0 172.17.0.1:50360] "GET" "key"
1583397021.466502 [0 172.17.0.1:50360] "MULTI"
1583397021.466524 [0 172.17.0.1:50360] "SET" "key" "value"
1583397021.466531 [0 172.17.0.1:50360] "EXEC"
1583397021.467971 [0 172.17.0.1:50360] "UNWATCH"
```

**Comment by andymccurdy** [comment]
Thanks, merged in 9c8be70e12c501dd0682232e9a7b686ac5e70ec3
