### ISSUE TITLE
Pipeline incorrectly calls DISCARD after EXEC in case of EXECABORT error

### ISSUE THREAD

**Issue by nickgaya** [andymccurdy/redis-py#1300]
**Version**:
Redis-py 3.4.1
Redis 5.0.7

**Platform**:
Python 3.8.2
Mac OS 10.13.6

**Description**:
Executing an explicit transaction containing an invalid command results in a response error, masking the original parsing error.

Example:
```
from redis import Redis
redis = Redis(...)

with redis.pipeline() as pipe:
    pipe.multi()
    pipe.execute_command('INCR', 'a', 'b', 'c')
    pipe.execute()
```

Expected:
```
redis.exceptions.ResponseError: Command # 1 (INCR a b c) of pipeline caused error: wrong number of arguments for 'incr' command
```

Actual:
```
redis.exceptions.ResponseError: DISCARD without MULTI
```

**Comment by andymccurdy** [comment]
Merged in 07fec7e18996b6b3b4f30ec9636b88c9b287ece5
