### ISSUE TITLE
BRPOPLPUSH hangs forever in socket

### ISSUE THREAD

**Issue by jacopofar** [andymccurdy/redis-py#1305]
We have multiple processes using Redis and randomly they hang forever while performing a `BRPOPLPUSH` operation witha. timeout of 10 minutes. It seems to happen intermittently, about 1/ 200 times, and when it happens the process hangs forever.

The client instance was created with `health_check_interval=30` in an attempt to solve, but didn't work.

Using `gdb-python` I got this stack trace:

```
(gdb) py-bt
Traceback (most recent call first):
  File "/usr/local/lib/python3.7/dist-packages/redis/_compat.py", line 71, in recv
    return sock.recv(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/redis/connection.py", line 190, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/usr/local/lib/python3.7/dist-packages/redis/connection.py", line 248, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.7/dist-packages/redis/connection.py", line 316, in read_response
    response = self._buffer.readline()
  File "/usr/local/lib/python3.7/dist-packages/redis/connection.py", line 734, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.7/dist-packages/redis/client.py", line 892, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.7/dist-packages/redis/client.py", line 878, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.7/dist-packages/redis/client.py", line 1895, in brpoplpush
    return self.execute_command('BRPOPLPUSH', src, dst, timeout)
```

Is there some other method to ensure the socket is alive before trying an operation?

**Version**: redis 3.4.1

**Platform**: Python 3.7 in Debian stable running in a K8s pod

**Comment by laixintao** [comment]
Not sure if it's a connection issue, can you check the connection state using `ss` or `netstat` when it happens again?

Can you make the `timeout` shorter like 1 minute, issue another `BRPOPLPUSH` after 1 minute?

BTW How long dose this command block exactly?

**Comment by andymccurdy** [comment]
Unfortunately `health_check_interval` does nothing when using blocking commands such as `BRPOPLPUSH`.

The typical pattern that I recommend is to set `socket_timeout=N` and then use `N - T` as the timeout to `BRPOPLPUSH` where `N > T >= 2`. For instance, if you set `socket_timeout=30`, set the timeout of `BRPOPLPUSH` to something like 25 or so.

Then, structure your code like so:

```python
r = redis.Redis(socket_timeout=30)
...

def get_work():
    while True:
        value = r.brpoplpush(src, dst, 25)
        if value is not None:
            return value
```

In the above code, `get_work()` will block for up to 25 seconds waiting to pop a value off of `src`. If it found a value within that time, it will be returned. If no value was found, `get_work()` will loop and try again.

If for any reason the underlying connection becomes disconnected or stalled, a `TimeoutError` will be raised. Your code calling `get_work()` can catch this error and decide what to do. It might make sense to simply try again or if you want more flexibility. Or you could implement a strategy that alerts your team after some number of consecutive failures, etc.

**Comment by jacopofar** [comment]
Thanks for the quick answer @andymccurdy will try that!
