### ISSUE TITLE
Getting error when fetching data from aws elastic cache cluster

### ISSUE THREAD

**Issue by kundankumarjha** [andymccurdy/redis-py#1308]
**Version**: What redis-py and what redis version is the issue happening on?
latest

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
AWS lamda with Python 3.8
**Description**: Description of your issue, stack traces from errors and code that reproduces the issue
Some time it is accessing data from elastic cache and some time error like below.
[ERROR] ResponseError: MOVED 5798 10.220.93.183:6379
Traceback (most recent call last):
  File "/var/task/app.py", line 11, in handler
    res = r.get('name')
  File "/var/task/redis/client.py", line 1607, in get
    return self.execute_command('GET', name)
  File "/var/task/redis/client.py", line 902, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/var/task/redis/client.py", line 916, in parse_response
    response = connection.read_response()
  File "/var/task/redis/connection.py", line 752, in read_response
    raise responseEND RequestId: 04ea2538-b851-45fd-8194-12f90312447e
REPORT RequestId: 04ea2538-b851-45fd-8194-12f90312447e	Duration: 50.07 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 64 MB

**Comment by andymccurdy** [comment]
Looks like you're running a Redis cluster. You also need the redis-py-cluster library (https://github.com/Grokzen/redis-py-cluster)

**Comment by adamwrobel-ext-gd** [comment]
@andymccurdy  that library is outdated. It does not work due to breaking changes - removed `dict_merge` from `redis.client`. Was not patched for years. 
Are you saying this python library redis-py does not work in cluster mode?
