### ISSUE TITLE
How to know the number of ‘’name ‘’in the redis hash

### ISSUE THREAD

**Issue by xiaofeng3** [andymccurdy/redis-py#1311]
r.hset(name="name",key="key1",value="value")

**Comment by andymccurdy** [comment]
I’m not sure what you’re asking. Are you looking for the `HLEN` command?

**Comment by xiaofeng3** [comment]
How to get the number of the "name"s in the hset？，HLEN command is the number of keys to get a name

**Comment by andymccurdy** [comment]
In your example, `name` is the name of the hash key in Redis. `key` and `value` refers to the key/value pair inside of `name`. 

So `HLEN` will return the number of key/value pairs within `name`.

If you want the number of hash objects in Redis, you could use the `KEYS` command, but I wouldn’t recommend that in production. You could also use the `hscan` iterator, which would be more performant.

**Comment by xiaofeng3** [comment]
The problem has been solved, thank you
