### ISSUE TITLE
Feature Request: LCS Command

### ISSUE THREAD

**Issue by 2014BDuck** [andymccurdy/redis-py#1314]
**Version**: Latest

**Platform**: Any

**Description**: Hi. Thanks for checking this.
I noticed that a new command `LCS` is added to Redis: https://twitter.com/antirez/status/1245448546205216777
I am thinking about adding this to redis-py, but not sure if someone else is doing this. So I prefer posting a issue/feature req here first.

I didn't see any feature request on "issues" board, so if I posted it on a wrong place, please correct me. Thanks

**Comment by andymccurdy** [comment]
No one is working on this yet. Typically I like to see the official command documentation to understand how to implement it. I don't know enough about this command yet to even start.

**Comment by 2014BDuck** [comment]
Got it.
Same for the `ACL LOG` PR? 
Maybe I should poke @itamarhaber (no offense)  Any idea about the doc for some new features?
