### ISSUE TITLE
blpop blocked forever

### ISSUE THREAD

**Issue by kingname** [andymccurdy/redis-py#1331]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: What redis-py and what redis version is the issue happening on?

redis-py: 3.4.1
redis_version:4.0.9, single instance.

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure) 

Ubuntu 19.04
Python 3.7.3

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

My code:

```python
import redis
client = redis.Redis()
while True:
    data = client.blpop('key', timeout=5 * 60)
    if not data:
        continue
    parse(data[1])
```
sometime, this code will block forever even if there are many datas in the list. Especially when the list is empty for a long time, and then I lpush some data to it, the code could not read data from list, just blocks here. I must restart the program, then it could continue to consume.

**Comment by andymccurdy** [comment]
This is a common question that has been answered before. Check out the linked comment here: https://github.com/andymccurdy/redis-py/issues/1305#issuecomment-597305775

**Comment by andymccurdy** [comment]
Closing this as no response has been made. If you're still having an issue and the comments in #1305 aren't helpful, please feel free to reopen this.
