### ISSUE TITLE
PubSub.on_connect may be no call!

### ISSUE THREAD

**Issue by seewindcn** [andymccurdy/redis-py#1332]
**Version**: What redis-py and what redis version is the issue happening on?
3.2.1

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
windows 7

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue
redis/client.py: 
```
        if self.connection is None:
            self.connection = self.connection_pool.get_connection(
                'pubsub',
                self.shard_hint
            )
            # register a callback that re-subscribes to any channels we
            # were listening to when we were disconnected
            self.connection.register_connect_callback(self.on_connect)
```
connection_pool.get_connection is make sure return a connected connection;
so connection.register_connect_callback(self.on_connect) may be not effect;

**Comment by andymccurdy** [comment]
`PubSub.on_connect` does not (and should not) be called when first initializing the PubSub object. This callback should be called only when the TCP link is broken and reconnected.

**Comment by andymccurdy** [comment]
Closing this as I don't believe this to be a bug or issue. If you disagree, please reopen.
