### ISSUE TITLE
'hmset' with mapping of length 0

### ISSUE THREAD

**Issue by hrith** [andymccurdy/redis-py#1335]
I am receiving 'hmset' with mapping of length 0 error on accessing my admin url in django. 

I have set SESSION_ENGINE = 'redis'

After removing this line I am not receiving this error.

`#redis.py
from django.contrib.sessions.backends.base import SessionBase
from django.utils.functional import cached_property
from redis import Redis

class SessionStore(SessionBase):
    @cached_property
    
    def _connection(self):
        return Redis(
            host='127.0.0.1',
            port='6379',
            db=0,
            decode_responses=True
        )
    
    def load(self):
        return self._connection.hgetall(self.session_key)

    
    def exists(self, session_key):
        return self._connection.exists(session_key)
    
    def create(self):
        # Creates a new session in the database.
        self._session_key = self._get_new_session_key()
        self.save(must_create=True)
        self.modified = True
    
    def save(self, must_create=False):
        # Saves the session data. If `must_create` is True,
        # creates a new session object. Otherwise, only updates
        # an existing object and doesn't create one.
        if self.session_key is None:
            return self.create()
        data = self._get_session(no_load=must_create)
        session_key = self._get_or_create_session_key()
        self._connection.hmset(session_key, data)
        self._connection.expire(session_key, self.get_expiry_age())
    
    def delete(self, session_key=None):
        # Deletes the session data under the session key.
        if session_key is None:
            if self.session_key is None:
                return
            session_key = self.session_key
        self._connection.delete(session_key)
    @classmethod
    
    def clear_expired(cls):
        # There is no need to remove expired sessions by hand
        # because Redis can do it automatically when
        # the session has expired.
        # We set expiration time in `save` method.
        pass
`

**Comment by andymccurdy** [comment]
`HMSET` requires at least one key/value pair within the `mapping` dict. It is an error to call `HMSET` with an empty (0 length) dict. Assuming the error is coming from your `SessionStore.save()` method, you probably have no session data to save. A simple `if data:` check in that method will likely fix this.

**Comment by hrith** [comment]
@andymccurdy  while accessing the admin page of Django, I can't add that check.

**Comment by andymccurdy** [comment]
The `SessionStore` you pasted is not implemented properly. If you authored the `SessionStore` class, you can easily fix it. If this is from another package, you can either submit a but to that package and ask them to fix it or you can subclass their `SessionStore` and fix it yourself.

This is not a redis-py bug.

**Comment by andymccurdy** [comment]
Closing this as it does not appear to be a redis-py bug.
