### ISSUE TITLE
Low performance in stream colection

### ISSUE THREAD

**Issue by endikap100** [andymccurdy/redis-py#1338]
**Version**:
redis-py: 3.5.0
redis: 5.0.7

**Description**: 
I am testing the performance of stream collection, and I am seeing a performance penalty in the client side.
Redis slow log reports that the query is performed in 0,28s.
In a network capture I can see that it takes 0,31s from the first network package to the last package.
But the python script with the library takes 4s to get all the streams (in the attached code from "start getting streams" to "end getting streams").
I performed the test with 16424 streams with a total of 78212 entry's with an average of 6 variables each.
Is it the expected behavior? or am I doing something wrong?

**Code for the test**:
import redis
import datetime

redis_session = redis.Redis(host="127.0.0.1", port=6379)
print("start getting keys ", datetime.datetime.now())
keys = redis_session.scan_iter("stream*", count=10000)
print("end getting keys", datetime.datetime.now())

dict = {}
for key in keys:
    dict[key] = b"0-0"

print("start getting streams", datetime.datetime.now())
call_trace = redis_session.xread(dict, count=10000)
print("end getting streams", datetime.datetime.now())

**Comment by andymccurdy** [comment]
My hunch is that the majority of the time is being spent in 3 different locations. You could use a profiler to prove this and get more information.

1. Packing the request into the Redis protocol. Part of that happens directly in `Redis.xread` and the rest in `Connection.pack_command`. Both of these are fairly optimized and I don't know of any tricks to improve them.

2. Parsing the Redis protocol into Python objects. This happens within one of redis-py's parser classes. If you're not already using hiredis-py, I'd suggest that you install it in addition to redis-py. If redis-py finds hiredis-py, redis-py will automatically use the hiredis-py parser. hiredis-py is a C module that can greatly improve the parsing of Redis responses, especially when dealing with large amounts of small data items (lists, hashes, streams, etc.). You can install it by simply running `pip install hiredis`.

3. redis-py's `parse_xread` response callback. After one of the parser classes converts the stream into a Python object, redis-py runs the `parse_xread` callback to convert each stream into a more Pythonic and user-friendly object. You could override this behavior by installing your own custom response callback via `redis_session.set_response_callback('XREAD', my_callback)` where the callback looks like `my_callback(response, **options)`. It might be useful to see how much time is being spent in the default `parse_xread`.

Overall, my recommendation is to install hiredis-py if you're not already using it. Then if you're still having performance issues, run the above code through one of the various Python profilers to identify where the bottleneck is.

**Comment by endikap100** [comment]
Installing hiredis-py reduces the time to 0,96s.
I'll check the query packaging and changing the callback if I need more performance.
Thanks for the feedback!!
