### ISSUE TITLE
rediss connection not successful when passing the ca certificate as stream input.

### ISSUE THREAD

**Issue by praveenghuge** [andymccurdy/redis-py#1346]
**Version**: What redis-py and what redis version is the issue happening on?
redis python package - 3.2.0
also tried with newer redis version 3.5.2

**Platform**: Ubuntu

**Description**:

Cannot create redis connection when passing ca certificate as stream, the redis connection passes when the actual ca_cert file is present is at some location, but we should be supporting the passing the ca certificate as stream, similar to other library which are creating connection using ca certificate.

If it is possible please help us with the some example.

logs: 
`context.load_verify_locations(self.ca_certs)
FileNotFoundError: [Errno 2] No such file or directory
During handling of the above exception, another exception occurred:`

Thank you.

**Comment by praveenghuge** [comment]
Sample code used

**working:**
```
def get_connection():
    redis_connection = redis.Redis.from_url("rediss://admin:password.sample_url:port/0", 
    ssl_cert_reqs="required", ssl_ca_certs="/home/rest.crt")
    return redis_connection
```
in this case it is able to find the file and works properly


**not working:**

```
def get_connection(redis_cert):
    redis_connection = None
    with tempfile.NamedTemporaryFile() as cert_file:
        cert_file.write(redis_cert)
        cert_file.flush()
        redis_connection = redis.Redis.from_url("rediss://admin:password.redis_url:port/0",
        socket_timeout=5,
        ssl_ca_certs=cert_file.name,
        retry_on_timeout=True)
    return redis_connection
```
this case does not work had to explicitly create the file

**Comment by andymccurdy** [comment]
You're storing the certificate in a temporary file which gets deleted once the `NamedTemporaryFile` context manager exits. redis-py (actually the stdlib ssl module) only reads the contents of the certificate file when it's establishing the socket connection with the server. The `ssl_ca_certs` path must be valid and contain the certificate anytime you are executing a Redis command as redis-py connections are lazily created.

**Comment by praveenghuge** [comment]
we are getting cert file as input from other application and we cannot write that file into the system, due to which we wanted to NamedTemporaryFile or any other approach like passing the certs as buffer, is there any way we can achieve this without writing the file.

**Comment by andymccurdy** [comment]
redis-py uses the stdlib's `SSLContext.load_cert_chain` (https://docs.python.org/3/library/ssl.html#ssl.SSLContext.load_cert_chain) to read the certificates. A quick read of that link suggests it requires the cert chain to be on disk when the socket connection is established.

I'm not sure if there's another way to get the cert chain loaded into the `SSLContext`.

**Comment by OJFord** [comment]
A `NamedTemporaryFile` is still going to 'write that file into the system', it's just deleting it (because you haven't specified `delete=False`) when the context manager exits and you return the connection.

**Comment by praveenghuge** [comment]
thanks @OJFord will try the option, closing the issue
