### ISSUE TITLE
Redis.from_url overwrites password in kwargs with None if password is not provided in url

### ISSUE THREAD

**Issue by hmstepanek** [andymccurdy/redis-py#1347]
**Version**: What redis-py and what redis version is the issue happening on?
redis==3.5.1

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
python:3.6.8-alpine3.9

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

When calling the following:
```
from redis import Redis
Redis.from_url('redis://<hostname>:<port>', password='supersecret')
```

Internally, the passed url is parsed by urlparse into pieces and is used to update the kwargs. The kwargs get overridden with the urlparse parsed password [here](https://github.com/andymccurdy/redis-py/blob/afb3b81dca308307a17409a0a97bb52b070716b8/redis/connection.py#L1058) and so the password "supersecret" is replaced with None and this results in an authentication error.

**Comment by andymccurdy** [comment]
It seems to me that arguments passed in the URL should overwrite hardcoded values. Feel free to try and convince me otherwise.

**Comment by hmstepanek** [comment]
> It seems to me that arguments passed in the URL should overwrite hardcoded values.

That's totally fair and understandable. I think what I'm getting at here is there's a difference between specifying it as part of the URL and the URL taking precedence vs not specifying it as part of the URL and the unspecified value clearing the specified keyword argument.

I think there are a couple advantages for making this distinction:

- This would align this function with other connection functions that allow you to pass the argument via keyword argument. What seems to be going on in from_url is you can never pass anything that could be part of the URL as a keyword argument whether it's actually specified as part of the URL or not. It seems like this eliminates the purpose of allowing kwargs in the first place though there may be some that can't be specified as part of the URL.
- The behavior of clearing a specified keyword argument with an unspecified portion of the URL is a bit surprising.
- There may be cases where you have a URL to your Redis instance but the username and password are provided separately. In this scenario I only see two different methods for a user to handle this:
    
1. The user urlparse's their own URL into pieces and uses Redis directly.
1. The user urlparse's their own URL into pieces, adds the username and password, puts it back together and then calls from_url. 
Neither of these scenarios are ideal. If however, from_url only overwrote values that were actually specified as part of the provided URL, then the user could provide the username and password as keyword arguments without having to perform any additional logic themselves.

In general the confusion here is really around which kwargs you can specify in from_url and which you can't. So if the decision is to leave it as is, which is understandable and arguably a simpler implementation, I'd at least suggest documenting which kwargs are allowed and not overridden by parsing the URL since right now it's unclear without looking at the implementation.

**Comment by owtaylor** [comment]
Just a quick note that this surprised me as well - I expected `url_without_password, password=<password>` to work, and it would expect it to be documented if it doesn't. My workaround if it helps anyone:

``` python
from urllib.parse import quote, urlparse, urlunparse

def get_redis_client(url, password=None):
    # redis.Redis.from_url() doesn't support passing the password separately
    # https://github.com/andymccurdy/redis-py/issues/1347

    if password:
        parts = urlparse(url)
        netloc = f':{quote(password)}@{parts.hostname}'
        if parts.port is not None:
            netloc += str(parts.port)

        url = urlunparse((parts.scheme, netloc, parts.path, parts.params, parts.query, parts.fragment))

    return redis.Redis.from_url(url, decode_components=True)
```

**Comment by fedelaport** [comment]
We also expected `from_url` to allow overriding some things. We are using this now:

```python
def get_redis_client(url, **kwargs):
    """ 
        Get a redis client from url and kwargs,
        since redis.Redis.from_url() doesn't support passing kwargs.
    """

    up = urlparse(url)

    if up.scheme == "redis":
        print("[!] Warning, setting SSL to false because the URL schema")
        kwargs["ssl"] = False

    if "host" not in kwargs:
        kwargs["host"] = up.hostname
    if "username" not in kwargs:
        kwargs["username"] = up.username
    if "password" not in kwargs:
        kwargs["password"] = up.password
    if "port" not in kwargs:
        kwargs["port"] = up.port

    return redis.Redis(**kwargs)
```
