### ISSUE TITLE
monitor command escape cannot distinguish \x92 and \\x92

### ISSUE THREAD

**Issue by binux** [andymccurdy/redis-py#1349]
**Version**: >3.5.2 (current master https://github.com/andymccurdy/redis-py/tree/7973bd9)

**Platform**: Python 3.7.2 OSX

**Description**: 

For test case:

https://github.com/andymccurdy/redis-py/blob/9c8be70e12c501dd0682232e9a7b686ac5e70ec3/tests/test_monitor.py#L30

`b'foo\\x92'` is producing the same `response['command']` as `b'foo\x92'`

```
    def test_command_with_binary_data(self, r):
        with r.monitor() as m:
            byte_string = b'foo\x92 \\x92'
            r.get(byte_string)
            response = wait_for_command(r, m, 'GET foo\\x92 \\x92')
            assert response['command'] == 'GET foo\\x92 \\x92'
```

**Comment by andymccurdy** [comment]
I did some digging into this today and resolved this issue. We were trying to be clever and un-escaping slash characters in the command string.
