### ISSUE TITLE
Semaphore Implementation

### ISSUE THREAD

**Issue by cemremengu** [andymccurdy/redis-py#1355]
Is there a[ (counting) semaphore ](https://redislabs.com/ebook/part-2-core-concepts/chapter-6-application-components-in-redis/6-3-counting-semaphores/) implementation provided? If not, would you consider a PR?

**Comment by andymccurdy** [comment]
There is no counting semaphore implementation, though there is a basic `Lock` implementation. At this time I'm not convinced that this library needs more lock-like implementations. This would be trivial to implement in a 3rd party package or within your own codebase. If you feel strongly that this needs to be included within redis-py, please let me know.

**Comment by cemremengu** [comment]
Right, I had some time to sleep over this and found out that it is actually trivial to implement.

Thanks for your answer and your work!
