### ISSUE TITLE
How to test PubSub for multiple messages over a single function?

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [andymccurdy/redis-py#1356]
**Version**: Latest

**Platform**: Python 3.7 on all plats I guess.

**Description**: 

Looking to test my PubSub in Django. A single function (a view) executes several publish commands. I took a look at test_pubsub.py (and I may have missed the solution), but I'm not entirely sure how I'd get all the messages executed. The `wait_get_message` seems to only be returning a single string. Is there maybe some method of collection of messages over a period of time for my pytest cases? Thank you!

**Comment by andymccurdy** [comment]
If you're testing a view that publishes 3 messages, call `wait_for_message` 3 times in your test to get each of the messages. They're guaranteed to be retrieved in the same order that you sent them.

Alternatively, you could mock the pubsub object's `publish()`, run the view, and then verify that the mocked `publish()` was invoked 3 times with the expected arguments.

**Comment by Andrew-Chen-Wang** [comment]
> They're guaranteed to be retrieved in the same order that you sent them.

Ohh that helps a lot. Thank you!
