### ISSUE TITLE
Random Connection refused issue

### ISSUE THREAD

**Issue by mangleddata** [andymccurdy/redis-py#1361]
**Version**: redis_version:4.0.9,  redis-py __version__ = '3.5.3'
**Platform**: What platform / version? (python 3.6.6, Ubuntu 18.04.3 LTS, Amazon EC2)

**Description**: I am using redis-py to connect to a local redis. There are many different threads and independent process that connects to redis (the number of clients should still be small < 10). At random points, I keep getting connection refused error.
"Error 111 connecting to 127.0.0.1:6379. Connection refused."
This is not reproducible consistently. Can you please offer any pointers on how to rootcause this ? I've tried many things (including locking before get/put) - but this random error pops up during put and goes away.  I use a singleton connection pool and have enough headroom for CPU/memory etc. Some of the connection stats look like below and nothing stands out from what I could see.

# Stats
total_connections_received:6
total_commands_processed:5380
instantaneous_ops_per_sec:59
total_net_input_bytes:374586707
total_net_output_bytes:139631996
instantaneous_input_kbps:5111.95
instantaneous_output_kbps:6.49
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:90
keyspace_misses:39
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

**Comment by andymccurdy** [comment]
Do you happen to have a maxclients limit set on the server? Not sure why else you’d be getting a ConnectionRefused to localhost. ConnectionRefused comes from the system’s TCP stack when the network or destination server actively refused to allow a connection to be established.

A traceback might be helpful.

**Comment by mangleddata** [comment]
I hadn't set any limit and default value would've been assumed (10000 as I see now). In any case, I purged and reinstalled redis and it seems to be fine so far (last 15 minutes). Will close this for now since it is not reproducible.
