### ISSUE TITLE
callable handler not returning value from pubsub

### ISSUE THREAD

**Issue by mahdi-b** [andymccurdy/redis-py#1363]
Is the fact that pattern or channel subscription handler does not return values a feature or a bug. In the example below, which is slightly modified from the README page, "received a message" is indeed printed, but the value True is not returned.

```
>>> def my_handler(message):
    print("received a message")
    return True
>>> p.subscribe(**{'my-channel': my_handler})
```
If this is a conscious design decision, can you please explain the logic behind this decision and how could one go about returning values from a handler?

**Comment by andymccurdy** [comment]
Message handlers don't return values. Think of them like a callback. They are invoked via the pubsub client directly, not from user code. The client would have no idea what to do with values that your handler may return and thus ignores any return value(s).

**Comment by mahdi-b** [comment]
Thank's @andymccurdy. Any other way to implement this and get something like futures or promises that return values?

**Comment by andymccurdy** [comment]
Futures or promises are just a different kind of return value, and you end up in the same situation -- the pubsub client has no idea what to do with any type of value that a message handler returns.

Instead, your message handler can call into other parts of your codebase, passing whatever values you want, which gives you the ability to do anything you really want.

**Comment by andymccurdy** [comment]
Closing this as it doesn't appear to be a bug in redis-py. If you need further help or clarification, feel free to reopen.
