### ISSUE TITLE
Connections is CLOSE_WAIT state 

### ISSUE THREAD

**Issue by inewlife** [andymccurdy/redis-py#1364]
server = redis server 5.0.6 with haproxy
redis = 3.5.3
Ubuntu (Kubernetes POD)

we are seeing many connection at the application in CLOSE_WAIT state. So many that application pod runs of all the file descriptors. Restart is the only option.
At the Redis server there are no dangling connection to the clients however. We are seeing this issue with multiple application clients.

**Comment by andymccurdy** [comment]
Please provide an example of how your codebase constructs and uses the `Redis` instance(s).

**Comment by inewlife** [comment]
```
redis_db = redis.StrictRedis(host=host, port=port, password=password, db=0, decode_responses=True,
                             socket_connect_timeout=5, max_connections=12, socket_keepalive=True, socket_timeout=5)
```
redis_db is gloabel

**Comment by inewlife** [comment]
I found that this problem only occurs under multithreading, single threading does not

**Comment by inewlife** [comment]
`    def disconnect(self):
        "Disconnects from the Redis server"
        self._parser.on_disconnect()
        if self._sock is None:
            return
        try:
            if os.getpid() == self.pid:
                shutdown(self._sock, socket.SHUT_RDWR)
            self._sock.close()
        except socket.error:
            pass
        self._sock = None`

why not raise error

**Comment by andymccurdy** [comment]
Are you manually calling `disconnect()` anywhere?

**Comment by inewlife** [comment]
- I did not disconnect manually

- Raising an error in such a situation seems wrong,But it can be printed to help locate the problem

- My redis server is proxied through haproxy
Now I find I change the haproxy  config,It' ok now, However, I still think that redis-py has a problem when dealing with server disconnection


`timeout connect 5s
timeout queue   5s
timeout client 30s
timeout server 30s
timeout client-fin 30s
timeout server-fin 30s
timeout tunnel  1h`

**Comment by andymccurdy** [comment]
What setting(s) did you change in haproxy?

**Comment by inewlife** [comment]
add those settings

timeout client-fin 30s
timeout server-fin 30s
timeout tunnel 1h

**Comment by andymccurdy** [comment]
What's the value of the `timeout` parameter on your Redis server? It's likely specified in your redis.conf file. I assume it's > 0.

If so, then this is what's likely happening:

1. You have some sort of spike in activity that causes many connections to be created. This would explain why you're only seeing this behavior when running your app in a threaded environment.
2. The spike goes away and most of those connections go idle. The server eventually disconnects them due to the server's `timeout` value.
3. The client continues to use a small set of the allocated connections, causing them to stay healthy. The rest of the connections in the connection pool remain idle but aren't actively used.

**Comment by inewlife** [comment]
My redis server does not set the timeout parameter, but haproxy is set, the socket should be closed by haproxy idle connection. After the client is in CLOSE_WAIT, it should actively call socket.close() and then release it from the connection pool. The problem now is that it is only released, and the socket is still in the system.

**Comment by andymccurdy** [comment]
That's the nature of TCP. A socket closed on one end doesn't trigger a significant event on the opposite end. In our case, the only way we know that a socket has been disconnected on the other end is that we can read exactly 0 bytes from it.

redis-py does not currently check for reap stale connections.
