### ISSUE TITLE
How to close idle Redis SSE connections?

### ISSUE THREAD

**Issue by Atin007** [andymccurdy/redis-py#1366]
In our web application, we are using redis-py to connect with Google cloud Redis (MemoryStore). Also, we are using flask_sse. Although we close the SSE connections from the client-side, the Redis doesn't close these connections. Is there a way we can achieve this in redis-py in our backend. Thanks!

**Version**: redis==2.10.6

**Platform**: Python 2.7 Flask app & Google cloud MemoryStore (Redis)

Thanks!

**Comment by andymccurdy** [comment]
You can forcefully disconnect all connections in the pool by calling `<redis_instance>.connect_pool.disconnect()`. This is not threadsafe -- if you have other threads using this connection pool they could encounter issues. Also, if you execute any redis command after the `disconnect()`, new connections will be created.

I'd also suggest upgrading to redis-py 3.5.x. Your version is quite old.

**Comment by andymccurdy** [comment]
Closing this as I believe the question has been answered. Feel free to re-open if you need further clarification.
