### ISSUE TITLE
Issues working with a Redis object across a DaemonContext

### ISSUE THREAD

**Issue by portante** [andymccurdy/redis-py#1369]
**Version**: 3.5.3

**Platform**: Fedora 31 (tox env)

**Description**: Closing down Redis() objects when using `DaemonContext` requires knowledge of the underlying connection pool

Lets say we do the following:

```
import redis

r = redis.Redis(host='localhost', port=17001, db=0)
r.set('key', 'value')
r.get('some-key')

with DaemonContext(...):
    do_something_with(r)
```

This won't work because all the open file descriptors maintained by the connection pool are closed by the `DaemonContext`.

To get around this one has to re-create the `Redis()` instance:

```
import redis

r = redis.Redis(host='localhost', port=17001, db=0)
r.set('key', 'value')
r.get('some-key')
r.connection_pool.disconnect()
del r

with DaemonContext(...):
    r = redis.Redis(host='localhost', port=17001, db=0)
    do_something_with(r)
```

Is there some way we can make this a bit more intuitive?  Perhaps with a `Redis()` method to return the list of open file descriptors that should be preserved?  Or adding a method of `Redis()` to properly close down internal state?

**Comment by andymccurdy** [comment]
Based on some googling, I'm assuming you're using the python-daemon package. I also saw PEP 3143 which discusses this, but given that it's from 2009 and has a status of "Deferred" seems to suggest that it won't be available in the standard library anytime soon. Therefore I'm not interested in officially supporting `DaemonContext` within this library. However, if there's common sense things that we can do to make interacting with the packages like python-daemon easier, then we should certainly consider it.

I don't particularly like the idea of of returning a list of open file descriptors as those can change in the background if the connection pool is in use by multiple threads.

And it seems like you've already found the `ConnectionPool.disconnect()` method that shuts everything down. The `Redis` class maintains no other internal state that needs to be cleaned up, so any new method directly on the `Redis` class would simply call `connection_pool.disconnect()`.
