### ISSUE TITLE
slowlog get - does not include fields added in Redis version 4

### ISSUE THREAD

**Issue by RoeyPrat** [andymccurdy/redis-py#1374]
**Version**: What redis-py and what redis version is the issue happening on?
any version of redis-py up to master (last release Is 3.5.3), and Redis version 4+
**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
issue is platform agnostic.
**Description**: Description of your issue, stack traces from errors and code that reproduces the issue
`slowlog get` does not include fields added in Redis version 4:

- Client IP address and port (4.0 only).
- Client name if set via the CLIENT SETNAME command (4.0 only).

**Comment by RoeyPrat** [comment]
noticed in PR https://github.com/andymccurdy/redis-py/pull/1352

**Comment by RoeyPrat** [comment]
@ian28223 let me know if you want to work on this issue. If not, I'll handle it.

**Comment by ian28223** [comment]
@RoeyPrat feel free to work on it and close mine. please link me to the new PR though so I can watch it. Thanks!
