### ISSUE TITLE
saving subscriptions across pubsub connections

### ISSUE THREAD

**Issue by dcguim** [andymccurdy/redis-py#1377]
I am using python 3.8.2, Redis server version=6.0.5 and redis-py 3.5.2.
I am trying to persist subscriptions even after the pubsub object was closed. I am afraid it is not very clear to me, the scope of the PubSub objects, in one hand it shouldn't be shared among several threads, on the other I can't persist changes to it. 
```python
>>> import redis
>>> r = redis.Redis(host='localhost', port=6379,db =0)
>>> ps =r.pubsub()
>>> ps.subscribe('ch1')
>>> r.pubsub_numsub('ch1')
[(b'ch1', 1)]
>>> r.bgsave()
True
>>> r.save()
>>> ps.close()
>>> ps = pubsub_numsub()
>>> r.pubsub_numsub('ch1')
[(b'ch1', 0)]
```
Can published messages also be persisted/loaded?

**Comment by andymccurdy** [comment]
`pubsub.close()` closes the underlying connection to the Redis server and unsubscribes from any channels and/or patterns that you've subscribed to.

I'm confused as to why you'd want to close the pubsub object yet stay subscribed to channels and/or patterns. Can you explain what you're trying to do?

**Comment by dcguim** [comment]
I would like to use redis-py in a webserver, to create a notification system between users; I am trying to persist subscriptions to disk. So in case the server goes down, I am in another thread, or any other case in which I don't have access to the PubSub object; I am still able to fetch those subscriptions. 
`pubsub.close()` was just a way to simulate, this lack of access to the pubsub object.
If this is not possible on the redis-py level, I can still store the subscription relationship between users in a relational database and subscribe then back again, if I am in another thread. But this seemed like an overkill.

**Comment by andymccurdy** [comment]
Correct, you need to keep a pubsub object open to continue to receive messages.

If these messages are important I would suggest using a persisted data structure like a list or stream. In the past I’ve created a list key per user. When the web server fetches the message list for a user, you can truncate the user’s list. I’ve found this far more effective and easier to work with.

Pubsub is unreliable by design.

**Comment by abrookins** [comment]
Streams definitely seem like a better fit here. See the docs for more: https://redis.io/topics/streams-intro

There's also a free course from Redis Labs on how to use Streams: https://university.redislabs.com/courses/ru202/

**Comment by dcguim** [comment]
Thanks @andymccurdy and @abrookins, for the clarification and the quick reply. I guess this issue can be closed.
