### ISSUE TITLE
Wrong number of arguments for 'set' command version 3.5.3

### ISSUE THREAD

**Issue by alexanderbakhmach** [andymccurdy/redis-py#1379]
**Version**:  redis-py version -  3.5.3.  Redis version - 2.4.5

**Platform**: Windows 10

**Description**: Receive the error:
```
...
 redis.exceptions.ResponseError: wrong number of arguments for 'set' command
...
```
 When try to use redis lock the next way. 
```
>>>import redis
>>>r = redis.Redis()
>>>
>>>with r.lock('my-lock-key', blocking_timeout=5) as lock:
>>>    pass
>>>
```

**Comment by andymccurdy** [comment]
You need Redis server version >= 2.6.12 to use redis-py locks. We require support for the `nx` and `px` options of the `SET` command.

**Comment by andymccurdy** [comment]
Closing this as it seems like a server version issue. If you upgrade to 2.6.12 or higher and still have issues, please reopen.
