### ISSUE TITLE
Redis Cluster

### ISSUE THREAD

**Issue by farzad-xgen** [andymccurdy/redis-py#1385]
Is there any plan to support Redis cluster mode (the way it is set up in AWS ElastiCache)? We used to use redis-py-cluster but now it has an RC to support Redis > 3.1.00 but it's been frozen for a while and the repo owner is not responding. We're using cluster mode for some tasks and we also use Celery (using another setup with no cluster) and now we need to use both in a single task and now we are kind of stuck! Celery doesn't work with Redis < 3.4.0 and the official redis-py-cluster on PyPi is not working with Redis > 3.1.0!!!

**Comment by raphaelauv** [comment]
[redis-py-cluster](https://github.com/Grokzen/redis-py-cluster) is an active repo

**Comment by RoeyPrat** [comment]
Hi @farzad-xgen, sorry, but support for Redis cluster mode in redis-py is currently not planned. 
Please work with the `redis-py-cluster` community to resolve this issue if it persists.
