### ISSUE TITLE
redis.sentinel.MasterNotFoundError: No master found for master01 (But able to connect to master with Redis class)

### ISSUE THREAD

**Issue by Asrst** [andymccurdy/redis-py#1388]
**Description**:  Trying to connect with redis sentinel but having the above error. But `master01` is present (i.e. 192.168.10.213:6379) and I even verified with redis-cli command.

```
> $ redis-cli -u redis://MY_PASSWORD@192.168.10.213:26379
> 192.168.10.213:26379 > sentinel master master01
>  1) "name"
>  2) "master01"
>  3) "ip"
>  4) "192.168.10.213"
>  5) "port"
>  6) "6379"
```

Below is the code snippet I am using for connection (which is raising the MasterNotFoundError):

```
from redis.sentinel import Sentinel
sentinel = Sentinel([('192.168.10.213', 26379),
                     ('192.168.10.214',26379),
                     ('192.168.10.215',26379)], socket_timeout = None, sentinel_kwargs={'password': 'MY_PASSWORD'})
r = sentinel.discover_master('master01')
print(r)
```

Later to verify, I connected directly to master using `Redis` class and its working 

```
>>> import redis
>>> r = redis.Redis(host='192.168.10.213', port=6379, password = 'MY_PASSWORD')
>>> r.set('foo', 'bar')
True
>>>r.get('foo')
b'bar'
```
Tried searching, but never got the real issue. What could be potential issue here ? 
Anything to do with redis-py client (or) could be improper configuration on redis-server ?

**Version**: latest (v3.5.3) - Unable to establish proper connection using redis.Sentinel

**Platform**: Python 3.7.4 on Ubuntu 18.04

**Comment by filipcima** [comment]
Hi, I am having the same trouble as @Asrst described above.

Version: latest (v3.5.3) - Unable to establish proper connection using redis.Sentinel
Connecting to: REDIS 6
Platform: Python 3.7.3 on Debian 10.4

**Comment by Asrst** [comment]
It turned out to be config issue on redis-server. thanks you

**Comment by hrichakabir** [comment]
> ```python
> password="REDIS_PASS"
> ```

Facing the same issue, It would be great if you can guide me configuration changes on redis-server.

**Comment by hrichakabir** [comment]
> 

Facing the same issue, It would be great if you can guide me configuration changes on redis-server.

**Comment by shahar-trullion** [comment]
> > 
> 
> Facing the same issue, It would be great if you can guide me configuration changes on redis-server.

In our project we created a patch for aioredis_sentinel_pool.patch
`diff -Naur from/pool.py to/pool.py
--- from/pool.py	2022-02-16 11:31:35.000000000 +0200
+++ to/pool.py	2022-02-16 11:32:23.000000000 +0200
@@ -237,6 +237,7 @@
                 pool = await create_pool(
                     address, minsize=1, maxsize=2,
                     parser=self._parser_class,
+                    password=self._redis_password,
                     )
             pools.append(pool)
             return pool`

hope it will help you

**Comment by c-dev-acc1** [comment]
> I think your problem here is that you're specifying password only for sentinel. If your redis instance is password protected too, you need to pass it in connection_kwargs like in following code snippet:
> 
> ```python
> sentinel = Sentinel(["localhost:26379"], password="REDIS_PASS", sentinel_kwargs={"password": "SENTINEL_PASS"})
> ```
> 
> Hope it helps.

I still cant connect. Did I miss anything?
```
>>> sentinel = redis.sentinel.Sentinel([('sentinel.redis', 5000)], password='password', sentinel_kwargs={'password': 'password'}).discover_master('mymaster')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/redis/sentinel.py", line 252, in discover_master
    raise MasterNotFoundError(f"No master found for {service_name!r}{error_info}")
redis.sentinel.MasterNotFoundError: No master found for 'mymaster' : Redis<ConnectionPool<Connection<host=sentinel.redis,port=5000,db=0>>> - AuthenticationError('AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?')

>>> sentinel = redis.sentinel.Sentinel([(':password@sentinel.redis', 5000)], sentinel_kwargs={'password': 'password'}).discover_master('mymaster')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/redis/sentinel.py", line 252, in discover_master
    raise MasterNotFoundError(f"No master found for {service_name!r}{error_info}")
redis.sentinel.MasterNotFoundError: No master found for 'mymaster' : Redis<ConnectionPool<Connection<host=:password@sentinel.redis,port=5000,db=0>>> - ConnectionError('Error -2 connecting to :password@sentinel.redis:5000. Name or service not known.')
```
