### ISSUE TITLE
Closing unused connections

### ISSUE THREAD

**Issue by aartur** [andymccurdy/redis-py#1389]
**Version**: 3.3.8, I checked the changelog, but I didn't notice any changes related to the issue.

**Platform**: Python 3.7.7 on Ubuntu 18.04.

**Description**: I want the Redis connections to be closed when they are not used, but I can't find the needed config/API to make it happen.

Motivation: we're exceeding the limit of the opened connections set by a third-party Redis server. Our application doesn't perform many Redis calls, but a single call is sufficient to make the connection persistently opened. So we would like to close connections when they are not used for any communication, even if it means waiting longer for acquiring a new connection (I checked the performance of creating a new connection and it's in single-milliseconds for our case).

One option would be to create a new `Redis` client instance for each usage, but this requires making many code changes and won't fix usages by third-party libraries like `django-redis`.

I tried to make my own version of a connection pool:
```python
class DisconnectingConnectionPool(redis.connection.ConnectionPool):

    def release(self, connection):
        super().release(connection)
        connection.disconnect()
```

And while it worked well for single-threaded usage, it resulted in multiple errors when used from multi-threaded code (errors like `Bad file descriptor` or `self._sock` becoming `None`).

**Comment by andymccurdy** [comment]
Several thoughts:

Reverse the order of the commands in your custom `release()` method. As written, the connection is is returned to the pool by the parent's `release()` where it can be picked up by another thread. If that happens, you're ripping the proverbial rug out from underneath the other thread by then disconnecting its connection.

Alternatively/additionally, consider specifying `max_connections` when creating the connection pool. This limits the number of connections that can be created. The default `ConnectionPool` will raise an error if you try to exceed the number of connections. The `BlockingConnectionPool` will block if you try to exceed the numbers of connections. You can specify a `timeout` argument to the `BlockingConnectionPool` which indicates the max number of the seconds to block for before raising an error.

**Comment by aartur** [comment]
> Reverse the order of the commands in your custom `release()` method. As written, the connection is is returned to the pool by the parent's `release()` where it can be picked up by another thread. If that happens, you're ripping the proverbial rug out from underneath the other thread by then disconnecting its connection.

If I make this change (the reversing of the statements) is it guaranteed it will work 100% correctly? Overall I would much prefer if it would be a supported configuration inside the library, because I don't want the risk of getting bugs (and I don't want to maintain such custom low-level code across library updates).

> Alternatively/additionally, consider specifying `max_connections` when creating the connection pool. This limits the number of connections that can be created. The default `ConnectionPool` will raise an error if you try to exceed the number of connections. The `BlockingConnectionPool` will block if you try to exceed the numbers of connections. You can specify a `timeout` argument to the `BlockingConnectionPool` which indicates the max number of the seconds to block for before raising an error.

Thanks for the tip, but I don't think it will resolve our issue. We run many long-running processes which usually make a Redis call maybe once per 10 seconds, and even if I reduce the number of created connections for the multi-threaded use cases, just having a single connection opened persistently in each of the processes might exceed the server connections limit.

**Comment by andymccurdy** [comment]
> If I make this change (the reversing of the statements) is it guaranteed it will work 100% correctly? Overall I would much prefer if it would be a supported configuration inside the library, because I don't want the risk of getting bugs (and I don't want to maintain such custom low-level code across library updates).

I don't see why this wouldn't work. The calling thread owns the connection until `super().release(connection)` would be called. This is probably your best bet for now.

**Comment by ionelmc** [comment]
How about this?
```python
class NoConnectionPool(ConnectionPool):
    def owns_connection(self, connection):
        return False
```
