### ISSUE TITLE
hset mapping not working

### ISSUE THREAD

**Issue by dondoktor** [andymccurdy/redis-py#1396]
**Version**: What redis-py and what redis version is the issue happening on?
redis windows x64 3-2-100
redis-py 3.5.3 and 3.5.2

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
windows 10
python 3.7.6

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

I wanted to use hmset to insert a dict in redis db
`info = {'a': 10, "b":1010}
pipe.hmset("hashname",info)`

and it got me the warning:
DeprecationWarning: Pipeline.hmset() is deprecated. Use Pipeline.hset() instead.

so i looked up how to use pipeline.hset
in the documentation it says
pipeline.hset(name, key=None, value=None, mapping=None)
and i found out that i should write
`info = {'a': 10, "b":1010}
pipe.hset("hashname",mapping=info)`

but this gives me the error

  File "lib\site-packages\redis\connection.py", line 756, in read_response
    raise response

ResponseError: Command # 1 (HSET hashname a 10 b 1010) of pipeline caused error: wrong number of arguments for 'hset' command

could be a redis windows problem instead of a redis-py problem though, i don't know.

**Comment by andymccurdy** [comment]
You need Redis server version 4.0+ to be able to use `HSET` with multiple key/value pairs. If you don't want to upgrade your Redis server, you'll need to use `HMSET`.

**Comment by mrwonderfulness** [comment]
Why is the syntax for hset while using dictionaries 
`r.hset(key,None,None,queue_entry) `

What do those Nones represent?
Could not find any reference except here:
https://stackoverflow.com/questions/32276493/how-to-store-and-retrieve-a-dictionary-with-redis

<img width="827" alt="Screen Shot 2021-02-01 at 11 17 53" src="https://user-images.githubusercontent.com/73687088/106407402-4b301a80-647f-11eb-90be-0fff3f77fcc0.png">

and it doesn't appear to be consistent with the standard Redis syntax, so the Redis docs don't help.

**Comment by andymccurdy** [comment]
The signature is `def hset(self, name, key=None, value=None, mapping=None)`. `key` and `value` exist from when `HSET` did not accept more than one key/value pair. They still exist for backwards compatibility. You don't need to pass the two `None` arguments if you use keyword arguments like so:

```python
my_dictionary = {
    'key1': 'value1',
    'key2': 'value2',
}
r.hset(key, mapping=my_dictionary)
```
