### ISSUE TITLE
Delete all keys after reconnect

### ISSUE THREAD

**Issue by egornevezhin** [andymccurdy/redis-py#1401]
**Version**: 3.5.3

**Platform**: redis:alpine/Mac OS 10.15.6, python 3.7

**Description**:  I connect to redis from fastapi. When the application is restarted, the keys in the database are cleared. Why can this be so?

```python
def redis_connect() -> redis.client.Redis:
    try:
        pool = redis.ConnectionPool(
            host=os.getenv('REDIS_HOST'),
            port=6379,
            password=os.getenv('REDIS_PASSWORD'),
        )
        return redis.Redis(connection_pool=pool)
    except redis.AuthenticationError:
        print("AuthenticationError")
        sys.exit(1)```

**Comment by andymccurdy** [comment]
redis-py only deletes keys when you explicitly tell it to.

**Comment by Grokzen** [comment]
@egornevezhin Nothing in the code above or any code path that it uses above would be the cause of your keys being deleted. It must have been from either some other code, or other trigger for data to be lost in your case.

**Comment by andymccurdy** [comment]
Ya, this doesn't seem to be a redis-py issue.
