### ISSUE TITLE
Error on Monitor initializzation

### ISSUE THREAD

**Issue by Capantonio** [andymccurdy/redis-py#1407]
**Version**: i'm using redis-py 3.5.3 and redis 2.4.6

**Platform**: Python 3.7 on Windows 64-bit

**Description**: I'm making a simple monitor-view script for monitoring some traffic of information, but when i run the code drop me the following error :  
```
Traceback (most recent call last):
  File "c:/Users/******/Desktop/******/RedisMonitor.py", line 72, in <module>
    for Result_SL in result.listen():
  File "C:\Users\******\AppData\Local\Programs\Python\Python371\lib\site-packages\redis\client.py", line 3373, in listen
    yield self.next_command()
  File "C:\Users\******\AppData\Local\Programs\Python\Python371\lib\site-packages\redis\client.py", line 3345, in next_command
    db_id, client_info, command = m.groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

the code i run is this:

```
70    with Rserver.monitor() as result:
71        MonitUP = True
72            for Result_SL in result.listen():
```

**Comment by andymccurdy** [comment]
This is likely because of how old your Redis server is. The client is attempting to parse the monitor log entry. I believe the format of the log entries changed sometime around server version 3.0 or 4.0. I'd suggest upgrading your Redis server to a more recent version.

**Comment by andymccurdy** [comment]
Closing this as it seems to be because of how old your server is. If after upgrading your Redis server you're still having issues, please re-open and provide more info.
