### ISSUE TITLE
Health check usage gives pylance/mypy error

### ISSUE THREAD

**Issue by lexicalunit** [andymccurdy/redis-py#1409]
**Version**:
- redis: 6.0.5
- redis-py: 3.5.3
- python: 3.7.7

**Platform**:

- Heroku

**Description**:

So the README says:

> To combat this, redis-py can issue regular health checks to assess the liveliness of a connection just before issuing a command. Users can pass health_check_interval=N to the Redis or ConnectionPool classes or as a query argument within a Redis URL. The value of health_check_interval must be an integer. A value of 0, the default, disables health checks. Any positive integer will enable health checks. Health checks are performed just before a command is executed if the underlying connection has been idle for more than health_check_interval seconds. For example, health_check_interval=30 will ensure that a health check is run on any connection that has been idle for 30 or more seconds just before a command is executed on that connection.
>
> If your application is running in an environment that disconnects idle connections after 30 seconds you should set the health_check_interval option to a value less than 30.

But if I try to do that I get a `pylance` error: **No parameter named "health_check_interval"**

```python
from os import getenv
from urllib import parse
import redis

redis_url = getenv("REDISCLOUD_URL", None)
url = parse.urlparse(redis_url)
db = redis.Redis(
    host=url.hostname,
    port=url.port,
    password=url.password,
    health_check_interval=30,
)
```

The code does run without error but I don't really have any confidence that it's doing the right thing... it seems like maybe it's just ignoring the  `health_check_interval` parameter?

But then when I look at the implementation details here: https://github.com/andymccurdy/redis-py/blob/686116d5c740b0ba89e031ca09c5704af5076fd8/redis/client.py#L737 I see that `health_check_interval` does seem like it is a parameter for `__init__()`.

`mypy` also fails, which prevents my codebase CI checks from passing and prevents me from making a release:

```
error: Unexpected keyword argument "health_check_interval" for "Redis"
```

What's going on?

**Comment by andymccurdy** [comment]
Sorry, I don't use `pylance` or `mypy` so I'm not exactly sure what's going on.

**Comment by lexicalunit** [comment]
@andymccurdy this might help: I can click into the definitions on vs code and I see:

`~/.vscode/extensions/ms-python.vscode-pylance-2020.10.0/dist/typeshed-fallback/third_party/2and3/redis/client.pyi`:

```python
class Redis(object):
    RESPONSE_CALLBACKS: Any
    @classmethod
    def from_url(cls, url: Text, db: Optional[int] = ..., **kwargs) -> Redis: ...
    connection_pool: Any
    response_callbacks: Any
    def __init__(
        self,
        host: Text = ...,
        port: int = ...,
        db: int = ...,
        password: Optional[Text] = ...,
        socket_timeout: Optional[float] = ...,
        socket_connect_timeout: Optional[float] = ...,
        socket_keepalive: Optional[bool] = ...,
        socket_keepalive_options: Optional[Mapping[str, Union[int, str]]] = ...,
        connection_pool: Optional[ConnectionPool] = ...,
        unix_socket_path: Optional[Text] = ...,
        encoding: Text = ...,
        encoding_errors: Text = ...,
        charset: Optional[Text] = ...,
        errors: Optional[Text] = ...,
        decode_responses: bool = ...,
        retry_on_timeout: bool = ...,
        ssl: bool = ...,
        ssl_keyfile: Optional[Text] = ...,
        ssl_certfile: Optional[Text] = ...,
        ssl_cert_reqs: Optional[Union[str, int]] = ...,
        ssl_ca_certs: Optional[Text] = ...,
        max_connections: Optional[int] = ...,
    ) -> None: ...
[...]
```

So it looks like the `pyi` file is missing the correct signature/typing information for `Redis.__init__()` for some reason.

**Comment by abrookins** [comment]
@lexicalunit What's happening here is that redis-py is not type-annotated, so mypy falls back to using the third-party type definitions found in the [typeshed project](https://github.com/python/typeshed/blob/master/third_party/2and3/redis/client.pyi#L47). That's what VS Code has taken you to in the example you posted.

The typeshed definitions for third-party libraries are static -- they don't change with the library unless someone opens a PR with new parameters, functions/methods, etc. So in this case, if you want, you can do this -- you'd clone typeshed, add the parameter and give it a Callable annotation (most likely), and submit the PR. New versions of mypy include new versions of typeshed, so you change would then propagate to anyone who uses mypy.

**Comment by lexicalunit** [comment]
PR: https://github.com/python/typeshed/pull/4670
