### ISSUE TITLE
Explain that input is encoded to utf-8 by default

### ISSUE THREAD

**Issue by felipou** [andymccurdy/redis-py#1410]
**Version**: 3.5.3 (and master, it's a documentation issue)

**Platform**: Any (it's a documentation issue)

**Description**: There isn't any text in the README or anywhere (that I could find at least), saying that the default encoding of the user inputs is utf-8. I have had to check the code more than once just to make sure of that (between long intervals of dealing with this lib), I think it's a critical piece of information, since we need to decode the bytes retrieved using the same encoding. I can help, almost created a pull request, but wasn't sure where that information would fit best, or if you have any preferences about how to write this.

**Comment by andymccurdy** [comment]
I think elaborating on this in the README/docs would be great. There's a small section about encoding and the `decode_responses` settings, so additional info would fit well there. Please open a PR and we can work on it. Thanks!

**Comment by felipou** [comment]
Done https://github.com/andymccurdy/redis-py/pull/1417
