### ISSUE TITLE
What is the recommended way to handle ConnectionResetErrors?

### ISSUE THREAD

**Issue by Nick-Morgan** [andymccurdy/redis-py#1415]
I am instantiating my redis connection like this:

```python
import redis
redis_client = redis.Redis(host=HOST, port=PORT, health_check_interval=30)
```

Later on, I have multiple threads use this `redis_client` to read data from redis. Occasionally, I am getting `ConnectionResetErrors`. This repo's [README](https://github.com/andymccurdy/redis-py/blob/master/README.rst) says the following on ConnectionErrors:

> When a connection becomes disconnected, the next command issued on that connection will fail and redis-py will raise a ConnectionError to the caller. This allows each application that uses redis-py to handle errors in a way that's fitting for that specific application. 

So my question is, what is the recommended method for handling these errors? Currently I am doing the following

**Simplified Example:**
```python
while True:
    try:
        redis_client.get(key)
    except ConnectionResetError as e:
        redis_client = redis.Redis(host=HOST, port=PORT, health_check_interval=30)
```

Is this appropriate error handling, or is there a more elegant solution?

**Comment by andymccurdy** [comment]
Hey Nick, a couple questions:

1. What version of redis-py are you using? 
2. I see you refer to `ConnectionResetError` exceptions. Do you mean `ConnectionError` exceptions? redis-py only defines `ConnectionError`, so if you are in fact seeing `ConnectionResetError` exceptions, perhaps they are from another library.
3. Can you post a full traceback with the exception being raised?

**Comment by Nick-Morgan** [comment]
Hey Andy, thanks for the response.

1. Version 3.3.0
2. I believe I was mistaken - It looks like a `ConnectionResetError` is raised, which redis catches before raising a `ConnectionError` - see the traceback below


Note that I am using opentracing, which does patch redis connections
```
'Traceback (most recent call last):
File "/opt/conda/lib/python3.8/site-packages/redis/connection.py", line 671, in read_response
 response = self._parser.read_response()
File "/opt/conda/lib/python3.8/site-packages/redis/connection.py", line 283, in read_response
 response = self._buffer.readline()
File "/opt/conda/lib/python3.8/site-packages/redis/connection.py", line 215, in readline
 self._read_from_socket()
File "/opt/conda/lib/python3.8/site-packages/redis/connection.py", line 159, in _read_from_socket
 data = recv(self._sock, socket_read_size)
File "/opt/conda/lib/python3.8/site-packages/redis/_compat.py", line 58, in recv
 return sock.recv(*args, **kwargs)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/path/to/my/app/redis.py", line 197, in my_personal_function
 result = redis.get(key)
File "/opt/conda/lib/python3.8/site-packages/opentracing_instrumentation/client_hooks/strict_redis.py", line 75, in get
 return ORIG_METHODS['get'](self, name, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/redis/client.py", line 1332, in get
 return self.execute_command('GET', name)
File "/opt/conda/lib/python3.8/site-packages/opentracing_instrumentation/client_hooks/strict_redis.py", line 109, in execute_command
 return ORIG_METHODS['execute_command'](self, cmd, *args, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/redis/client.py", line 839, in execute_command
 return self.parse_response(conn, command_name, **options)
File "/opt/conda/lib/python3.8/site-packages/redis/client.py", line 853, in parse_response
 response = connection.read_response()
File "/opt/conda/lib/python3.8/site-packages/redis/connection.py", line 679, in read_response
 raise ConnectionError("Error while reading from %s:%s : %s" %
"redis.exceptions.ConnectionError: Error while reading from <my database> : (104, 'Connection reset by peer')
"]
```

**Comment by andymccurdy** [comment]
Thanks for the additional info. It shows a couple things:

1. The health check passed. At the time the connection was retrieved from the pool, it was healthy. It became disconnected in the (presumably few) milliseconds between retrieving the connection from the pool and reading the response to your `GET` command.

2. `'Connection reset be peer'` typically means that the other end (in this case, likely the Redis server, though potentially a router/load balancer/etc in between) forcefully killed the connection. This would example why the connection was healthy at first and then suddenly disconnected.

Given both of these things, I'd look at whether your Redis server has the `timeout` config setting enabled. If so, you want to make sure the `health_check_interval` client option is less than the server's `timeout` setting. I generally recommend at least a few seconds lower, e.g. if the server's `timeout` is 30, set `health_check_interval=25`. This will ensure that the health check always fires before the server times the connection out.

If you don't have `timeout` configured, a network device between the client and server could be severing the connection. This too would also likely happen to prevent idle connections. If that's the case, you can solve this by setting the `health_check_interval` to something lower than the idle timeout.

**Comment by andymccurdy** [comment]
I'd also suggest upgrading your redis-py version. At the very least, go up to 3.3.11. 3.3.0 -> 3.3.11 fixes some issues with health checks and SSL connections.

**Comment by Nick-Morgan** [comment]
I appreciate the suggestions. I _do_ have the healthcheck set below the server's `timeout`, but I wonder if the `opentracing` patch is not successfully sending the healthcheck params when creating the connection. 

I will upgrade to `3.3.11`, try to verify that the healthchecks are being sent before the timeouts, and report back.

**Comment by Nick-Morgan** [comment]
Upgrading to `3.3.11` solved the issue. Thanks again for the help.
