### ISSUE TITLE
readme so bad

### ISSUE THREAD

**Issue by JamesLi2013** [andymccurdy/redis-py#1416]
**Version**: lastest
**Platform**: windows 10 

**Description**:  
    import redis
    >>> r = redis.Redis(host='localhost', port=6379, db=0)
    >>> r.set('foo', 'bar')
    True
    >>> r.get('foo')
    b'bar'

    r.get('foo')  return b'bar' .  start with b so puzzle. 
   general  use redis to set text type ,not byte.
   while I first use redis-py r.get  ('foo') ,I fee puzzle. why b start with result?
   use redis cli or java redis client   result is normal.
   I cost ten minute to think and search the question, find the solution:
        https://stackoverflow.com/questions/25745053/about-char-b-prefix-in-python3-4-1-client-connect-to-redis
   I do not want next user cost time again?
   can the doc change like below ?
    r = redis.StrictRedis(host="localhost", port=6379, charset="utf-8", decode_responses=True)

**Comment by andymccurdy** [comment]
There’s actually a lot of use cases for redis-py to store bytes in Redis. Many caching frameworks serialize data at picked objects or json before writing to Redis. Both of these types work with bytes, not strings.

I believe the docs should start with the basic, no-frills options first and then describe how to add on higher level features. The 2 paragraphs immediately following the code example you highlighted talk specifically about `decode_responses`.

I’m all for enhancing this section but I’m happy with the way that it starts. Feel free to open a PR if you like.
