### ISSUE TITLE
XREAD method doesn't read several messages in stream

### ISSUE THREAD

**Issue by artempal** [andymccurdy/redis-py#1429]
**Version**: Redis 6.0.9, redis-py 3.5.3

**Platform**: Ubuntu 20.04.1 LTS

**Description**: 
I use infinite while in receiver.py

```
stream = 'message'
while 1:
    stream_message = redis_connection.xread({stream: '$'}, 5, 0)
    redis_connection.xdel(stream, stream_message[0])
```

And I sent messages in sent.py

```
for data in data_list:
    xadd = redis_stream_message.xadd('message', data)
```

In this case my script receiver.py reads only one message.
In Redis we can see these messages:
![image](https://user-images.githubusercontent.com/23340672/102028438-5dfd6b80-3dbb-11eb-950d-4bf1e7b1d7e7.png)

 To send it for processing I have to use:

`old_messages = redis_connection.xrange(stream)`

But if I use this into infinite while, I get CPU load.
How to use xread correctly in program? 
Thks a lot.

**My workaround**
In sent.py I added sleep. It's works for me.
```
for data in data_list:
    xadd = redis_stream_message.xadd('message', data)
    time.sleep(1)
```

**Comment by andymccurdy** [comment]
Take a look at the Redis docs on the special `$` id: https://redis.io/commands/xread#the-special-codecode-id

You should only use `$` on the first iteration of the loop. Subsequent iterations should use the ID of the last message the previous loop read.

**Comment by artempal** [comment]
@andymccurdy ,I don't use block xread. How can I do this command using redis-py?
` XREAD COUNT 2 STREAMS message $ 0 0`

**Comment by artempal** [comment]
@andymccurdy , I use 0 instead $, it's works for me.
`stream_message = redis_connection.xread({stream: '0'}, None, 0)`

**Comment by andymccurdy** [comment]
Looks like you got it.

**Comment by artempal** [comment]
@andymccurdy Thank you so much!
