### ISSUE TITLE
zadd error

### ISSUE THREAD

**Issue by omides248** [andymccurdy/redis-py#1436]
Hello how fix this error 
ZADD error:
Command # 2 (ZADD queuecaller:901  1608531876.4066405) of pipeline caused error: value is not a valid float

```
if redis.VERSION[0] < 3:
      pipe.zadd(cls.get_namespace(queue_name), time.time(), caller)
else:
      pipe.zadd(cls.get_namespace(queue_name), {time.time(): caller})

```

redis-server --version : Redis server v=5.0.3
pip freeze: redis==3.5.3
python3.8

**Comment by andymccurdy** [comment]
You have the element-name/score reversed on the last line. ZADD takes a dict of element-name keys associated to their score values.

`pipe.zadd(cls.get_namespace(queue_name), {caller: time.time()})`

**Comment by omides248** [comment]
My problem is solved, thank you
