### ISSUE TITLE
Suggestion: Add CLI arguments to Redis.py

### ISSUE THREAD

**Issue by WarpWing** [andymccurdy/redis-py#1440]
Hello! Love Redis.py. I was wondering if there was a way to establish a connection using Redis.py with CLI parameters like --raw for example?

**Comment by andymccurdy** [comment]
redis-py isn't designed to be a CLI tool. I'd suggest using the official `redis-cli` tool for interacting with Redis via a shell.

**Comment by WarpWing** [comment]
Ah noted. Thx for the response and your time ^^
