### ISSUE TITLE
 File "/usr/local/redis/redis-py-master/redis/client.py", line 558     **string_keys_to_dict(      ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by hongwei-lv** [andymccurdy/redis-py#1441]
**Version**: redis-py-master on redis-3.5.3 

**Platform**: python2.7 on centos - 7 

**Description**: when I run the python setup.py install, it happens that File "/usr/local/redis/redis-py-master/redis/client.py", line 558     **string_keys_to_dict( SyntaxError: invalid syntax

**Comment by Grokzen** [comment]
@hongwei-lv Python 2.7 support was removed from master branch a while back and it will not be supported in redis-py >= 4.0.0 releases so that error is expected. See #1318

**Comment by chayim** [comment]
Closing as per @Grokzen comment. Thank you for pointing that out!
