### ISSUE TITLE
host in Redis() when connect to redis docker container

### ISSUE THREAD

**Issue by hraffiest** [andymccurdy/redis-py#1446]
**Version**: redis==3.5.3
**Platform**: Mac OS and Ubuntu in docker containers from python:3.8-slim-buster image
**Description**: Hello guys. This is my first issue. When I dockerize my celery app with redis broker  and ur library in tasks I have a trouble with connection to redis container.
 In my first steps I used env from docker file - `ENV CELERY_BROKER_URL redis://redis:6379/0` in host parameter to create redis object. But error rised -  `redis.exceptions.ConnectionError: Error -2 connecting to redis://redis:6379/0/6379. Name or service not known.`
I used many variants and tried to find similar problems in google. And when I delete protocol 'redis://' and connect only to 'redis' it works fine.
This is object will work with hostname 'redis' for redis container
`r = Redis(host='redis')` 
I wrote this post for guys who have trouble like I. 
P.S. sry for my ugly English)

**Comment by andymccurdy** [comment]
The `CELERY_BROKER_URL` looks OK to me, assuming the `redis` hostname resolves correctly in your Docker setup. Outside of that I don't have much more to offer as this seems more like a Docker or Celery question than a redis-py question.

**Comment by chayim** [comment]
This is a docker issue, not a redis issue. The host named _redis_ doesn't resolve inside of your docker container. You need to either:

1. Add an entry to /etc/hosts in your docker (depending on the docker setup)
2. Ensure you have a [link](https://docs.docker.com/network/links/) configured for your docker containers - which in turn set up DNS.
3. Depending on your need, just connect to the routing IP for your docker network (likely 172.17.0.1), but check.
4. Connect your containers to a [docker network](https://docs.docker.com/engine/reference/commandline/network_connect/) or similar.

Closing as this isn't a redis issue.
