### ISSUE TITLE
BRPOPLPUSH deprecated from Redis 6.2.0.

### ISSUE THREAD

**Issue by cristianourban** [andymccurdy/redis-py#1447]
It seems that BRPOPLPUSH command is considered deprecated from Redis version 6.2.0 and will be replaced by BLMOVE.

- https://redis.io/commands/brpoplpush
- https://redis.io/commands/blmove

Best regards,
Cristiano Urban.

**Comment by chayim** [comment]
@cristianourban This associated PR will implement the new commands and features - this deprecation is a future problem, so for now - that PR will close this bug.
