### ISSUE TITLE
My value is stored as a number. Why does it become a string after being taken out with .get()? 

### ISSUE THREAD

**Issue by jianmaikj** [andymccurdy/redis-py#1450]
**Version**: redis 3.3.5

**Platform**: Python 3.8 on centos 7.5

**Comment by andymccurdy** [comment]
Redis has no concept of types. It stores everything as strings.

redis-py will automatically convert Unicode strings and built in numeric types like ints and floats to byte representations before sending them over the wire to Redis. But there’s no way for redis-py to know how to convert your data back when pulling data out of Redis. That’s your responsibility.
