### ISSUE TITLE
Connecting to multiple nodes

### ISSUE THREAD

**Issue by KarthikRevanuru** [andymccurdy/redis-py#1452]
**Version**: 3.5.3

**Platform**: Python 3.8 on MacOS Catalina 10.15.7

**Description**: How to connect to multiple nodes of a Redis Cluster ?

**Comment by jakob-keller** [comment]
Hello @KarthikRevanuru! Not sure if this is still relevant for you, but support for Redis cluster mode is provided by the [redis-py-cluster client](https://github.com/grokzen/redis-py-cluster).

**Comment by Grokzen** [comment]
@KarthikRevanuru redis-py do not support this feature, my lib that jakob posted a link to is the way to go for a client connecting to a redis-cluster. 
@andymccurdy This is closeable
