### ISSUE TITLE
Read-only client support?

### ISSUE THREAD

**Issue by hotpxl** [andymccurdy/redis-py#1453]
`pyredis.Client` is a read-write client to the Redis server. I currently have a shared server that some clients should only have read access to. Of course I'm not trying to protect against malicious actors, but rather I want to provide a way in case the client code is unknowingly writing to the Redis.

Is there current mechanism in pyredis for me to do this?

**Comment by andymccurdy** [comment]
If you're using Redis server 6.0 or greater, you can use the ACL command to create user accounts w/ limited permissions. redis-py fully supports Redis ACL.

**Comment by chayim** [comment]
Closing as stale.
