### ISSUE TITLE
XTRIM - MINID as in redis 6.2.0

### ISSUE THREAD

**Issue by manigsankar** [andymccurdy/redis-py#1454]
**Version**:3.5

**Platform**: Linux-pycharm

**Description**: XTRIM - eviction based on timestamp IDs using MINID as it is available from redis6.2.0...
will we get upgrades on this?

**Comment by gtrainavicius** [comment]
I just found the xtrim MINID is missing too, but looks like it can be accessed anyway like this:

```
r.execute_command('XTRIM', stream_name, 'MINID', '~', id)
```

**Comment by manigsankar** [comment]
Thanks

**Comment by rhdxmr** [comment]
I need this feature too 👍 
Until it is added to redis-py, I am going to make use of `execute_command`
Thank you
