### ISSUE TITLE
Docker redis got deadlock connecting to redis server.

### ISSUE THREAD

**Issue by Randomneo** [andymccurdy/redis-py#1455]
Python: 3.7, 3.9
redis: 3.5.3 (latest at the moment)
eventlet: 0.30.2 (latest at the moment)

Unable to use redis inside docker image

Please check [this](https://github.com/Randomneo/eventel_docker_error) repo with demonstration.

### short description

Create docker-compose with redis and python (3.7 in example, reproduced with 3.9).
1. Start docker containers.
2. Enter python container.
3. Install eventlet redis via pip.
4. Try to connect interact with redis inside python shell

Got deadlock.

Deadlock passes after some time (5-20 min, varies, reason unknown)

**Comment by chayim** [comment]
@Randomneo Can you provide more information about your environment? I just validated this working.

Please note, your test script does not run eventlet, it merely imports it - meaning at the very least, that's a red herring.

**Comment by chayim** [comment]
Closing unresponsive.
