### ISSUE TITLE
PubSub not reconnecting

### ISSUE THREAD

**Issue by robin-blanchard** [andymccurdy/redis-py#1464]
**Version**: What redis-py and what redis version is the issue happening on?
I am using redis-py 3.5.3 and redis 6.0.10. It might be worth mentionning that my redis instance is inside a docker container.

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
Python 3.6.12 for Ubuntu 18.04.

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue
I am currently developping a wrapper around Redis Pubsub to get a Subscriber instance. I am trying to make it robust to Connection interruptions.
As per the documentation, "In the event of a disconnection such as a network error or timeout, the PubSub object will re-subscribe to all prior channels and patterns when reconnecting". But it doesn't seem to work for me.

Here's a working example of a PubSub process:
```python
>>> import redis
>>> r = redis.Redis(host="172.17.0.2", port=6379)
>>> r.ping()
True
>>> sub = r.pubsub()
>>> sub.subscribe("test")
>>> r.publish("test","test")
1
>>> sub.get_message()
{'type': 'subscribe', 'pattern': None, 'channel': b'test', 'data': 1}
>>> sub.get_message()
{'type': 'message', 'pattern': None, 'channel': b'test', 'data': b'test'}
```

At this point, I shutdown my Redis instance.
`r.ping()` results in a `redis.exceptions.ConnectionError` as expected.

At this point, I restart my Redis instance.
```python
>>> r.ping()
True
>>> r.publish("test","test")
0
>>> sub.get_message()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/robin/.conda/envs/rb-linkvision/lib/python3.6/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/robin/.conda/envs/rb-linkvision/lib/python3.6/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/robin/.conda/envs/rb-linkvision/lib/python3.6/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/robin/.conda/envs/rb-linkvision/lib/python3.6/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/robin/.conda/envs/rb-linkvision/lib/python3.6/site-packages/redis/connection.py", line 231, in can_read
    raise_on_timeout=False)
  File "/home/robin/.conda/envs/rb-linkvision/lib/python3.6/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
```
It seems the Redis connection has correctly been re-enabled, but the PubSub instance doesn't work anymore. I am then currently using a workaround.
```python
>>> sub.reset()
>>> sub.subscribe("test")
>>> sub.get_message()
{'type': 'subscribe', 'pattern': None, 'channel': b'test', 'data': 1}
```

I am happy with my workaround, but the documentation clearly states that this should be handled automatically. Is there something that I don't do correctly ?
Thanks for your answers !

**Comment by andymccurdy** [comment]
`Pubsub.reset()` will clear the Pubsub instance's cache of channel and subscription patterns. So you probably don't want to be calling that unless you're truly looking to close the connection.

Instead, keep calling `Pubsub.get_message()`. The `ConnectionError` should go away once the Redis server is back up and the client can re-establish a connection. You also probably want to be using the `heath_check_interval` option when creating the client connection.

**Comment by robin-blanchard** [comment]
> The ConnectionError should go away once the Redis server is back up and the client can re-establish a connection.
That's what I was hoping for. The client indeed re-established the connection but the PubSub instance never got working again.

> You also probably want to be using the heath_check_interval option when creating the client connection.
That indeed did the trick, thanks a lot !

**Comment by bmerry** [comment]
I've also run into this. The `health_check_interval` helps but is not a great solution, as it requires the health check interval to be set, and it only reconnects once the health check interval has expired even though redis-py knows the connection is problematic. My workaround is to do something like this:

```python
#!/usr/bin/env python3

import time
import redis

r = redis.Redis.from_url('redis://localhost')
r.flushdb()
with r.pubsub() as ps:
    ps.subscribe('foo')
    while True:
        try:
            print(ps.get_message(timeout=1))
        except redis.ConnectionError:
            print('Connect error! Trying to reconnect')
            try:
                ps.connection.disconnect()
                ps.connection.connect()
            except redis.ConnectionError:
                print('Could not reconnect, trying again in 1 second')
                time.sleep(1)
```

Would it be possible for redis-py to do something similar internally when it receives a ConnectionError on a pubsub connection?
