### ISSUE TITLE
Does Redis-py 2.X support py 3.X?

### ISSUE THREAD

**Issue by cat-turner** [andymccurdy/redis-py#1468]
a quick question. we are migrating our py project from 2.X to 3.X. We use this repo, v 2.X. It doesn't say anywhere redis-py 2.X does support or not support py 3. Any ideas? thanks in advance!

**Comment by andymccurdy** [comment]
Python 3 support was added in 2.6.1. See the changelog here: https://github.com/andymccurdy/redis-py/blob/master/CHANGES

I'd highly recommend moving to the latest redis-py version as many bugs have been fixed and features added.
