### ISSUE TITLE
Cannot find ZREVRANGEBYSCORE

### ISSUE THREAD

**Issue by kentgiwinanto** [andymccurdy/redis-py#1469]
**Version**: redis==3.5.3

**Platform**: Ubuntu 20.04 LTS and Windows 10

**Description**: 
Hi, i want to use ZREVRANGEBYSCORE.
Do redis-py module support this command?

Thank you.

**Comment by chayim** [comment]
@kentgiwinanto It's in the latest master and will be in the upcoming release. The 3.5.3 release doe not have support for zrangebyscore.
