### ISSUE TITLE
Redis-py "execute_command()" function splits args on spaces before packing the arguments into the Redis protocol. Splitting on spaces breaks more complex raw queries.

### ISSUE THREAD

**Issue by Gemini420** [andymccurdy/redis-py#1471]
**Version**:

      Redis 5.0.7   Redis-py 3.5.3

**Platform**:

     Ubuntu 20.04  /  Python 3.8.5

**Description**:

The Redis-py "execute_command()" function seems to split args by spaces before packing the series of arguments into the Redis protocol.  [  i.e. Line: 768 in connection.py ]

This breaks more complex raw queries, for example this valid Redisearch Query:

         FT.SEARCH news "@date:[1609477200 1609563600]" NOCONTENT LIMIT 0 9

In this example, the Date clause   "@date:[1609477200 1609563600]"   needs to stay as a single quoted entity.  It should not be split into two parts.

The current pack_command() functionality produces Redis server syntax errors after it is split and packed:

      args = ('FT.SEARCH', 'news', '@date:[1609477200', '1609563600]', 'NOCONTENT', 'LIMIT', 0, 9)

The desired functionality would be:

      args =  ('FT.SEARCH', 'news', '@date:[1609477200 1609563600]', 'NOCONTENT', 'LIMIT', 0, 9)

It appears that "execute_command()" only accepts a string as input (leaving the parsing and packing up to the Redis-py module.)

An easy possible solution might be to also accept a tuple as input to the "execute_command()" method, where the end-user can use a tuple to specify exactly how the args should be parsed before packing ... 

For example:

query = ('FT.SEARCH', 'news', '@date:[1609477200 1609563600]', 'NOCONTENT', 'LIMIT', 0, 9)
result = redis_py.execute_command(query)

**Comment by andymccurdy** [comment]
If that were true, any command that sent a string argument with a space would get messed up, e.g., `r.execute_command('SET', 'foo', 'string with space')` (which clearly works).

Can you provide Python code that demonstrates this happening?

**Comment by Gemini420** [comment]
Yikes, okay.  Thanks for the hint in your reply.

I was implementing this incorrectly, using traditional Redis-cli syntax as a single argument to execute_command()

#  Using Redis CLI syntax worked fine here (single search term, as a single argument string)
result = redis.execute_command("FT.SEARCH news 'Bicycle' NOCONTENT LIMIT 0 9")

# Adding in a more complex term (with a space) produced Redis Server syntax errors
# Debugging this call showed the @date clause being split into multiple parts
result = redis.execute_command("FT.SEARCH news '@date:[1609477200 1609563600]' NOCONTENT LIMIT 0 9")

# What I should have been doing was manually splitting this out into multiple arguments (which works just fine.)
result = redis.execute_command( 'FT.SEARCH', 'news', "'@date:[1609477200 1609563600]'", 'NOCONTENT', 'LIMIT', 0, 9 )

**Comment by andymccurdy** [comment]
Ya. The split on the first argument helps with multi-word command names, e.g. `CONFIG GET` or `CONFIG SET`. Redis wants those as two separate tokens, but often times developers think of both words as the "command" and put that in the first argument.
