### ISSUE TITLE
What happens when a DB is specified for a writing client, but no DB specified on a reading client?

### ISSUE THREAD

**Issue by JamesEarle** [andymccurdy/redis-py#1497]
**Version**: What redis-py and what redis version is the issue happening on?
I am using Azure cache for Redis version 4.0.14

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
Azure

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue
Say you have data you want to store in separate databases. You can use a specific ID to map to which database that should be written to. So you have a bucket for data with database ID of 0, and another bucket for database ID 1, and so on. You can make a client with that ID specified so it writes correctly, but what happens on reading if we can't know that ID ahead of time? Say we query for a piece of data without specifying a bucket, where does the client look?

I have this type of setup right now I'm not 100% positive on why certain things are still being retrieved from Redis when they should report not found and instead the system would reach out to SQL. Any ideas?

**Comment by andymccurdy** [comment]
redis-py defaults to `db=0` if a database isn't specified. Perhaps the key you're looking for is found in db0?

In general, I prefer not to use multiple dbs in Redis. If I really need to separate something, I'll spin up another Redis instance or prefix keys with an app name to distinguish them. In fact, dbs don't work at all in Redis cluster. Note the last paragraph here: https://redis.io/commands/select

**Comment by JamesEarle** [comment]
We're not using clusters so that isn't a problem for me. Basically I want to be able to delete only specific information so we're using databases to load into specific buckets and that gives us the ability to delete only that specific database with `.flushdb()` instead of everything in redis `.flushall()` 

This creates the problem on lookup where we don't know the database ID and the only way to find which database that item is in is to A) list the total number of databases in the configuration, then B) iterate to that number and check each for that item. But now I'm having issues using the Python client with `.config_get()` to show this information

![image](https://user-images.githubusercontent.com/5976499/122978818-c1102200-d34b-11eb-869f-0b1693ca2a17.png)

**Comment by andymccurdy** [comment]
The following works for me. You didn't provide what version of redis-py you're using.

```python
import redis
r = redis.Redis()
r.config_get()
```

**Comment by JamesEarle** [comment]
I am trying to find the version and actually unsure which is correct...

![image](https://user-images.githubusercontent.com/5976499/122983203-983e5b80-d350-11eb-9f17-2a43650e7e25.png)

Below is the entirety of the connection and the error I'm getting 

![image](https://user-images.githubusercontent.com/5976499/122982038-40532500-d34f-11eb-9d5f-88a476683253.png)

**Comment by andymccurdy** [comment]
I'm not sure why the `CONFIG GET *` command wouldn't be working. The Redis server version (4.0.14) is a little old, but it should certainly have that command according to: https://redis.io/commands/config-get

Perhaps Azure disables that command for some reason. From the perspective of redis-py, your code should work.

**Comment by JamesEarle** [comment]
Right, and from the perspective of redis-py it does, it's just a backend thing on this command that seems to fail. I get the same error trying to execute `CONFIG GET *` in the Azure Redis terminal as well

![image](https://user-images.githubusercontent.com/5976499/122989208-65e42c80-d357-11eb-98b4-44fcf64ece8f.png)

**Comment by andymccurdy** [comment]
Yup. This isn't a redis-py bug.

**Comment by JamesEarle** [comment]
Thanks for your help, closing the issue
