### ISSUE TITLE
Migrate to travis-ci.com to run PRs

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [andymccurdy/redis-py#1498]
(template did not apply)

Currently, no PR will be able to run the CI since Travis migrated to travis-ci.com and stopped support for Travis-ci.org completely on June 15. This is how you can migrate to travis-ci.com: https://docs.travis-ci.com/user/migrate/open-source-repository-migration#migrating-a-repository

**Comment by chayim** [comment]
Closing. @andymccurdy moved over to GitHub actions.
