### ISSUE TITLE
redis lmove

### ISSUE THREAD

**Issue by immadevel** [andymccurdy/redis-py#1503]
Hello everybody
I have seen that redis-py library is no longer updated since June of 2020, although since then it was regularly updated on a quarterly basis. Considering this, do you perhaps have any idea of when the next release of that library, including the LMove method, will be distributed?

**Comment by chayim** [comment]
Hi @immadevel there are definitely changes coming in redis-py. I'm hoping to help make them, and issued a PR as a result of your posting here.

If you want to go one way only, [rpoplpush](https://redis.io/commands/rpoplpush) is already implemented, though deprecated in redis 6.2.  Any chance that helps for now?  The same is true with blmove - which replaces [brpoplpush](https://redis.io/commands/brpoplpush).

For the record - I intend to implement both, but I'm hoping this helps in the interim,

**Comment by immadevel** [comment]
Hi chayim, unfortunately I need for a blmove since I need to pop a value from a list to push it at the same time on another list and this has to be atomically. Do you perhaps know when this would be available since I am currently stuck in my developement.
Thanks a lot

**Comment by abrookins** [comment]
You can usually run any Redis command using the `execute_command()` method. Most of the command APIs are wrappers around this method. See Chayim's PR: https://github.com/andymccurdy/redis-py/pull/1504/files#diff-3161b005adfa1f5266a9736bffb5ede9d14e2ab40937cb241bc16ca5647df79dR1736 Does that help?

**Comment by immadevel** [comment]
Thanks abrookins, using execute_command() and invoking LMOVE is working perfectly.
However it seems that the python library is no longer updated since June of the last year, are you considering to post a new release soon?

**Comment by immadevel** [comment]
Any news on whether this will be part of a new release to download?

**Comment by chayim** [comment]
@immadevel There are a few other things we'd like to get in - and then push out a new release. One should be publishable in the near future.
