### ISSUE TITLE
BinanceWithdrawException missing

### ISSUE THREAD

**Issue by immadevel** [andymccurdy/redis-py#1541]
I have just installed the latest release of python-binance 1.0.12, however it seems that the exceptions.py module does no longer include the BinanceWithdrawException class, while the documentation still refers to it: https://readthedocs.org/projects/python-binance/downloads/pdf/latest/ ... any clue?

**Version**: What redis-py and what redis version is the issue happening on?
1.0.12

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
Python version: 3.8 on Wiindows 10 Enterprise

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue
ImportError: cannot import name 'BinanceWithdrawException' from 'binance.exceptions'

**Comment by chayim** [comment]
@immadevel Everything above refers to Binance. If you can relate this back to redis-py, please do, and we'll reopen!
