### ISSUE TITLE
xpending_range does not pass consumername in command any more

### ISSUE THREAD

**Issue by coleifer** [andymccurdy/redis-py#1592]
**Version**: What redis-py and what redis version is the issue happening on? latest HEAD - 9419f1d56beff5b350c87785cc57f2431fe85cbb

**Platform**: python 3 on linux

**Description**: `xpending_range()` accepts an optional `consumername` argument but does not actually use it.

Here is xpending doc, consumer is last parameter: https://redis.io/commands/XPENDING

The redis-py `xpending_range()` accepts the `consumername` param but does not actually use it:

https://github.com/andymccurdy/redis-py/blob/9419f1d56beff5b350c87785cc57f2431fe85cbb/redis/commands.py#L2037-L2076

In case it's not obvious, then here is an example invocation and the corresponding REDIS command (via MONITOR):

```python
>>> db.xpending_range(key, group, start, stop, count, consumer)  # consumer = 'ts1'
```

Redis output (consumer is missing):

```
+1633567393.619941 [15 127.0.0.1:44492] "XPENDING" "sa" "cgabc" "-" "+" "1000"
```

**Comment by chayim** [comment]
@AvitalFineRedis Please have a look.
