### ISSUE TITLE
redis.commands module missing in pypi release 4.0.0b2

### ISSUE THREAD

**Issue by guigarfr** [andymccurdy/redis-py#1645]
`client.py` is trying to import from the `redis.commands` module, and this import raises `ModuleNotFoundError: No module named 'redis.commands'`

```
.../site-packages/redis/client.py:9: in <module>
    from redis.commands import CoreCommands, RedisModuleCommands, list_or_args
    E   ModuleNotFoundError: No module named 'redis.commands'
```

**Version**: 4.0.0b2

**Platform**: Ubuntu

**Description**:

I'm getting the error `ModuleNotFoundError: No module named 'redis.commands'` after installing redis version 4.0.0b2

According to github, the tag 4.0.0b2 has a [module named commands](https://github.com/redis/redis-py/blob/v4.0.0b2/redis/commands/__init__.py).
When downloading the [tar.gz from pypi](https://files.pythonhosted.org/packages/55/bc/f482cb78c9dae1561d45a3532de34cd15f7cbebc8777146a60d185830d26/redis-4.0.0b2.tar.gz), the module is not there.

**Comment by ruslaniv** [comment]
It is marked as closed, but I'm still getting exactly the same error:

```
pip install "redis[hiredis]"
Requirement already satisfied: redis[hiredis] in /home/ruslan/.cache/pypoetry/virtualenvs/datascience-5HzBPYEV-py3.11/lib/python3.11/site-packages (4.6.0)
Requirement already satisfied: hiredis>=1.0.0 in /home/ruslan/.cache/pypoetry/virtualenvs/datascience-5HzBPYEV-py3.11/lib/python3.11/site-packages (from redis[hiredis]) (2.2.3)
```
![image](https://github.com/redis/redis-py/assets/7631314/072b07c6-8b6e-490b-88e8-557428d568dc)

**Comment by ruslaniv** [comment]
Ok, I have an extension that syncs `.ipynb` to `.py` files. 
It looks like that `py` file gets executed too when I do the import. But why would redis fail on the second import of the same objects? It should not even import them, since they already have been imported.
