### ISSUE TITLE
consistent hashing

### ISSUE THREAD

**Issue by emre** [andymccurdy/redis-py#183]
is there a plan to implement consistent hashing/sharding based on keys to the library?

**Comment by Grokzen** [comment]
@andymccurdy This issue is over 5+ years old now, and i would argue that this could be closed because we do now have a cluster sharding solution available that would superseed any client side sharding and logic solution.

**Comment by andymccurdy** [comment]
Agreed, cluster provides a better solution. This library will not support client side sharding.
