### ISSUE TITLE
'module' object has no attribute 'StrictRedis'

### ISSUE THREAD

**Issue by samrat** [andymccurdy/redis-py#188]
When I tried 

```
>>> import redis
>>> r = redis.StrictRedis(host='localhost', port=6379, db=0)
```

as instructed in the readme file, I get this error:

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'StrictRedis'. 

```
```

**Comment by saso008** [comment]
hi 
i use ipython3 and used Redis instead of StrictRedis and it not worked. and i change the file name redis but dose't work in ipython3.
can me get suggest for this problem?
