### ISSUE TITLE
Is there a way to fuzziness search and precision search at the same time?

### ISSUE THREAD

**Issue by evandeng2009** [andymccurdy/redis-py#2769]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: What redis-py and what redis version is the issue happening on?

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)

**Description**: 
I have a field article_title for fuzziness search, and author_name for precision matching, for example, to find some articles of a specified author.  Is there a way to fuzziness search and precision search at the same time?

**Comment by evandeng2009** [comment]
More description here:

Search the articles of a unique user whose name is Mike, age is 18 , and country is US, by a keyword. 

Is this possible to set such a Query or some composite one?

**Comment by SoulPancake** [comment]
@evandeng2009 Seems possible.
To conduct a fuzzy search combined with precision filters, you will first need to create an index with the fields you want to search on. In your case, you would need fields for article_content, author_name, author_age, and author_country.
Also I think currently fuzzy searches via RedisSearch is just with respect to Levenstein distance.

**Comment by evandeng2009** [comment]
I checked class AggregateRequest and Query which are used for search and ft.aggregate, seems can't satisfy my requests:
1. 5 content fields to be searched on, one or all of them for each search(fuzzy search), coz they may have some same words and I need specify one or all of theose fields.
2. Meanwhile, some precise search on more than 1 field like age and name.
3. And sort by 2 other fields, asc for one and another desc, like post_time

Yes I created an index having all those fields, Query has limit_fields(*fields) works for request 1, but does not for request 2 or request 3. So I have to do it on my own, and I need the exact doc num of search, this has poor performance when data set is too big.

Then I see ft.aggregate, it works for request 2 and request 3, but not for request 1. 

I don't see a full example of ft.search and ft.aggregate in redis-py doc or source code, not sure I don't understand correctly or it's acctually impossible for my case.

**Comment by evandeng2009** [comment]
I created another issue which is more detailed. So close this issue here.

**Comment by evandeng2009** [comment]
@SoulPancake , please take a look at my solution there https://github.com/redis/redis-py/issues/2777 if you need.

**Comment by SoulPancake** [comment]
Thanks @evandeng2009 Good job there!
