### ISSUE TITLE
Support unix domain sockets in from_url

### ISSUE THREAD

**Issue by sprat** [andymccurdy/redis-py#278]
Hello,

I think the `from_url` function should support a way to pass an unix domain socket instead of TCP host/port. However, I'm not sure which option would be the best:
file:///path/to/redis.sock
or:
redis:///path/to/redis.sock

Keep up the good work,
Sylvain

**Comment by AngusP** [comment]
UNIX sockets have been supported for a long time, I think since at least a378cdb so maybe @andymccurdy or @sprat could close this issue?

**Comment by Grokzen** [comment]
@andymccurdy Bump on closing this based on previous msg from AngusP

**Comment by sprat** [comment]
Agreed, I suppose it is solved now, so I am closing this issue.
