### ISSUE TITLE
Thoughts on handling setting/getting of 'None' differently?

### ISSUE THREAD

**Issue by yeago** [andymccurdy/redis-py#321]
Currently, conn.set('x', None) returns the string 'None' when using get(). I think use-cases relying on this behavior are probably pretty obscure.

I understand setting None is a pointless practice, but sometimes tracking down the setter can be difficult to detect. I can submit pull requests if this is a favorable direction.

**Comment by andymccurdy** [comment]
Starting with redis-py 3.0, `None` is no longer accepted as input for keys or values. Same for `True` or `False`. Users will need to cast these values explicitly before sending them to redis-py.
