### ISSUE TITLE
Missing Documentation of ZCOUNT

### ISSUE THREAD

**Issue by cjhanks** [andymccurdy/redis-py#339]
From Here:
http://redis-py.readthedocs.org/en/latest/

Functionality of zcount is not included, however it appears in the tests and is included in functionality.  I would fix it myself, but I am unsure where (if anywhere) it is written in code.

**Comment by thestick613** [comment]
still missing!
https://redis-py.readthedocs.io/en/latest/search.html?q=zcount&check_keywords=yes&area=default
