### ISSUE TITLE
Feature Request: Option to pickle/unpickle data

### ISSUE THREAD

**Issue by jacinda** [andymccurdy/redis-py#348]
Something like this built in as an option for set/get (Similar behavior to pylibmc):

def set_value(redis, key, value):
    redis.set(key, pickle.dumps(value))

def get_value(redis, key):
    pickled_value = redis.get(key)
    if pickled_value is None:
        return None
    return pickle.loads(pickled_value)

http://stackoverflow.com/questions/12870772/get-object-from-redis-without-eval

I'll submit a pull request for this if I get some time.

**Comment by andymccurdy** [comment]
redis-py will not pickle or unpickle values directly. This is something that should be happening in user code.
