### ISSUE TITLE
Cluster support

### ISSUE THREAD

**Issue by desprezj** [andymccurdy/redis-py#380]
Hello, 
   Is it scheduled soon to start including some cluster support (unstable branch redis) in order to start gaining insight and feedback on changes to be done??

Using a branch like this one: That already provides some support.
https://github.com/Grokzen/redis-py-cluster

thank you

**Comment by Grokzen** [comment]
@andymccurdy This issue can be closed in favor for #603

**Comment by desprezj** [comment]
Closing since treated in #603
