### ISSUE TITLE
redis-py rpush method returns list as a string

### ISSUE THREAD

**Issue by shashank9487** [andymccurdy/redis-py#382]
rpush method takes values as *argument in its method, when i try to save a huge list in redis around 2 lac items, it gives me string result in lrange operation. I tried json.dumps before insert data in redis and for fetching use json.loads but not working.

How to return list from rpush method, while on other hand php redis work properly and return proper list.

**Comment by kamronbek29** [comment]
i have some questions to you

**Comment by kamronbek29** [comment]
i want to set multiple values to one key, and also want to get them, for example redis.get(smth[1]), smth like this, how to do it? Could you help me plz?

**Comment by andymccurdy** [comment]
@kamronbek29 You should look at Redis hashes or sets, whichever fits your use case better. If you're looking for further help, I'd suggest asking on the Redis mailing list.
