### ISSUE TITLE
SETNX with TTL

### ISSUE THREAD

**Issue by vskr** [andymccurdy/redis-py#387]
Is it possible to do a atomic SETNX with TTL.  I use redis as distributed key value store, and am looking to simulate lock -> update -> release pattern on redis.

Since SETNX doesn't take expiration time, if the thread which obtains lock dies subsequent SETNX's are always false

**Comment by kingname** [comment]
> If you're using Redis server 2.6.12 or greater and redis-py 2.7.4 or greater, you can pass additional arguments to the `SET` command.
> 
> ```python
> r = redis.StrictRedis(...)
> r.set('my-key', 'my-value', nx=True, ex=10)  # 10 second expiration, note you can also use `px` for millisecond resolution
> ```
> 
> You could also do this with LUA scripting or with a pipeline+watch command.

you can not use `r.set` with `nx=True` as the replacement of `r.setnx`，because `r.setnx` will return `True/False` to show if this key exists already, but `r.set` always return `None`.

**Comment by patrick91** [comment]
@kingname I know this is an old issue, but this seems to be working as expected now :D
