### ISSUE TITLE
Fix ordering of zincrby args

### ISSUE THREAD

**Issue by PaulMcMillan** [andymccurdy/redis-py#402]
The order of arguments for zincrby in StrictRedis don't match the docs. I'd provide a patch but I'm not sure what the correct backwards compatibilty choice is.

http://redis.io/commands/zincrby
https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L1266

**Comment by Grokzen** [comment]
@andymccurdy This was fixed in 3.0 release, reference https://github.com/andymccurdy/redis-py/commit/a750c7946d41862a38955c35b6928f098911c406 and the other mentioned issue inside that commit

**Comment by andymccurdy** [comment]
thanks, closing.
