### ISSUE TITLE
__init__() got an unexpected keyword argument 'hosts'

### ISSUE THREAD

**Issue by arisolt** [andymccurdy/redis-py#417]
I have the following code:

```
 import redis

 pool = redis.ConnectionPool(hosts='localhost', port=6379, db=0)
 r = redis.Redis(connection_pool=pool)

 reply = r.hmget("1000","link","text")
```

and it gives the following error:

```
 __init__() got an unexpected keyword argument 'hosts'
```

What could be the cause? I should mention ConnectionPool stuff is copy/pasted from the github tutorial.

**Comment by lordkadoz765** [comment]
Quick fix:

in your settings.py file or your config file paste this and leave the area commented 

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
        # 'CONFIG': {
        #     'hosts': [('127.0.0.1', 6379)],
        # }
    }
}

**Comment by visa15cs** [comment]
Thanks lordkadoz765 , it worked!
