### ISSUE TITLE
Problem with hash get/set

### ISSUE THREAD

**Issue by tommiv** [andymccurdy/redis-py#463]
Hi there. I tried to set hash and then restore it, but, every piece of restored data looks binary encoded. Here is listing:

Python 3.3.0 (default, Dec 19 2013, 23:07:15)
[GCC 4.6.3] on linux

> > > import redis
> > > r = redis.StrictRedis(password = "fakepass")
> > > mydict = {}
> > > mydict["test"] = "test11"
> > > print(mydict)
> > > {'test': 'test11'}
> > > r.hmset("test:key", mydict)
> > > True
> > > stored = r.hgetall("test:key")
> > > print(stored)
> > > {b'test': b'test11'}

In result, stored.get("test") returns None due to b'test' key.
I checked with redis-cli and stored data looks ok:
redis 127.0.0.1:6379> hgetall test:key
1) "test"
2) "test11"

redis-py version is 2.9.1, installed via pip, redis-server version is 2.2.12

**Comment by bitdivision** [comment]
This seems to come up in google for this issue so I'm going to add an extra note on this:

If you are using `connection_pool` in your `StrictRedis` constructor then you need to pass the `decode_responses=True` to the `ConnectionPool` to get it to work:

```
# This won't work
c = redis.ConnectionPool(**redis_settings)
r = redis.StrictRedis(connection_pool=c, decode_responses=True)

# This will:
c = redis.ConnectionPool(**redis_settings, decode_responses=True)
r = redis.StrictRedis(connection_pool=c)
```
