### ISSUE TITLE
Update connection polling to use something other than select.select()

### ISSUE THREAD

**Issue by andymccurdy** [andymccurdy/redis-py#486]
As @ntki points out in #419, `select.select()` can crash if the file description is >1024. Switch to a more modern polling system that's compatible with all OS's.

**Comment by Seteeri** [comment]
Python 3.4 introduces the "selectors" module; it'll choose the most efficient implementation available on the current platform.

Docs:
https://docs.python.org/3/library/selectors.html#module-selectors
Source:
https://github.com/python/cpython/blob/master/Lib/selectors.py

**Comment by schlitzered** [comment]
there is basically no need to use select, or any other polling method at all.

simply use socket.setTimeout($TIMEOUT) on the redis socket and catch socket.timeout while trying to read or write from the socket.

i have implemented a python 3 only redis client that is doing this, and there is also redis cluster support build in https://github.com/schlitzered/pyredis

**Comment by andymccurdy** [comment]
3.2.0 adds support for additional polling strategies and will use the best one for your system.
