### ISSUE TITLE
Pass connection info through environment to test suite

### ISSUE THREAD

**Issue by jbergstroem** [andymccurdy/redis-py#503]
The test suite assumes that a redis is running on localhost:6379. This is not optimal for a few reasons, the most important one being that it might actually destroy/mess with vital data.

One way to avoid this would be to pass connection information through the environment, or use a config.py within the tests folder for passing the info to the test cases.

**Comment by gyermolenko** [comment]
It would be convenient (at least for local development) to be able to run tests against particular Redis server, to compare test runs from two servers.
I.e. start server from docker as `docker run --rm -p 6301:6379 redis:5.0.0` and run  
`pytest --redis-url=redis://localhost:6301 tests`

I can create a PR to discuss this idea further.

**Comment by andymccurdy** [comment]
We now have a way to specify a connection string with the `--redis-url` option. That seems to satisfy the needs of this issue.
