### ISSUE TITLE
New connection created everytime

### ISSUE THREAD

**Issue by JohnSundarraj** [andymccurdy/redis-py#504]
Hi there, i'm trying to use RQ worker to execute background jobs in my Torando App. I'm successful sofar, but one weird thing i noticed. Redis client creates a new connection everytime a job gets executed by the RQ worker. I found this issue by using the command `redis-cli info | grep 'connection'`. Everytime i check this command after a job gets executed, its incremented. To solve this problem i tried various implementations, but nothing worked. Below it he wrapper class i've created. It seems to be a bug in redis client, if i'm not wrong...Need help on this issue. Thanks in advance.

``` python
# Redis controller.
class Redis(object):
  __Instance = None

  def __init__(self):
    if self.__class__.__Instance:
      return
    else:
      self.__class__.__Instance = self
    self.Conf = DBConf()['Redis']
    print "NEW REDIS"
    self.Engine = redis.Redis(connection_pool=redis.ConnectionPool(host=self.Conf['Host'],port=self.Conf['Port'],max_connections=10))

  def __new__(self):
    if self.__Instance:
      return self.__Instance
    else:
      return object.__new__(self)
```

**Comment by jeffwidman** [comment]
Looks like this issue should be closed.

**Comment by JohnSundarraj** [comment]
@viveksinghtt can you please provide the code snippet, so that we can suggest something.

**Comment by andymccurdy** [comment]
3.2.0 now behaves well with multiprocessing and forked connections.
