### ISSUE TITLE
client doesn't pass the keys to the connection pool

### ISSUE THREAD

**Issue by dvirsky** [andymccurdy/redis-py#507]
The connection pool's API is:

``` py
def get_connection(self, command_name, *keys, **options):
```

But the client never passes `*keys` to the connection pool. Thus, when I wanted to create a sharded connection pool, I wasn't able to do it without inheriting from the client class and passing it. I only passed the first key:

``` py
def execute_command(self, *args, **options):

        command_name = args[0]
        key = args[1] if len(args) >1 else ''

        connection = self.connection_pool.get_connection(command_name, key, **options)
```

I'm not sure this is always correct - please advise. If not passing the key is intentional I will continue with my inherited client, if not I'll gladly provide a patch for this.

**Comment by dvirsky** [comment]
Hey Andy. I just remembered this old thing :) 
Is it still relevant? Or did you implement it yourself somehow since then?

**Comment by Grokzen** [comment]
@andymccurdy Ain't this another issue where the cluster solution would take presidence over a hashring or non clustered solution as was talked in the issue above? If the cluster solution would, then this could probably be closed as no longer valid.

**Comment by andymccurdy** [comment]
Agreed, cluster solves this much better.
