### ISSUE TITLE
redis.exceptions.ResponseError: wrong number of arguments for 'del' command

### ISSUE THREAD

**Issue by ruajhonatan** [andymccurdy/redis-py#513]
I'm trying to integrate "sorl-thumbnail" with "redis" and this is the error that throws me, someone can guide me with this difficulty. 

redis.exceptions.ResponseError: wrong number of arguments for 'del' command

Thank you ..

**Comment by Grokzen** [comment]
@andymccurdy Stale and old issue. Not enough information to reproduce bug and no additional information and  update in 4+ years now.
