### ISSUE TITLE
ConnectionError: No connection available in 2.10.1

### ISSUE THREAD

**Issue by tapanpandita** [andymccurdy/redis-py#516]
I have been using the BlockingConnectionPool with redis-py v2.9.1 and hiredis v0.1.2 and everything worked as expected. I upgraded to v2.10.1 and v0.1.4 respectively and I started seeing this error:

```
  File "/app/.heroku/python/lib/python2.7/site-packages/redis/client.py", line 1816, in hmset
    return self.execute_command('HMSET', name, *items)

  File "/app/.heroku/python/lib/python2.7/site-packages/redis/client.py", line 526, in execute_command
    connection = pool.get_connection(command_name, **options)

  File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 935, in get_connection
    raise ConnectionError("No connection available.")

ConnectionError: No connection available.
```

It's definitely not waiting for the timeout period before raising this error and there are definitely connections available.
I haven't changed anything in my code. This is how I instantiate the connection pool:

``` python
REDIS_CONNECTION_POOL = redis.BlockingConnectionPool(
    host=REDIS_HOSTNAME,
    port=REDIS_PORT,
    db=0,
    password=REDIS_PASSWORD,
    socket_timeout=15,
    max_connections=3,
    timeout=25,
)
```

Any idea why this is happening?

**Comment by gjcarneiro** [comment]
I get this issue as well with 2.10.3, but haven't tried 2.10.5 yet.  Any idea if 2.10.5 should fix this?
