### ISSUE TITLE
docs/make html

### ISSUE THREAD

**Issue by heysion** [andymccurdy/redis-py#527]
make html is nothing ?

**Comment by pedromorgan** [comment]
I'm a bit confused myself..

This
https://github.com/wolph/redis-py
Is the source for
https://redis-py.readthedocs.org/en/latest/

Now I got a patch.. to make it more friendly..
But which one do I target../patch agains

Assume this is "Definate upstream" and master source of the code ?

And the docs are outta date..
Can someoen get in touch with
https://github.com/wolph (issues disabled)
and make the docs point to this place instead ??

am cofused
