### ISSUE TITLE
python redis error

### ISSUE THREAD

**Issue by elastic10** [andymccurdy/redis-py#533]
> > > import redis
> > > r = redis.StrictRedis(host='localhost', port=6379, db=0)

as instructed in the readme file, I get this error:

```Traceback (most recent call last):
File "", line 1, in
AttributeError: 'module' object has no attribute 'StrictRedis'.
just begining redis, i have this error, do have please any idea?

**Comment by darksmoke** [comment]
I have a problem

Traceback (most recent call last):
  File "/etc/zabbix/externalscripts/zbx_redis_stats.py", line 95, in <module>
    client = redis.StrictRedis(host=host, port=redis_port, password=redis_pass)
AttributeError: 'module' object has no attribute 'StrictRedis'

How you solved it?

**Comment by andymccurdy** [comment]
@darksmoke You likely have a file named `redis.py` somewhere in your code base on the Python path. You'll need to rename it.

**Comment by darksmoke** [comment]
find / -name redis.py -type f
Have not found =(

**Comment by andymccurdy** [comment]
@darksmoke the next thing I'd try is this:

import redis
print redis

That should show you where the redis module is being imported from.

**Comment by onebraveman** [comment]
I just met the same error. After I found the redis overwrite the redis package file, the result exists.
So, I just restart Idle and clear the error.

**Comment by noamgr** [comment]
so i find this doc ... and i want to add 
if you call you python scrip "redis.py" the lib will not work ... 
can understand why but i change my script name from redis.py to redis-test.py 
and i can see all the function and its work ...

**Comment by andymccurdy** [comment]
When you call `import redis`, Python iterates over `sys.path` looking for a module named `redis`. Often your local code base is at the top of that list before your installed 3rd party modules where pip or easy_install place packages that get installed.

**Comment by perrygeo** [comment]
This is the top hit for the search term so it might be helpful to add:

```
from __future__ import absolute_import
```

Will fix this problem on Python 2.7. See https://www.python.org/dev/peps/pep-0328/#rationale-for-absolute-imports

**Comment by gnubyte** [comment]
For the fool having an issue with this like I did in the future:

change
`conn = Redis.StrictRedis`

to

`conn = redis.StrictRedis`

**Comment by a2944239990** [comment]
module 'redis' has no attribute 'StrictRedis'

**Comment by onceone** [comment]
great！change the name.it`s OK

**Comment by ansh1221** [comment]
Hi @andymccurdy ,

While testing one of my python files using cli - nosetests -m filename
I get the following error:

![image](https://user-images.githubusercontent.com/39158645/58461449-592b8500-814d-11e9-96a1-517c873ee333.png)

**Comment by andymccurdy** [comment]
Same answer as above. Python is looking for the ConnectionPool object within your redis.py module. Either rename that file to something else or use `from __future__ import absolute_import` at the top of your redis.py module.

**Comment by ansh1221** [comment]
Hi @andymccurdy still the same error. "from __future__ import absolute_import" is already present in the file redis.py. 
I have actually set PYTHONPATH also, but still it doesn't works. Can you please guide/suggest me for the same.

**Comment by SumathiGit** [comment]
> Ah, you have a file named `redis.py` somewhere. Python's import will import your redis.py module instead of a package named `redis`. You need to rename the redis.py file to something else.

well i noticed that my file name is redis.py and that causes the problem ! Thankyou
