### ISSUE TITLE
Redis-py should be able to accept and return file-like objects

### ISSUE THREAD

**Issue by pjrobertson** [andymccurdy/redis-py#535]
Take the example that I have of storing a gzipped string in redis. If I have an uncompressed string, I don't want to have to store the compressed string in memory. It would be preferable to pipe it as a BytesIO object straight to redis

``` python
# uncompressed string
mystring = "this is uncompressed"

# compress the string (or perhaps you already have a gzip compressed string/bytes, which you received from a URL respone...
uncompressed = BytesIO(mystring)
compressed = BytesIO()
with gzip.open(compressed, 'wb') as c:
     w.writelines(uncompressed)

# for some strange reason this sets repr(compressed) as the value - what is the logic behind taking a repr() of val?
redis.set('compressed_data', compressed)


# now to uncompress:
# ... later on in the code

with gzip.open(redis.get('compressed_data'), 'rb') as c:
       uncompressed = BytesIO(c.readlines())
```

This of course doesn't work, and you have to pass a string to the redis connection. It should really accept file-like objects, so that you don't have to load the objects into memory.

I my case, I am storing an XML string in redis. When setting/getting I am converting from/to an `ElementTree` element. With the current way redis.py stands, I have to do something as follows

``` python
xmlString = redis.get('xmlstring')
element = ElementTree.fromstring(xmlString)
```

This is potentially a huge was of memory. What if xmlString is a 500kb string? I must load it into memory, pass it to ElementTree and _then_ create the element (which adds to the memory again)

**Comment by andymccurdy** [comment]
I don't believe redis-py will support file-like object access anytime soon. Sorry.
