### ISSUE TITLE
Add support for RedLock

### ISSUE THREAD

**Issue by dallagi** [andymccurdy/redis-py#540]
RedLock is an attempt to provide a canonical way to implement distributed locks with Redis.
The algorithm was first announced on antirez's blog [0] and it's described on the Redis online documentation [1]. It has been already implemented in several languages, including python [2].
I'm not sure how does RedLock compare to the locking system implemented in redis-py, but I think it would be worth considering to implement RedLock in redis-py.

[0] http://antirez.com/news/77
[1] http://redis.io/topics/distlock
[2] https://github.com/SPSCommerce/redlock-py

**Comment by jhorman** [comment]
For reference, there is another redlock implementation out there now.

https://github.com/glasslion/redlock

**Comment by imomaliev** [comment]
+1 for this feature
