### ISSUE TITLE
PyPI page is not rendering README.rst as reST

### ISSUE THREAD

**Issue by msabramo** [andymccurdy/redis-py#548]
https://pypi.python.org/pypi/redis

The raw reST is shown. Probably, there is some small error in the markup -- the PyPI RST parser is very unforgiving.

It may or may not have to do with the issue that I fixed with PR #547 -- you might try merging that and then doing `python setup.py register` and maybe it might fix it.

**Comment by andymccurdy** [comment]
Thanks! Your PR fixed the issue.
