### ISSUE TITLE
Able to hit 'unknown command 'EVALSHA'' when using a lualock on redis 2.2

### ISSUE THREAD

**Issue by harlowja** [andymccurdy/redis-py#550]
It appears that redis 2.2 (when used) will correctly pass the lualock code (which it doesn't seem like it should) and then it will blowup with errors such as 'unknown command 'EVALSHA''.

An example log we hit that shows this (on ubuntu precise which has redis 2.2):

http://logs.openstack.org/42/131442/1/check/gate-tooz-python33/e4560c5/console.html

**Comment by rouge8** [comment]
Likely broken by this commit: https://github.com/andymccurdy/redis-py/commit/0340f1b6609b3222dfc15750f83279899fc0616d
