### ISSUE TITLE
about pool, if raise ConnectionError ,  if connection is None cant be run.

### ISSUE THREAD

**Issue by ydf** [andymccurdy/redis-py#553]
https://github.com/andymccurdy/redis-py/blob/a8e9e19d6fab065eee382942baec79d5f3b56bb5/redis/connection.py

in line 987-996

 try:
    connection = self.pool.get(block=True, timeout=self.timeout)
except Empty:
    raise ConnectionError("No connection available.")   
if connection is None:
       connection = self.make_connection()
return connection

**Comment by andymccurdy** [comment]
The initial pool is created with N `None` slots where N is the max_connections the pool. None is a valid value to pull out of the pool which is an indicator to create the new connection.
