### ISSUE TITLE
Connection leak when no explicit cleanup of pubsub object

### ISSUE THREAD

**Issue by yoav-steinberg** [andymccurdy/redis-py#555]
Since the registation of "on_connect" callbacks were added to `PubSub`, pubsub objects aren't freed when they loose all app references (because the callback is still referened from within the connection pool's connection object).
Try this:

``` python
r = redis.Redis()
r.ping()
for i in range(100):
    s = r.pubsub()
    s.subscribe('chn')
```

I'd expect the connection used for `s` to be reused, but instead 100 subscribe connections are created and never freed (even if we move to a scope where `s` isn't defined anymore).

I undestand that for "resubscribe" feature we need this on_connect callback. So maybe there isn't a perfect solution for this. But in such a case we should:
- Document that s needs to be explicitly cleaned up (via a call to .close())
- Have the `PubSub` class implement the python context manager protocol so we can do something like:

``` python
for i in range(100):
    with r.pubsub() as s:
        s.subscribe('chn')
```

**Comment by MattFisher** [comment]
I don't know if it's the same issue, but Celery leaks connections when using redis as its broker: https://github.com/celery/celery/issues/4465
