### ISSUE TITLE
pipeline.hget() returns StrictPipeline, NOT value of key

### ISSUE THREAD

**Issue by pothiers** [andymccurdy/redis-py#563]
I'm unable to use hget on a pipeline to get an actual key value:

    red = redis.StrictRedis()
    pl = red.pipeline()

    ercnt = pl.hget(ecnt,rid)
    logging.debug('Got error on action. ercnt="{}"'.format(ercnt))
    # => DEBUG Got error on action.      
    ercnt="StrictPipeline<ConnectionPool<Connection<host=localhost,port=6379,db=0>>>

If I replace above get with:
`errcnt=red.hget(ecnt,rid)`
I get a value.  But I worry that its an unprotected one.

**Comment by puncha** [comment]
Great! I was really confused that why the conditional checks can be used in Redis pipeline. Thanks for your explain on special mode.
