### ISSUE TITLE
incrby parameter order inconsistent

### ISSUE THREAD

**Issue by CBenni** [andymccurdy/redis-py#571]
I encountered this:
`r.zincrby("key",5,"member")`
Gives an exception, eventhough this is the same order of parameters as redis has.
`r.zincrby("key","member",5)`
works however.

Comparison: `r.zadd("key",5,"member")` works the way it is supposed to.

**Comment by stevenh** [comment]
Any news on this, coming from redis or other languages / libs like redigo this is a major gotcha and the long its left to fester the worse it gets.

**Comment by andymccurdy** [comment]
Fixed in redis-py 3.0
