### ISSUE TITLE
Url encoding passwords with invalid url characters causes connection failure

### ISSUE THREAD

**Issue by lBowlin** [andymccurdy/redis-py#579]
Cloud services that required passwords such as "iAITMl7lD127c/VZEl0OZl8qviaXHIoKekaJjP1J1HI=" can contain a variety of characters including forward slashes which are invalid in a url string.

When entered in the correct format "rediss://:password@hostname:port" the slash cause in improper breakage of the netloc  during urlparse. Encoding the forward slash into a valid url safe character (%2F) fixes the urlparse issue, but is never decoded after parsing prior to assignment as the password.

This is particularly an issue with Azure Redis Caches which have keys that may contain such values. I think a simple url decode would fix the issue, but have not tested this.

**Comment by yozik04** [comment]
Also using Azure Redis Cache. Have same problems.

**Comment by andymccurdy** [comment]
Hey guys, this issue was fixed a while back here: https://github.com/andymccurdy/redis-py/pull/586

**Comment by ddennis** [comment]
Thank you for documenting this. Have the same problem using node
