### ISSUE TITLE
brpop raise redis.exceptions.TimeoutError if socket_timeout is less than brpop timeout

### ISSUE THREAD

**Issue by hyt-hz** [andymccurdy/redis-py#583]
I'm using redis as a queue, and the StrictRedis client is create with socket_timeout set to 5, When I 'brpop' to wait for some message, it always raise redis.exceptions.TimeoutError after 5 seconds.

I am aware of some workarounds, but all feels wrong to me:
1. do not set socket_timeout
2. set timeout on brpop smaller than socket_timeout
3. catch TimeoutError for brpop, and start brpop again (will this cause current connection be marked as bad and thrown away?)
4. have another StrictRedis client with no socket_timeout, dedicated to brpop operation only

So is it possible for the client to temporary overwrite the socket read timeout for the connection which will be used for block operation like brpop. Or there is already some other workaround I am not aware of.

Thanks

Here is the example:

```python
>>> import redis
>>> r = redis.StrictRedis(socket_connect_timeout=5, socket_timeout=5)
>>> r.brpop('abcd', timeout=100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/redis/client.py", line 1166, in brpop
  File "build/bdist.linux-x86_64/egg/redis/client.py", line 565, in execute_command
  File "build/bdist.linux-x86_64/egg/redis/client.py", line 577, in parse_response
  File "build/bdist.linux-x86_64/egg/redis/connection.py", line 569, in read_response
  File "build/bdist.linux-x86_64/egg/redis/connection.py", line 224, in read_response
  File "build/bdist.linux-x86_64/egg/redis/connection.py", line 162, in readline
  File "build/bdist.linux-x86_64/egg/redis/connection.py", line 133, in _read_from_socket
redis.exceptions.TimeoutError: Timeout reading from socket
```

**Comment by andymccurdy** [comment]
The answer depends on why you're using `socket_timeout`. If you're only interested in preventing `socket.connect` from hanging indefinitely, then take a look at the `socket_connect_timeout` argument instead. `socket_connect_timeout` was introduced in 2.10.0.

If you're using `socket_timeout` to limit the amount of time waiting on `socket.recv`, then that's at odds with the `BRPOP` operation. In this case, I'd suggest using a separate client instance with a different `socket_timeout` setting.

**Comment by hyt-hz** [comment]
Thanks for your response.

Hanging on recv, if something bad happened to the socket, may cause trouble to my program, so I have to set socket_timeout, or maybe socket_keepalive is enough?

Anyway, having another instance of StrictRedis is my best choice for now, I think.
