### ISSUE TITLE
Name of redis-py package

### ISSUE THREAD

**Issue by thboileau** [andymccurdy/redis-py#585]
Hello,

I find very confusing (at least) that the name of the package to install is actually "redis" (which is __the__ server) whereas this is only a python implementation of redis client.

Is is possible possible to just install `redis-py`?
```
sudo pip install redis-py
```

**Comment by andymccurdy** [comment]
I apologize if this causes confusion. It's not something that's going to change however. It would break all existing installations to change the package name.

**Comment by AndrewGuenther** [comment]
@andymccurdy If there's no plan to fix, maybe close this out?
