### ISSUE TITLE
Allow URL encoded parameters in Redis URLs by Default

### ISSUE THREAD

**Issue by paulkeene** [andymccurdy/redis-py#589]
Yesterday I submitted pull request #586 to allow URL encoded parameters to be included in Redis URLs, but this has to be explicitly enabled by passing `decode_components=True` to `from_url` since existing clients might be relying on the current behavior.

I saw that version 3.0 of redis-py is in the works so it might be nice to include a change in the new version that removes the `decode_components` argument and always decodes URL components.

**Comment by andymccurdy** [comment]
Agreed. I believe the only issue with making this the default behavior currently is passwords that have a "%" in them.

**Comment by gyermolenko** [comment]
Since v3.0 has happened in 2018 maybe this issue can be revisited.
v4 label or wont-fix/close maybe?

**Comment by andymccurdy** [comment]
This is now the default and will be included in the 4.0 release.
