### ISSUE TITLE
PubSub object is undocumented

### ISSUE THREAD

**Issue by Suor** [andymccurdy/redis-py#592]
Currently I need to read source to use that.

**Comment by andymccurdy** [comment]
Have you looked at the README? There's a whole section on PubSub.

**Comment by Suor** [comment]
Oh, I was looking in the docs. Still some things go undocumented, like `block` and `timeout` arguments.

I don't mind using README as docs, but now situation is a bit schizophrenic: some things are here, other ones are there. There is no definite source to look. Maybe since you started docs transfer everything to it? It could contains topic pages as well as API docs. It also be easier if topics had their specific pages with nice TOC.

**Comment by andymccurdy** [comment]
Yup, I agree. I actually don't control the current docs on readthedocs. I need to to reach out to the owner and have them transfer it over.

**Comment by ParetoLife** [comment]
I second this. It's not a big deal, but it would be nice to view it on RTD. Now I'm switching between those and the source code.

Is there something blocking this that I could assist in?
