### ISSUE TITLE
expireat behavior

### ISSUE THREAD

**Issue by defransen** [andymccurdy/redis-py#598]
`expireat` uses `time.mktime` to convert dattimes into epoch timestamps. But mktime makes no check if timezone infos are available and just assumes local timezone.
The confusing result is that if you use datetimes in UTC (which might be the programmers intuitive choice after reading http://redis.io/commands/expireat) or have to deal with many timezones and use aware datetimes, the expiry is wrong.
To solve this `expireat` should check for `tzinfo` and use it if available.

**Comment by charleswhchan** [comment]
Would it be possible to publish a new release for redis-py with this fix on pypi? Thanks! 😃 

At time of writing: Latest version on pypi == 2.10.6 from Aug 2017. This fix was committed on Dec 2017.

**Comment by charleswhchan** [comment]
@andymccurdy : Would you be able to publish a release to PyPI with the fix?

**Comment by MrScallion** [comment]
I got same problem in verion 3.5.3, then I checked the source code there has no code to deal timezone problem
![image](https://user-images.githubusercontent.com/43311996/112412910-3e7ec300-8d5a-11eb-8dc8-6b68edfb1258.png)
