### ISSUE TITLE
Too many open files error because of using uuid.uuid1()

### ISSUE THREAD

**Issue by tomas-cliqz** [andymccurdy/redis-py#601]
The `Lock::lock()` method in [redis/lock.py](https://github.com/andymccurdy/redis-py/blob/master/redis/lock.py#L102) uses `uuid.uuid1()` to generate a unique token for acquiring locks. libuuid however has a bug (reported [here](https://github.com/dln/python-libuuid/issues/1) and [here](http://comments.gmane.org/gmane.linux.utilities.util-linux-ng/4771)) . The bug goes all the way down to the libuuid c-library and the problem is that it leaks file descriptors for /var/libuuid/clock.txt. It was reported several times years ago, so it doesn't look like anyone is doing anything about it. This can cause servers to crash after reaching the limit of max number of open files. I made a wrapper that doesn't use uuid to generate the unique tokens, but I think it would be really nice if this was fixed in redis-py.

**Comment by andymccurdy** [comment]
Interesting. The links you provided suggest this only occurs in threaded environments. Mostly for my own curiosity, but are you running your code in a threaded application?

**Comment by tomas-cliqz** [comment]
Yes, I was also running the code in a multi-threaded application and I noticed that the more threads I had, the more leaks. I think there's 1 fd leak per closed thread, so it's mostly a problem for applications with short running threads. If you re-use threads for different tasks, it probably won't reach a limit, but when you close the thread, file descriptors are leaked.
