### ISSUE TITLE
Is MIGRATE implemented ? 

### ISSUE THREAD

**Issue by hostmaster** [andymccurdy/redis-py#605]
Is command [MIGRATE](http://redis.io/commands/migrate) implemented ?

**Comment by imankulov** [comment]
Apparently, it's not, but it's quite trivial to fall back to `execute_command`, with something like 

```python
>>> r.execute_command('migrate', '127.0.0.1', 6379, key, 0, 5000)
```

P.S. Some questions are worth replying even in more than a year :)

**Comment by nashley** [comment]
Is there a technical reason why it's not implemented, or does someone just need to take the implement it?

**Comment by Grokzen** [comment]
@andymccurdy This one can be closed as solved. #1000 talks about it and #1064 implemented it.
