### ISSUE TITLE
redis.lock, redis.lock.Lock not thread safety

### ISSUE THREAD

**Issue by vincentwyshan** [andymccurdy/redis-py#610]
The documentation mentioned Pipline is not thread safety, and redis.lock.Lock using redis.transaction(pipline).

So redis.lock.Lock is not thread safety, am I right?

**Comment by andymccurdy** [comment]
Lock objects are thread safe when not using them with pipelines.

Once you mix in pipelines there is no guarantee about thread safety.

**Comment by vincentwyshan** [comment]
thanks. It's good to know the lock is thread safety

I have a issue when using redis.lock under multi thread context, I have to think clear for every single line code.

**Comment by tomas-cliqz** [comment]
Don't know what issue you are having, but I reported one here #601 which is a fd leak from the uuid c-library.
