### ISSUE TITLE
AttributeError: 'list' object has no attribute 'encode' (no support for multi-bulk reply to SUBSCRIBE command)

### ISSUE THREAD

**Issue by marc1n** [andymccurdy/redis-py#612]
From time to time I get error:

``` python
redis_client = redis.StrictRedis.from_url('redis://localhost:6379/0')
pubsub = redis_client.pubsub()
for message in pubsub.listen():
    # ...
```

Traceback (most recent call last):

``` python
 [...]
  File "<MYDIR>/local/lib/python2.7/site-packages/redis/client.py", line 2215, in listen
    response = self.handle_message(self.parse_response(block=True))
  File "<MYDIR>/local/lib/python2.7/site-packages/redis/client.py", line 2232, in handle_message
    message_type = nativestr(response[0])
  File "<MYDIR>/local/lib/python2.7/site-packages/redis/_compat.py", line 19, in <lambda>
    x if isinstance(x, str) else x.encode('utf-8', 'replace')
AttributeError: 'list' object has no attribute 'encode'
```

Version: redis (2.10.3)

**Comment by marc1n** [comment]
I have more information: this is happening when I subscribe more than one channel:
```python
pubsub.subscribe('channel-1', 'channel-2')
```

Somtime redis server returns 2 separate responses:
['subscribe', 'channel-1', 1L]
['subscribe', 'channel-2', 1L]

Sometimes redis server returns one multi-bulk response:
[['subscribe', 'channel-1', 1L], ['subscribe', 'channel-2', 1L]]

The second case is not supported by PubSub.listen and PubSub.get_message methods.

**Comment by andymccurdy** [comment]
Ah, interesting. This must have changed recently in the server. Should be an easy fix.

**Comment by gugu** [comment]
@andymccurdy any update on this? Problem is still exists

**Comment by hp685** [comment]
Has anyone in this thread had any luck? I'm encountering the same issue when using redis as a backend for celery

**Comment by parisk** [comment]
I am running into this issue as well.

Any idea on how could this be fixed? I am willing to put a PR for that.

## Sentry screenshot
![image](https://user-images.githubusercontent.com/1188592/29672231-4bd827a8-88f4-11e7-9c1f-8ac48beb62e0.png)

**Comment by gugu** [comment]
it is celery issue – pubsub does not support concurrency and celery tries to work with it from eventlet/greenlet

**Comment by parisk** [comment]
Thanks @gugu. Makes sense. Any idea for a workaround?

**Comment by gugu** [comment]
@parisk I just published a module: https://github.com/gugu/ezy-chord
Tomorrow I'll move it to https://github.com/EzyInsights/ezy-chord

**Comment by andymccurdy** [comment]
closing this as it seems to be a celery issue. please reopen if it's something in redis-py

**Comment by davit555** [comment]
guys I think it is not celery issue.
Right now I am facing the same issue on gevent based application which is not using celery

**Comment by gugu** [comment]
It is issue of incorrect redis-py usage. Other products can use this incorrectly as well
