### ISSUE TITLE
support zadd options

### ISSUE THREAD

**Issue by sinchb** [andymccurdy/redis-py#625]
redis 3.0.2 has released recently. Will redis-py support [this](https://github.com/antirez/redis/pull/1132#issuecomment-107310494) feature about zadd ? It's really useful.

**Comment by arturican** [comment]
I also need this feature too

**Comment by chester89** [comment]
I suppose no one would mind if I try to do that on a weekend

**Comment by sinchb** [comment]
@chester89 Much appreciated if you do this :smile:

**Comment by chester89** [comment]
ok, I'll try

2015-07-17 12:10 GMT+03:00 sinchb <notifications@github.com>:

> @chester89 <https://github.com/chester89> Much appreciated if you do this [image:
> :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andymccurdy/redis-py/issues/625#issuecomment-122225421>
> .
>



-- 
Yours faithfully,
Gleb

**Comment by chester89** [comment]
Any cloud providers already use 3.0.2? I don't have Linux VM at the moment

2015-07-17 12:30 GMT+03:00 Gleb Chermennov <thebitterend77@gmail.com>:

> ok, I'll try
>
> 2015-07-17 12:10 GMT+03:00 sinchb <notifications@github.com>:
>
>> @chester89 <https://github.com/chester89> Much appreciated if you do
>> this [image: :smile:]
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/andymccurdy/redis-py/issues/625#issuecomment-122225421>
>> .
>>
>
>
>
> --
> Yours faithfully,
> Gleb
>



-- 
Yours faithfully,
Gleb

**Comment by chester89** [comment]
So I've written the code and tests, let me try if it works with Redis
server and PR will be ready in 2 or 3 days.

2015-07-17 17:40 GMT+03:00 Gleb Chermennov <thebitterend77@gmail.com>:

> Any cloud providers already use 3.0.2? I don't have Linux VM at the moment
>
> 2015-07-17 12:30 GMT+03:00 Gleb Chermennov <thebitterend77@gmail.com>:
>
>> ok, I'll try
>>
>> 2015-07-17 12:10 GMT+03:00 sinchb <notifications@github.com>:
>>
>>> @chester89 <https://github.com/chester89> Much appreciated if you do
>>> this [image: :smile:]
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/andymccurdy/redis-py/issues/625#issuecomment-122225421>
>>> .
>>>
>>
>>
>>
>> --
>> Yours faithfully,
>> Gleb
>>
>
>
>
> --
> Yours faithfully,
> Gleb
>



-- 
Yours faithfully,
Gleb

**Comment by sinchb** [comment]
thanks a lot@chester89

**Comment by sinchb** [comment]
hi @chester89 , how about this feature :)

**Comment by chester89** [comment]
I made [a PR] (https://github.com/andymccurdy/redis-py/pull/638), there's still some finishing touches to be made

**Comment by sinchb** [comment]
hi @chester89 , how about this feature. I cannot find this feature in the newest release.

**Comment by chester89** [comment]
I didn't know the release was coming, unfortunately I didn't finish the PR.
Will do that this week

2015-11-03 5:58 GMT+03:00 sinchb <notifications@github.com>:

> hi @chester89 <https://github.com/chester89> , how about this feature. I
> cannot find this feature in the newest release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andymccurdy/redis-py/issues/625#issuecomment-153228508>
> .
>



-- 
Yours faithfully,
Gleb
