### ISSUE TITLE
Adding timeout argument to listen()

### ISSUE THREAD

**Issue by selwin** [andymccurdy/redis-py#631]
This was mentioned briefly in [this discussion](https://github.com/andymccurdy/redis-py/issues/225#issuecomment-4063287). Is this feature still planned?

My use case is for this is to enable periodic checking of job execution in RQ. I'd love to be able to do something like this:
```python
while True:
    for message in p.listen(timeout=5):
        # Cleanup job execution
    # Check whether worker is still alive
```

**Comment by AndrewGuenther** [comment]
I believe the snippet below accomplishes exactly what you're looking for.

```python
while True:
    while (message = p.get_message(timeout=5)) is not None:
        # Cleanup job execution
    # Check whether worker is still alive

**Comment by andymccurdy** [comment]
As @AndrewGuenther said, this is exactly what the `get_message` method was designed for. Please re-open if this doesn't solve your issue.
