### ISSUE TITLE
Executing custom redis commands.

### ISSUE THREAD

**Issue by har777** [andymccurdy/redis-py#632]
I used [geo-redis](https://matt.sh/redis-geo) to add additional geo functionality to redis. I'm able to use the commands from the redis-cli. Is it possible to use redis-py to use those new commands in a python script ?

Right now I'm doing : 
```
client = redis.Connection(host, port, db)
client.connect()
client.send_command('GEORADIUS ** **** ***')
```
This works. But is there an alternate better way to do it ?

**Comment by andymccurdy** [comment]
You probably want to use one of the client classes (`StrictRedis` or `Redis`) and use their `execute_command` method. You'll get automatic retrying and some other handy features. This should work just fine.

**Comment by har777** [comment]
Works perfectly well. I don't know how I missed it. Didn't find a single reference to this while searching. Thanks !
