### ISSUE TITLE
ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by hannosch** [andymccurdy/redis-py#633]
Python 2.6, redis-py 2.10.3

During `connection.disconnect` I get a ValueError and the connection cleanup fails.

Traceback, with app specific first couple stackframes removed:

```
Stacktrace (most recent call last):
  ...
  File "redis/client.py", line 2578, in execute
    return execute(conn, stack, raise_on_error)
  File "redis/client.py", line 2447, in _execute_transaction
    connection.send_packed_command(all_cmds)
  File "redis/connection.py", line 543, in send_packed_command
    self.disconnect()
  File "redis/connection.py", line 519, in disconnect
    self._parser.on_disconnect()
  File "redis/connection.py", line 216, in on_disconnect
    self._buffer.close()
  File "redis/connection.py", line 182, in close
    self.purge()
  File "redis/connection.py", line 176, in purge
    self._buffer.seek(0)
```

send_packed_command encountered a socket.error (`error(9, 'Bad file descriptor')`). It tries to call `self.disconnect()` but gets a ValueError inside the close/purge of the SocketBuffer used by the PythonParser, so it never gets to raise ConnectionError. The relevant bit from `Connection.send_packed_command` is:

```
        except socket.error:
            e = sys.exc_info()[1]
            self.disconnect()
            if len(e.args) == 1:
                _errno, errmsg = 'UNKNOWN', e.args[0]
            else:
                _errno, errmsg = e.args
            raise ConnectionError("Error %s while writing to socket. %s." %
                                  (_errno, errmsg))
```

I think the `SocketBuffer.close` should catch and ignore this error or possibly just log it. If the `SocketBuffer._buffer` isn't there anymore while we try to remove it, so be it.

**Comment by andymccurdy** [comment]
Sorry for the late reply.

Do you happen to recall the error message associated with the `ValueError` that was raised by `buffer.seek(0)`? It sounds like somehow the buffer isn't getting initialized correctly, but I fail to see how that can happen (it's initialized in `SocketBuffer.__init__`).

I tried injecting `raise socket.error(9, 'Bad file descriptor')` in `Connection.send_packed_command` manually which worked as expected. A `ConnectionError` was properly raised and the `SocketBuffer` was cleaned up appropriately.

Given that we're setting the instance's buffer to `None` after closing it's probably find to ignore errors while cleaning up the buffer. I'll go ahead and make the change but if you have more information on how this is happening I'd be interested in knowing.

Thanks for reporting this.

**Comment by Grokzen** [comment]
@andymccurdy If the referenced commit you made above resolves the issue, this issue could be closed as resolved.

**Comment by andymccurdy** [comment]
Ya, closing this as it seems to have been resolved.
