### ISSUE TITLE
Geo Commands

### ISSUE THREAD

**Issue by VsegdaZhivoi** [andymccurdy/redis-py#636]
Is there any python binding to redis geo commands (redis.io/commands#geo)?

**Comment by chester89** [comment]
Did you get somewhere with this @256x240?

**Comment by akosel** [comment]
I am not sure how the contribution model works for this project, but I am about to start a project using the Redis Geo commands. I could put together the bindings as a part of that. However, I am guessing this project is only tracking the stable commands, so this may need to wait until 3.2 is released. In the meantime, the `execute_command` method seems to work just fine.

**Comment by AndrewGuenther** [comment]
Since Geo bindings are in Beta, you will likely have to wait until they make it into the stable channel.

**Comment by alexk307** [comment]
Looks like 3.2 was released today. Any plans on starting work for GEO?

**Comment by thejpanganiban** [comment]
:+1:

`redis.execute_command()` seems to work properly with the geo commands.

**Comment by pfreixes** [comment]
@andymccurdy this one can be close

**Comment by Grokzen** [comment]
@andymccurdy Bump for closing this issue
