### ISSUE TITLE
add pattern support for subscribe

### ISSUE THREAD

**Issue by stableShip** [andymccurdy/redis-py#637]
as the [redis_example](http://redis.io/topics/notifications),I want to subscribe  all  the `__key*__:*` channels to handler some data in my project,but the `pubsub - subscribe` do not support pattern. Hope to add this feature.or is there other way to me to subscribe all `__key*__:*` channels.
 Thanks!

**Comment by AndrewGuenther** [comment]
I believe you're looking for [`PSUBSCRIBE`](http://redis.io/commands/PSUBSCRIBE)? If so, it is already supported. Check the [`README`](https://github.com/andymccurdy/redis-py#publish--subscribe)

If that's not what you're referring to, then I'm not sure I understand the question. Could you please add a bit more detail?

**Comment by stableShip** [comment]
`psubscribe` is exactly what i want ,thank you!
