### ISSUE TITLE
why there have two setex function? and with different args order?

### ISSUE THREAD

**Issue by axiaoxin** [andymccurdy/redis-py#648]
https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L1082
https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L1987

    def setex(self, name, time, value):
        """
        Set the value of key ``name`` to ``value`` that expires in ``time``
        seconds. ``time`` can be represented by an integer or a Python
        timedelta object.
        """
        if isinstance(time, datetime.timedelta):
            time = time.seconds + time.days * 24 * 3600
        return self.execute_command('SETEX', name, time, value)

    def setex(self, name, value, time):
        """
        Set the value of key ``name`` to ``value`` that expires in ``time``
        seconds. ``time`` can be represented by an integer or a Python
        timedelta object.
        """
        if isinstance(time, datetime.timedelta):
            time = time.seconds + time.days * 24 * 3600
        return self.execute_command('SETEX', name, time, value)

**Comment by andymccurdy** [comment]
This is detailed in the README: https://github.com/andymccurdy/redis-py#api-reference

The `Redis` class has a few methods that don't comply with the official parameter syntax for various reasons.
