### ISSUE TITLE
Support for NX/XX/CH/INCR options to ZADD

### ISSUE THREAD

**Issue by carljm** [andymccurdy/redis-py#649]
Redis 3.0.2+ support `NX`, `XX`, `CH`, and `INCR` options to the `ZADD` command: http://redis.io/commands/zadd#zadd-options-redis-302-or-greater

It doesn't seem (from the docs, at least) that redis-py supports these options.

Are you interested in supporting them? Should I bother with a pull request to implement support?

The one API issue is that the use of `kwargs` in the existing `zadd` API makes it a bit confusing where to add these options in the API with backward-compatibility. Any thoughts on that?

**Comment by andymccurdy** [comment]
Hey Carl, good to hear from you.

Ya, the `kwargs` issue is why I haven't already implemented this. There's a pull request (#638) that implemented each option as a separate command, but that means you can't mix options together.

My current thought is that the existing API sucks (using `kwargs`) and instead should just take a `dict` of items along with separate arguments for these options. This unfortunately breaks exiting code and I've been reluctant to bite the bullet.

It's becoming clearer that it's time for redis-py 3.0 where I can fix some of these issues without worrying as much about breaking things.

**Comment by carljm** [comment]
Hi Andy! Yeah, in practice I find the keys in a sorted set are usually dynamic, not literals, so the kwargs syntax isn't very useful anyway. So :+1: to your plan, and here's to redis-py 3.0 :-)

**Comment by AngusP** [comment]
Any idea how prevalent the `kwargs` method for `zadd` is? I doubt many people at all use it, given it's not very pythonic and as @carljm says, not great with variable keys.

**Comment by 0v0** [comment]
Hi, I found the same issue recently since I just started to use redis with Python.
And I reviewed the comments above considering the preservation of the previous way and the redis updates.
So I have an aggressive suggestion that you may preserve a keyword like "__write_mode__" to that method in kwargs. If that keyword was already used by someone, that guy must be quite boring.

**Comment by trickkiste** [comment]
Just ran into the same issue.

**Comment by id0Sch** [comment]
Hi @andymccurdy,
are there updates regarding this issue/version 3.0?
I need to use zadd w/ NX in production.

Would appreciate your reply.
thanks

**Comment by Granitosaurus** [comment]
You can monkey patch in this functionality:  


	import redis
	from redis import RedisError


	def zadd(self, name, items, nx=False, xx=False):
	    if nx and xx:
		raise RedisError("ZADD can't use both NX and XX modes")
	    pieces = []
	    if nx:
		pieces.append('NX')
	    if xx:
		pieces.append('XX')
	    for pair in items:
		if len(pair) != 2:
		    raise RedisError("ZADD items have to be pairs")
		pieces.append(pair[1])
		pieces.append(pair[0])
	    return self.execute_command('ZADD', name, *pieces)

	redis.Redis.zadd = zadd

	# then you can use
	redis.Redis().zadd('my_key', [('foo', 1), ('bar', 2)], nx=True)

**Comment by foxx** [comment]
It would be nice to see this improvement released, as it's surprising behaviour.

**Comment by andymccurdy** [comment]
fixed in redis-py 3.0
