### ISSUE TITLE
Bad assumption on TCP boundary

### ISSUE THREAD

**Issue by fusiyuan2010** [andymccurdy/redis-py#650]
I am using 2.10.1, got timeout on special query that has result length of 1449 bytes, found the reason here:
https://github.com/andymccurdy/redis-py/blob/e7589d76a20b577bbc65fbfcdb270435b24af444/redis/connection.py, on line 330:
if not buffer.endswith(SYM_CRLF):
    continue

It assumes SYM_CRLF always to be at the end of buffer, which is not true if the '\r\n' was split into two IP packets. In that case, recv() would run twice to get whole response. But the second recv() contained only '\n', so the loop will continue, until get a timeout in the next recv().

I looked into current codes, seems still the same. I didn't test it.

FYI, I made a quick & dirty fix like this to make it work. 
            last_end = ""
            ......
            if not (buffer == '\n' and last_end == '\r') and not buffer.endswith(SYM_CRLF):
                # buffer may have only 1 byte of '\n', while sometimes it is coincidently the end of response
                last_end = buffer[-1]
                continue
            last_end = buffer[-1]

Welcome feedback!

**Comment by andymccurdy** [comment]
I finally got around to looking at this. Sorry it took so long.

It turns out that trying to proactively check for a line ending in Python is less performant than just letting hiredis do it. I've deleted that section of code in master and will publish 2.10.4 shortly on PyPI.

Thanks for reporting this!
