### ISSUE TITLE
Redis.lock cannot be acquired then released in a different thread

### ISSUE THREAD

**Issue by dessant** [andymccurdy/redis-py#656]
A similar issue was solved in openstack: https://review.openstack.org/gitweb?p=openstack%2Ftooz.git;a=commitdiff;h=1664a04b3d11c06017566809fec7b5d94dae52db

```python
from threading import Thread
from redis import Redis


def callback(lock):
    lock.release()


lock = Redis().lock('app:lock', timeout=10)
lock.acquire()

Thread(target=callback, args=(lock,)).start()
```

```python
Exception in thread Thread-1:
Traceback (most recent call last):
  File "e:\dev\envs\py34_x86\Python\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "e:\dev\envs\py34_x86\Python\lib\threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "E:\dev\prs\main\test.py", line 6, in callback
    lock.release()
  File "e:\dev\envs\py34_x86\Python\lib\site-packages\redis\lock.py", line 131, in release
    expected_token = self.local.token
AttributeError: '_thread._local' object has no attribute 'token'
```

**Comment by andymccurdy** [comment]
This is the expected behavior. See the comments here about the use of thread locals:

https://github.com/andymccurdy/redis-py/blob/master/redis/lock.py#L43

**Comment by dessant** [comment]
@andymccurdy thanks a lot, I've missed reading the source.
Are there plans to expose these docstrings in the docs? I was using https://redis-py.readthedocs.org as a reference.

**Comment by andymccurdy** [comment]
Yes. Those docs on RTD are significant out of date. It's on my to-do!

**Comment by dessant** [comment]
Great work! I really like both redis and your client. :dancer:
