### ISSUE TITLE
setex raising error

### ISSUE THREAD

**Issue by Dowwie** [andymccurdy/redis-py#662]
using python3.4, setex is raising an error when a string value is used:

setex('mykey', 100, 'myvalue')

**Comment by andymccurdy** [comment]
Are you using a `Redis` instance or a `StrictRedis` instance? The `setex` command on the `Redis` class swaps the argument order of timeout and value.

**Comment by Dowwie** [comment]
that was exactly the case --  I was using the Redis instance

I was thrown off by these docs:  https://redis-py.readthedocs.org/en/latest/#redis.Redis.setex
