### ISSUE TITLE
unicode processing error when errors are returned by Redis

### ISSUE THREAD

**Issue by pacificleo** [andymccurdy/redis-py#664]
In client.py when a pipeline fails due to an exception, the following function is called which tried to add a description of the error to the exception being raised.

2528     def annotate_exception(self, exception, number, command):
2529         cmd = unicode(' ').join(imap(unicode, command))
2530         msg = unicode('Command # %d (%s) of pipeline caused error: %s') % (
2531             number, cmd, unicode(exception.args[0]))
2532         exception.args = (msg,) + exception.args[1:]

If the command does not contain utf-8 encoded byte string, the unicode lines raise an exception. 

Since Redis accepts any byte string (which may not be valid utf-8), the above function cannot assume that the command can be decoded into unicode.

Test:
1. Set AUTH on the Redis server
2. Do not provide a password to StrictRedis client
3. x = '\xe1z3\x01\xb3\xc1h\xf5\xab\xdc\x00\x0c'
3. redis.zincrby("ss", x, 10)

....
....
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 2578, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 2465, in _execute_transaction
    self.annotate_exception(ex, i + 1, command[0])
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 2529, in annotate_exception
    cmd = unicode(' ').join(imap(unicode, command))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 0: ordinal not in range(128)

**Comment by andymccurdy** [comment]
I believe this has already been fixed in the development version (2.10.4)
