### ISSUE TITLE
TypeError: an integer is required

### ISSUE THREAD

**Issue by liuaifu** [andymccurdy/redis-py#666]
```python
def GetRecordCount():
	try:
		n = 0
		for key in redisObj.keys('Server_Lock:*'):
			n += redisObj.scard(key)
		return n
	except Exception, e:
		print traceback.format_exc()
		sys.stdout.flush()
		return 0
```
Traceback (most recent call last):
  File "D:\DB_Scripts\db.py", line 253, in GetRecordCount
    for key in redisObj.keys('Server_Lock:*'):
  File "build\bdist.win32\egg\redis\client.py", line 934, in keys
    return self.execute_command('KEYS', pattern)
  File "build\bdist.win32\egg\redis\client.py", line 570, in execute_command
    connection.send_command(*args)
  File "build\bdist.win32\egg\redis\connection.py", line 549, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "build\bdist.win32\egg\redis\connection.py", line 604, in pack_command
    for arg in imap(self.encode, args):
TypeError: an integer is required

my environment: python 2.7.10 + redis-py 2.10.3

**Comment by andymccurdy** [comment]
I don't see anything wrong with the code above.

It looks like the exception is being raised while trying to encode the command arguments with the encoding specified. What `encoding` have you instantiated your `redisObj` with?

**Comment by liuaifu** [comment]
```python
def Init(host, port, db, _localIP):
	try:
		global redisObj
		global localIP
		localIP = _localIP
		redisObj = redis.StrictRedis(host, port, db)
		t = threading.Thread(target = WebThread)
		t.start()
	except Exception, e:
		print traceback.format_exc()
		sys.stdout.flush()
```
GetRecordCount make exception only the first call, the second call is no problem.

**Comment by andymccurdy** [comment]
Weird. I still don't see anything wrong with this. It works fine for me in the same Python 2.7.10 & redis-py 2.10.3 environment.

I do see you're running multiple threads. Perhaps there's something elsewhere in your code that's causing this? Have you tried testing outside of the rest of your application to ensure it's actually redis-py causing an error?

**Comment by liuaifu** [comment]
I'm using python in c++. Before call GetRecordCount, i have call another function, and the function no return value, but i suppose it return a int value, i'm not call PyErr_Fetch() and PyErr_Clear(), so the expection retain to next function.

```python
	//调用
	PyObject *objRet = PyEval_CallObject(objFunc, NULL);
	Py_XDECREF(objFunc);
	if(objRet==NULL) {
		WriteLog("%s: PyEval_CallObject失败", __FUNCTION__);
		return FALSE;
	}

	//结果判断
	if(PyInt_AsLong(objRet)==1) {
		Py_XDECREF(objRet);
		return TRUE;
	}
	Py_XDECREF(objRet);
```
