### ISSUE TITLE
PyPI Release?

### ISSUE THREAD

**Issue by xtfxme** [andymccurdy/redis-py#670]
Sorry to be that guy... looks as though the last was over a year ago? I'm trying to get non-git access to the `timeout` param of `PubSub.get_message` commited here https://github.com/andymccurdy/redis-py/commit/5c4273b7ca6b0bac15e9f23e6a9da25af16e9991 (Aug 11, 2014).

**Comment by xtfxme** [comment]
Are there other maintainers you could appoint perhaps? No shortage of interest it seems :-) someone(s) will step up.

**Comment by niwinz** [comment]
+1

**Comment by andymccurdy** [comment]
2.10.4 has been released. thanks for the poke.

**Comment by xtfxme** [comment]
Thanks!
