### ISSUE TITLE
from_url() undocumented

### ISSUE THREAD

**Issue by dvarrazzo** [andymccurdy/redis-py#680]
There is no mention about `StrictRedis.from_url()` on https://redis-py.readthedocs.org/en/latest/ or https://github.com/andymccurdy/redis-py. Is it documented anywhere?

**Comment by timsavage** [comment]
The documented version is actually `ConnectionPool.from_url`
https://github.com/andymccurdy/redis-py/blob/master/redis/connection.py#L742

**Comment by kevin1024** [comment]
This should absolutely be documented.  I had no idea that it existed, and I've always been using urllib to parse my redis urls!

**Comment by maruno** [comment]
This seems to be there now

**Comment by gyermolenko** [comment]
As was mentioned earlier the documentation is present at [RTD](https://redis-py.readthedocs.io/en/latest/#redis.ConnectionPool.from_url)

Should it be present in `readme` is a different question. Because at the moment `readme` has more information (apart from docstrings).
