### ISSUE TITLE
I found this unused variable in redis-py library

### ISSUE THREAD

**Issue by PramodBisht** [andymccurdy/redis-py#682]
Correct me if I am wrong but can't see the any usage of `command_name` argument in `get_connection` method of `BlockingConnectionPool` and `ConnectionPool` class. It is passed unneccessarily from everywhere it is called.

**Comment by andymccurdy** [comment]
Copied from #683:

The arguments are there on purpose. They allow user-authored subclasses to vary the connection returned based on the command name and/or keys involved.

A great example of this would be a ConnectionPool that automatically routes read-only queries to a set of slave servers and write queries to a master server. In this scenario get_connection needs to know the command name. Key names might be used to implement a ConnectionPool that supports client-side clustering via a hash ring.
