### ISSUE TITLE
ReadOnlyError: You can't write against a read only slave.

### ISSUE THREAD

**Issue by mtahirtariq** [andymccurdy/redis-py#688]
I am using Redis sentinel with Django. Here are the versions of packages installed

> django-redis==4.2.0
> django-redis-sentinel==1.0rc4
> redis==2.10.3
> Django==1.8.2

My Django application is running fine for months now. But today all of a sudden I started to get this error with every write request to cache.

Here is the stacktrace for the error

> ERROR 2015-12-02 09:50:28,763 django.request.base.handle_uncaught_exception:256 Internal Server Error: /xxxxxxxxxx
> Traceback (most recent call last):
>   File "xxxxxxxxxx/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
>     response = wrapped_callback(request, _callback_args, *_callback_kwargs)
>   File "xxxxxxxxxx/lib/python2.7/site-packages/django/utils/decorators.py", line 127, in _wrapped_view
>     return middleware.process_response(request, response)
>   File "xxxxxxxxxx/lib/python2.7/site-packages/django/middleware/cache.py", line 97, in process_response
>     cache_key = learn_cache_key(request, response, timeout, self.key_prefix, cache=self.cache)
>   File "xxxxxxxxxx/lib/python2.7/site-packages/django/utils/cache.py", line 268, in learn_cache_key
>     cache.set(cache_key, [], cache_timeout)
>   File "xxxxxxxxxx/lib/python2.7/site-packages/django_redis/cache.py", line 25, in _decorator
>     return method(self, _args, *_kwargs)
>   File "xxxxxxxxxx/lib/python2.7/site-packages/django_redis/cache.py", line 59, in set
>     return self.client.set(_args, *_kwargs)
>   File "xxxxxxxxxx/lib/python2.7/site-packages/django_redis/client/default.py", line 142, in set
>     return client.set(nkey, nvalue, nx=nx, ex=timeout, xx=xx)
>   File "xxxxxxxxxx/lib/python2.7/site-packages/redis/client.py", line 1055, in set
>     return self.execute_command('SET', _pieces)
>   File "xxxxxxxxxx/lib/python2.7/site-packages/redis/client.py", line 565, in execute_command
>     return self.parse_response(connection, command_name, *_options)
>   File "xxxxxxxxxx/lib/python2.7/site-packages/redis/client.py", line 577, in parse_response
>     response = connection.read_response()
>   File "xxxxxxxxxx/lib/python2.7/site-packages/redis/connection.py", line 574, in read_response
>     raise response
> ReadOnlyError: You can't write against a read only slave.

Restarting the Django server resolved the error. It seems after sentinel failover it did not updated the master which it did when it started all over again with restart of Django server. 

Please let me know if you need any more info to debug the issue. I am also willing to dig around furthur if someone can guide me in the right direction.

**Comment by Arfey** [comment]
Is because `RedisCach` from `django_redis.cache` initialization only once. RedisCach create client 
```python 
@property
    def client(self):
        """
        Lazy client connection property.
        """
        if self._client is None:
            self._client = self._client_cls(self._server, self._params, self)
        return self._client
```
in your case it is `SentinelClient`. SentinelClient create connection only once and if something happened (changed master) SentinelClient don't change connection automatically.
``` python
def get_client(self, write=True):
        """
        Method used to obtain a raw redis client.
        This function is used by almost all cache backend
        operations to obtain a native redis client/connection
        instance.
        """
        self.log.debug("get_client called: write=%s", write)
        if write:
            if self._client_write is None:
                self._client_write = self.connect(write)

            return self._client_write

        if self._client_read is None:
            self._client_read = self.connect(write)

        return self._client_read
```
So, i think that your redis master was changed to slave (read only) but sentinel use old connection to slave. If reconnect to redis when got `ReadOnlyError`, problem will solve.
