### ISSUE TITLE
Possible locking bug in python3 with decode_responses=True

### ISSUE THREAD

**Issue by twidi** [andymccurdy/redis-py#694]
When creating a redis instance by passing `decode_responses=True` to `StrictRedis`, I encouter a bug in Python 3.

The token saved in `threading.local` is created this way:

``` python
token = b(uuid.uuid1().hex)
```

And the check is done this way:

``` python
            lock_value = pipe.get(name)
            if lock_value != expected_token:
```

But with `decode_responses=True`, the value got from redis is a `str`, not a `bytes`, so the values don't match and the error `"Cannot release a lock that's no longer owned"` is raised.

Maybe it's an error on my side (detected when making [redis-limpyd](https://github.com/yohanboniface/redis-limpyd) work with redis-py 2.10.x).

It would be cool if someone could confirm this problem

Thanks in advance, and for this amazing library

**Comment by andymccurdy** [comment]
You're correct, this is a bug. `lock_value` will be a unicode string based on your encoding while `expected_token` is likely a byte string.

**Comment by andymccurdy** [comment]
This was resolved with redis-py 3.x. Thanks for reporting.
