### ISSUE TITLE
Some doubt on thread-safety of `BlockingConnectionPool`

### ISSUE THREAD

**Issue by duhoobo** [andymccurdy/redis-py#699]
I see the `BlockingConnectionPool` is designed to be able to be shared between threads, by using the thread-safe `Queue`. But Is the following code from `get_connection` possible to be called by multiple threads simultaneously, since it is not protected by any means?

```
def get_connection(self, command_name, *keys, **options):
    # ...
    # If the ``connection`` is actually ``None`` then that's a cue to make
    # a new connection to add to the pool.
    if connection is None:
        connection = self.make_connection()

    return connection
```

`make_connection` operates on internal attribute `_connections` with type `list`, and I don't think `append` on `list` is atomic.

**Comment by andymccurdy** [comment]
In most Python interpreters, including CPython, `list.append` is atomic. The only thing that uses `BlockingConnectionPool._connections` is the `disconnect` method. I don't believe that there are any thread safety concerns here.
