### ISSUE TITLE
signature of setex wrong in docs

### ISSUE THREAD

**Issue by madhukar93** [andymccurdy/redis-py#702]
it is given as: setex(name, value, time), even though it is setex(name, time, value)
https://redis-py.readthedocs.org/en/latest/

**Comment by cpnielsen** [comment]
The docs have the signature for both `redis.Redis` which is backwards-compatible showing the "wrong" signature as well as `redis.StrictRedis` which is not backwards-compatible and shows the correct signature. The documentation also mentions this.

**Comment by andymccurdy** [comment]
As @cpnielsen says, there's 2 `setex` functions, one for `Redis` and one for `StrictRedis`.
