### ISSUE TITLE
Key-Value Search

### ISSUE THREAD

**Issue by anguoyang** [andymccurdy/redis-py#711]
Hi,
I am a beginner on Redis.
Redis is famous for its key-value storage, there are some description on its official website :"data can later be retrieved only if we know the exact key used to store it"
What I want to ask: is it possible to retrieve the Key by compare all values?
In my application, I need to store many key-value pairs, when I want to search the DB, I have only the value, and want to compare with all values in the DB, and return the top-10 keys which value is more similar with the value I sent to, the comparing method is very simple, just abs(valueforsearch - valueinDB), we need select the keys for most small abs values compare with valueforsearch.

**Comment by andymccurdy** [comment]
This is a question better suited for general Redis discussion here: https://groups.google.com/forum/m/#!forum/redis-db

That said, this type of thing is typically solved by indexing your own data. For example:

SET foo 25
(Compute your score for 25. Let's say for example your computer score is 7)
SADD index:7 foo

Now to get all keys that have a "7" score value:

SMEMBERS index:7

Hope that helps.
