### ISSUE TITLE
Possible logic bug in sentinel code

### ISSUE THREAD

**Issue by bdrosen96** [andymccurdy/redis-py#714]
Looking at: https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L2163-L2183 it seems like there is a bug. If you have the following scenario:

1 Send command on socket 1

2 Try to read response and get error while doing so (socket disconnect say)

3 Reconnect to master with socket 2

4 Try to read response on socket 2 to message sent on socket 1

5 If the socket has a timeout, then parse_response will eventually timeout, leading to raised exception, but if timeout is None, I think this will block for ever.

Am I missing something? Should parse_response be bypassing the reconnect logic always?

**Comment by bdrosen96** [comment]
I realize this is for pubsub, but wouldn't this be a race condition at best. When the connection is re-established, the subscriptions seem to be renewed by on_connect. However if the response was sent after disconnect and before re-subscribe, shouldn't it be lost, assuming that the publisher will not send any more responses until it gets some sort of ack from the subscriber?

**Comment by andymccurdy** [comment]
Line https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L2181 mostly (entirely?) prevents against your hypothetical. It ensures there's data in the recv buffer of the socket. With that, read_response should never fail.

It's certainly possible there's some edge case that I'm not considering.

**Comment by bdrosen96** [comment]
That would only help if you use the non default options for non blocking and timeout, correct?

I think in the case that I am seeing (celery), the calling code is actually invoking parse_response separately. One potential issue seems to be that on_connect was not registered as a callback somehow. It looks like in that case the connection was registered just to listen, but the caller does the connection logic itself:

https://github.com/celery/kombu/blob/master/kombu/transport/redis.py#L944-L951

So this is likely more an issue with kombu than redis-py. Even so, should there be some sort of logic in _execute like:

```
if self.on_connect not in connection._connect_callbacks:
        connection.register_connect_callback(self.on_connect)
connection.connect()
```

**Comment by andymccurdy** [comment]
From the Python docs: https://docs.python.org/2/library/select.html#select.select "A time-out value of zero specifies a poll and never blocks." So the default values will check whether there's data available to be read and immediately respond.

The callback registration happens in `execute_command` (https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L2152-L2159) when executing the first pubsub command. This is when the connection is first used and seems like a logical place to setup initialization behavior.

It appears that Kombu is doing something different and using the `Connection` object directly.

**Comment by bdrosen96** [comment]
I may be missing something here, but isn't default for block True, which means can_read will not be invoked? parse_response would need to be invoked with block=False in order for it to check for data and immediately respond. (ie non default option)

In any case, it definitely looks like the main issue here is kombu using the interface poorly.

**Comment by andymccurdy** [comment]
Oh, you're right about the block. Sorry. `can_read` won't get called with the default options.
