### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'can_read'

### ISSUE THREAD

**Issue by damnever** [andymccurdy/redis-py#716]
If the PubSub object has not subscribed a subject, `pubsub.get_message()` will raise`AttributeError`: https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L2229

Maybe raise a NotSubscribedError or do somthing else in  `get_message`?

**Comment by gward** [comment]
I provided a fix for this in https://github.com/andymccurdy/redis-py/pull/707, but that PR has not received any feedback. ;-(

**Comment by pfreixes** [comment]
@gward could you break down this PR [1] getting an easy one that fix the bug?

[1] https://github.com/andymccurdy/redis-py/pull/707

**Comment by gward** [comment]
@pfreixes here is a fix for this bug and this bug only: https://github.com/andymccurdy/redis-py/pull/752

**Comment by larsks** [comment]
It looks like this is resolved in redis-py 2.10.6.  Should this issue be closed?
