### ISSUE TITLE
This is more of an information request than an issue (streaming)

### ISSUE THREAD

**Issue by SkyLeach** [andymccurdy/redis-py#725]
I fully realize that streaming isn't, generally speaking, anything close to what Redis is meant for (or even good at) but there are some very valid cases where it becomes appropriate to discuss the problem.

Specifically, redis is often used as a caching mechanism for REST, SOAP or other SoA style buffering either to reduce load cheaply and quickly or to compensate for infrequently updated data sources over slow connections or simply because the remote service is excessively slow.

The problem I am finding is with XML mostly.  I store XML responses from a REST WSAG API and about 90% of the time it works fantastically.  The problem comes in when the resulting XML is very large (around 15-100MB).  The obvious problem is that XML of this size has to be processed as a stream due to memory restrictions.  Right now I'm doing this by essentially dumping the response from redis into a StringIO buffer and then streaming that through my parser.  It's slow and not at all memory efficient.  Worse, more than one of these fetches can be happening in the same interpreter at the same time due to threading calls to the redis server.

As such I am seriously looking at having to modify my code to inject buffered streaming from the cache and I was wondering if it would be worthwhile to roll this into the redis-py functionality.  Obviously there are still a number of things about the underlying c library i don't know, but from what I have seen so far it seems doable.

Please advise.

**Comment by tuukkamustonen** [comment]
Seems like a duplicate of #535?

**Comment by SkyLeach** [comment]
partially.  There is a small side note there discussing streaming.  I realize the issue with _writing_ as a stream due to RESP.

As to the side note and the questions concerning the connection pool: it seems your fear is that the socket will be used improperly by the client.  On that we can certainly agree.  Just because you _return_ a streaming object to the caller, however, doesn't mean that the stream has to go directly to the socket.  It could instead go to a small thread that does sanity checking and is smart enough to purge the connection before returning it to the pool.

**Comment by andymccurdy** [comment]
I don't believe that redis-py will support streaming input or output data anytime soon. Sorry.
