### ISSUE TITLE
Documentation: SETEX

### ISSUE THREAD

**Issue by reikoshea** [andymccurdy/redis-py#726]
The docs show that SETEX's argument order is (name, value, time), but the source show it as (name, time, value).

https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L1130-L1138

**Comment by andymccurdy** [comment]
It depends on what client class you're using. See the bottom of this section: https://github.com/andymccurdy/redis-py/blob/master/README.rst#api-reference

redis.StrictRedis follows the official Redis argument order while redis.Redis changes them.
