### ISSUE TITLE
Strange problem: using seem port when connect redis server

### ISSUE THREAD

**Issue by zacharyzh** [andymccurdy/redis-py#727]
OS: debian
Python: 2.7
Redis: listening 6380

my english is very limited and I don't known how to explain my problem. so I upload a photo here.
![7u tjwwh1 9qt_ k uu6sl](https://cloud.githubusercontent.com/assets/4945538/14380202/d6604a66-fdb0-11e5-9436-cd0c967c2489.jpg)

```
$ netstat -anp|grep 6380
192.168.1.248:6380      192.168.1.248      ESTABLISHED   6548/python
```

No error occurs and start redis failed (because the Port 6380 was used)

**Comment by andymccurdy** [comment]
Sorry, I don't understand what problem you're having.

**Comment by zacharyzh** [comment]
my redis server listening 6380.

redis-py connect redis with 6380.

they are using the seem port (6380) !!!

**Comment by andymccurdy** [comment]
netstat is just showing the connection. redis-py isn't listening on 6380, so I don't see any issue.

**Comment by zacharyzh** [comment]
look carefully. the connection was connected to redis (6380) from 6380. This Python was started first, so redis start failed because port 6380 was used. That's the issue what I said.

**Comment by zacharyzh** [comment]
Redis-py must occurs an error in this case. Because redis server not running.

**Comment by zacharyzh** [comment]
configuration for redis-py 
host: 192.168.1.248
port: 6380
password: ~
db: 12

Can you understand what I mean?
