### ISSUE TITLE
Can we use georadius | georadiusbymember | geopos | geodist | geoadd command?

### ISSUE THREAD

**Issue by uname-yang** [andymccurdy/redis-py#746]
Redis 3.2 release GEO function. how to use the new function in this deriver.

Thanks

**Comment by pfreixes** [comment]
There is a PR [1] pending to be reviewed that implements all of these commands, I hope news soonner than later. Keeping on eye on that


[1] https://github.com/andymccurdy/redis-py/pull/736

**Comment by carltongibson** [comment]
Duplicate of #636

**Comment by uname-yang** [comment]
Thanks

**Comment by daTokenizer** [comment]
GEOADD/GEORADIUS both work pretty well for me

**Comment by andymccurdy** [comment]
#736 was merged. closing this.
