### ISSUE TITLE
Scalability of Channels (Pub/Sub)

### ISSUE THREAD

**Issue by pjebs** [andymccurdy/redis-py#756]
I'm building a real-time text based chat program where people can chat with ONLY 1 other person.
Each person can chat with 1 other person, but the aim is they can chat with Many people at once. (i.e. MANY one to one chats with different people). The aim is to have it scaleable, not necessarily to snapchat's level, but enough for 1 City.

I'm just wondering what is more scaleable:

* Having 1 channel for the **entire** application and filtering who the **message is for** and **who sent the message** based on the data encoded in the message

OR

* Having 1 channel for **each** person and all the different people sending messages to that person send their messages through that channel with data encoding **who sent the message**

OR

* Have an individual channel for EACH Chat between 2 people.

OR

* For Option 1 (1 channel for entire app), perhaps an intermediate solution of having 1 channel per city.

I'm wondering what approach is best for Python and Redis. If there is no clear cut answer, what the conditions/criteria are for making the decision.

**Comment by andymccurdy** [comment]
The solution really depends on your app. I personally like your second option (one channel per person), but it really depends on your app.

Also, if you're doing this in Go, you should probably ask in the Go community. This repo is for the Python Redis client.

**Comment by pjebs** [comment]
Thanks @andymccurdy. I'm still deciding what language to use.

**Comment by pjebs** [comment]
Do you think, 1 subscriber connection LISTENING TO ALL channels in second option is a good idea.

**Comment by andymccurdy** [comment]
No, I'd assume one connection listening to exactly one channel.
