### ISSUE TITLE
Where is the python-redis rpm package?

### ISSUE THREAD

**Issue by duyanghao** [andymccurdy/redis-py#757]
I have searched a lot online,there is no official released python-redis rpm package.I want to install python-redis(version:2.10.5) with rpm,but all i find is the url below:
https://pypi.python.org/pypi/redis/2.10.5
but the problem is that there is no rpm package,So,Where is the python-redis rpm package(2.10.5)?

**Comment by himanshuraja** [comment]
go on an check the https://www.rpmfind.net/linux/rpm2html/search.php?query=python-redis .
hope this helps

**Comment by duyanghao** [comment]
i am afraid that the above website is not to be trusted! and there is no python-redis rpm package(2.10.5) !

**Comment by andymccurdy** [comment]
I'm not sure who has provided RPM packages in the past, but it's never been us. We provide Python source and wheel distributions available on PyPI. For RPM, Deb, or other packages you'll have to check with the folks doing package management for your OS of choice.
