### ISSUE TITLE
Release version for most recent client

### ISSUE THREAD

**Issue by QuChen88** [andymccurdy/redis-py#760]
Can you please create a release on the most recent code? It would be nice to have all the new cluster-based and geo commands available in an official release.

**Comment by jumpandspintowin** [comment]
I'll second this request, I'm running into EINTR exceptions and would appreciate the patch that's already in master to be released.

**Comment by SunnyEgbo** [comment]
I agree with the previous two comments. It would be nice to use the geo commands.

**Comment by thomasst** [comment]
Yes, please make it happen @andymccurdy :)

**Comment by philfreo** [comment]
+1

**Comment by bbayles** [comment]
Adding to the chorus here - I'm the maintainer of [redis-collections](https://github.com/honzajavorek/redis-collections/), which depends on `redis-py`. I'd like to include a high-level interface to the GEO commands, but I currently have to pull a pre-release version.

I'd be pleased to help out here in this project if needed. Many thanks!

**Comment by andymccurdy** [comment]
2.10.6 is on PyPI now!
