### ISSUE TITLE
ZADD throws error with dict

### ISSUE THREAD

**Issue by Akarshit** [andymccurdy/redis-py#771]
While trying to add elements to a zset, I get the following error stacktrace
```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    r.zadd("KEY", kwargs=dict)
  File "/Library/Python/2.7/site-packages/redis/client.py", line 2057, in zadd
    return self.execute_command('ZADD', name, *pieces)
  File "/Library/Python/2.7/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/Library/Python/2.7/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/Library/Python/2.7/site-packages/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: value is not a valid float
```

The code I was trying to run was 
```
import redis
r = redis.Redis(host='localhost', port=6379, db=2)

dict = {'akarshit': 1.1}
r.zadd("KEY", kwargs=dict)
```

Is there something I am missing or is this a bug with py-redis?

**Comment by andymccurdy** [comment]
It should be:

```python
r.zadd("KEY", **dict)
```

**Comment by Akarshit** [comment]
@andymccurdy Thanks for the quick reply. It was indeed a stupid mistake on my part. 
Sorry for the stupid and issue.

**Comment by Akarshit** [comment]
@andymccurdy If I could ask for one more help. I am trying the following code 
```
import redis
r = redis.Redis(host='localhost', port=6379, db=2)

dict = {'name': 930.0}
r.zadd("KEY", **dict)
```

And am getting the following error 
```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    r.zadd("KEY", **dict)
TypeError: zadd() got multiple values for keyword argument 'name'
```
I understand that the cause of error is that the `zadd()` expects a argument `name=` and while unpacking the dictionary the `name` from dict is causing collision. 
Is there some solution to this?

**Comment by andymccurdy** [comment]
That's actually a long standing bug that requires a backwards incompatible change to fix.

Until that happens, you can call zadd like so:

```
# key1=name, score2=5.9, key2=some_other_element, score2=1.4
r.zadd('KEY', score1, key1, score2, key2)
```

**Comment by Akarshit** [comment]
I got it working using the  direct command. So the code looks like 
```
import redis
r = redis.Redis(host='localhost', port=6379, db=2)

dict = {'name': 930.0}

pieces = []
for pair in dict.iteritems():
    pieces.append(pair[1])
    pieces.append(pair[0])
r.execute_command('ZADD', "KEY", *pieces)
```

Should I open an issue for this?

**Comment by Akarshit** [comment]
I think this could be just fixed if [this] line is changed to something like
```
def zadd(self, somethingThatIsLeastLikelyToBeAEntryForSet, *args, **kwargs):
```

**Comment by kavin26** [comment]
@andymccurdy  hi... is the issue of `redis.exceptions.RedisError: ZADD requires an equal number of values and scores` when adding dict object, still open?
I'm using redis version 3.0.6 connected using redis-python
