### ISSUE TITLE
PythonParser vs. HiredisParser inconsistent when decode_responses=True

### ISSUE THREAD

**Issue by ms7s** [andymccurdy/redis-py#772]
Hi, I just noticed that `PythonParser` and `HiredisParser` implementations differ when you use `decode_responses=True` and the data returned from Redis is not decodable by the selected encoding.

`PythonParser` raises `ValueError` while `HiredisParser` (respectively `hiredis-py`) returns the original byte string instead in this case.

You can see the difference at [redis-py connection.py:296](https://github.com/andymccurdy/redis-py/blob/2ca3ffdc2102ecca1e7e419428706c29684ab38e/redis/connection.py#L296) versus [hiredis-py reader.c:78](https://github.com/redis/hiredis-py/blob/5cfdf41df274167cd399556821752459e43c316f/src/reader.c#L78)

**Comment by amw** [comment]
I have just noticed the same thing.

**Comment by andymccurdy** [comment]
This is the same problem as #1006. Closing this and will discuss over there.
