### ISSUE TITLE
redis.brpop() waits eternally if Redis went down despite the timeout given

### ISSUE THREAD

**Issue by iwuvjhdva** [andymccurdy/redis-py#775]
Hi,

I have the following problem of redis.brpop() not raising any exception or stopping on a timeout if Redis server went down after brpop() was called.

Steps to reproduce:

> > > r = redis.StrictRedis()
> > > r.brpop('foo', timeout=60)
> > > Now stop local Redis (service redis-server stop)

brpop() never quits, even after the timeout passed.

Please assist.

**Comment by andymccurdy** [comment]
Specify a `socket_timeout=62` when creating a client instance (or the underlying connection pool).

See #748 for more details.

**Comment by Grokzen** [comment]
@andymccurdy Issue seems resolved, consider closing this as solved
