### ISSUE TITLE
how can i set 'class' object and get it from redis ?

### ISSUE THREAD

**Issue by kute** [andymccurdy/redis-py#777]
class Myclass(object):
           def __init__(self):
                .....
       redis = redis.StrictRedis(host='localhost', port=6379, db=0)
       obj = Myclass()
       redis.set("mykey", obj)

now, the problem is how i get it from redis and convert to 'Myclass' type

     myobj = redis.get("mykey")
     print(type(myobj))   # <class 'bytes'>

maybe i should store `String` or `json-obj`， but how can i if i do this ? thank you

**Comment by kute** [comment]
maybe i should define `response_callback` on my redis instance by `redis.set_response_callback('get', 'my_callback_fun')`， but i don't know how to convert to `class byte` to `class` or `String` type

**Comment by andymccurdy** [comment]
I would suggest using JSON to serialize the data within your class and calling `redis.set('key', 'json_data')`. Similarly, you can retrieve it with `json_data = json.loads(redis.get('key'))`.

Of course you'll need to be able to re-create your class instance based on this data, which a helper function on your class can easily do. One of the patterns I've used before is:

```python
class MyClass(object):
    @classmethod
    def from_json(cls, json_data):
        return cls(json_data)
        # or something like:
        # instance = cls()
        # instance.attr1 = json_data['attr1']
        # ...

    def to_json(self):
        return json.dumps({
            'attr1': self.attr1,
            ...
        })

```

**Comment by kute** [comment]
Thank you. I will try with the `json_data`, maybe `store-class-object` is not the right way and i'll figure out how  the `class bytes` works.

**Comment by andymccurdy** [comment]
`Bytes` is just raw bytes. It's API is the same as a string.
