### ISSUE TITLE
socket_connect_timeout does not time out

### ISSUE THREAD

**Issue by dsuch** [andymccurdy/redis-py#778]
Hello,

this may be superficially related to #525 but I'm not really sure, perhaps it isn't.

I'm using Python 2.7.6 on Ubuntu 14.04 64-bit and redis-py 2.10.5.

Please have a look at the code snippet below:

```python

# stdlib
from datetime import datetime

# Redis
import redis
from redis.exceptions import ConnectionError

r = redis.StrictRedis(socket_connect_timeout=50)

start = datetime.utcnow()

try:
    r.ping()
except ConnectionError:
    took = datetime.utcnow() - start
    print('ConnectionError after {}'.format(took))
```

My understanding is that the call to .ping() should wait up to 50 seconds for a Redis server to become available and raise ConnectionError afterwards.

But this is not the case, the exception is raised immediately:

```bash
$ py redis-timeout1.py 
ConnectionError after 0:00:00.000374
$ 
```

Now, I can see in Connection._connect that there is a call such as ..

```python
sock.settimeout(self.socket_connect_timeout)
```

.. but it apparently makes no difference.

What could be the reason?

Thanks!

**Comment by dsuch** [comment]
Ok, now that I have had a closer look at it, the timeout appears to be the maximum time that the ```sock.connect``` will wait at most not guaranteed minimum time during which it will attempt to connect.

Please feel free to close the ticket if this is the expected behaviour.

**Comment by andymccurdy** [comment]
Correct, it's the maximum amount of time a socket operation will wait before an exception is raised. When an exception is raised immediately, it generally indicates that Redis isn't running or isn't listening on the port you're trying to connect to it.
