### ISSUE TITLE
https://redis-py.readthedocs.io docs vanished

### ISSUE THREAD

**Issue by andycoates** [andymccurdy/redis-py#783]
Did something happen to the doc build?  The documentation on each Redis command has disappeared. 

https://redis-py.readthedocs.io

**Comment by dctdevelop** [comment]
+1 
I also noticed this about 5 days ago, managed to figure out the commands from memory and forgot to raise the issue.

**Comment by erayerdin** [comment]
This also affects me.
I also tried to clone older commits or download older releases and build docs (with sphinx) myself, yet no help.

**Comment by andymccurdy** [comment]
Should be fixed.
