### ISSUE TITLE
question about process safety

### ISSUE THREAD

**Issue by monklof** [andymccurdy/redis-py#785]
Hi, I've just finished reading redis-py, there's one question about "process safe".

Every time it tries to execute one command, it will check whether the process is still the original process( `by _checkpid() ` ), if it's not, it will disconnect all opened socket, and re-establish the connections.

But the `disconnect()` method in class `Connection` tries to do so in the following way:

```python
    def disconnect(self):
        "Disconnects from the Redis server"
        self._parser.on_disconnect()
        if self._sock is None:
            return
        try:
            self._sock.shutdown(socket.SHUT_RDWR)  # Look here, should it shutdown when the subprocess tries to disconnect?
            self._sock.close()
        except socket.error:
            pass
        self._sock = None
```

It will **shutdown** the connection first, and then close it. This would cause the original process having problem when executing commands, because at that time, the socket should be closed and cannot proceed anymore.

I think the subprocess is supposed to  just close the socket without `shutdown` it.

**Comment by andymccurdy** [comment]
`Connection` objects aren't thread-safe and these objects should never be shared between threads.

When forking, it's assumed that the parent process is no longer using the `ConnectionPool`. I admit this could be cleaner, but it seems to work in all cases I've been made aware of (typically, a web server like gunicorn forking workers).

Calling `socket.shutdown()` immediately closes the socket. If you only rely on `socket.close()`, the socket can linger around until the GC cleans it up. This can lead to lots of connections in sitting in IO Wait for an unspecified amount of time.

**Comment by monklof** [comment]
It's reasonable since it's assumed that the parent process is no longer using the socket. Thanks for your response so quickly.
