### ISSUE TITLE
pubsub.listen() have a high cpu usage.

### ISSUE THREAD

**Issue by tangwz** [andymccurdy/redis-py#789]
I receive data like this:
```
for item in ps.listen(): 
    pass
```
But a simple send-channel-data server has used 15% cpu. Maybe the data out of redis channel is big.However,  I want to know is this normal phenomenon? May I lower the cpu usage?

**Comment by andymccurdy** [comment]
How many messages per second are you receiving? Each message has to be unpacked and then handed to your code.

**Comment by tangwz** [comment]
Hello,
    Because I use `psubscribe` instead of `subscribe`, and my cpu was in a tight loop. Most of the `psubscribe` data is useless.
    Thank you and I close this issue.
