### ISSUE TITLE
Purpose of "Fix re-used connection errors after fork()"

### ISSUE THREAD

**Issue by BlackRider97** [andymccurdy/redis-py#790]
@josiahcarlson  Hi. can you tell me that what is purpose of this commit https://github.com/andymccurdy/redis-py/commit/b8dd22455dc4f16eef28e848fc05b0b723022899 ?
We are using your TCP connections pooling logic except this commit and on production we are facing mismatch issue between client's request and response randomly (Request A's response returning as Request B's response).
I also read about TCP connections pooling here http://docs.sqlalchemy.org/en/latest/core/pooling.html
but I am not sure that my mismatch issue will be fixed or not if I make changes according to your commit in my connections pooling logic.

**Comment by andymccurdy** [comment]
@BlackRider97 That commit was more than 4 years ago. What version of redis-py are you using that you don't already have it in your distribution?

**Comment by josiahcarlson** [comment]
I think that @BlackRider97 is talking about some other client that he has written, and is actually asking how to do proper connection pooling. But we will see.

**Comment by BlackRider97** [comment]
@andymccurdy Mismatch issue is not encountered with redis-py. We are using redis-py's  blocking connection pool implementation to pool our thrift sockets and we are facing issue with this our own implementation. I wanted to know purpose of your commit https://github.com/andymccurdy/redis-py/commit/b8dd22455dc4f16eef28e848fc05b0b723022899 so that I can co-related this fix with our issue.

**Comment by BlackRider97** [comment]
@josiahcarlson  exactly.

**Comment by andymccurdy** [comment]
The commit ensures that a child (forked) process won't re-use any connections that were created within the parent process.
