### ISSUE TITLE
lazily returning keys()

### ISSUE THREAD

**Issue by pfigue** [andymccurdy/redis-py#791]
hi,

I've code like this:

        keys = self.conn.keys('namespace:*')
        if keys == []:
            LOGGER.warn('no keys fitting the pattern "{}".'.format(keys_pattern))
        for key in keys:
            self.conn.delete(key)

The thing is that keys() returns really a lot of keys, consumes too much memory and the OS kills my process.

So,
+ maybe there is another usage of *delete()*? where I can say something like `delete('namespace:*')` and don't need to run *keys()* before;
+ Maybe makes sense to have a lazy *keys()* operation that doesn't read and parse all the entire response before returning, if possible. As soon as it can parse one result, it `yields result`;

does it make sense to be also lazy?

**Comment by sfontana** [comment]
How about using scan or scan_iter?

**Comment by andymccurdy** [comment]
As @sfontana suggested, this is exactly what the `scan` command is for. `scan_iter` is the same thing packaged as a Python iterator.

**Comment by pfigue** [comment]
hi,

thanks both for your answers. I will try with scan and scan_iter. For the time being, it seems like this issue can be closed.

Thanks again.
