### ISSUE TITLE
consider calling redis.SET to replace redis.SETNX and redis.PEXPIRE in lock.py

### ISSUE THREAD

**Issue by andytzeng** [andymccurdy/redis-py#793]
Follow the suggestion from [Redis SET](http://redis.io/commands/set), SET command support EX, PX, NX, XX options. Based on the note:

> Note: Since the SET command options can replace SETNX, SETEX, PSETEX, it is possible that in future versions of Redis these three commands will be deprecated and finally removed.

It is better to replace redis.SETNX and redis.PEXPIRE with redis.SET in lock.py

**Comment by andymccurdy** [comment]
This was fixed at some point in the past. Sorry for not updating this issue sooner.
