### ISSUE TITLE
`setex` method' position of arguments

### ISSUE THREAD

**Issue by MrKiven** [andymccurdy/redis-py#797]
HI:

In class `Redis`:
```python
def setex(self, name, value, time)
```

In class `StrictRedis`:
```python
def setex(self, name, time, value)
```

Why the position of arguments are different..?

**Comment by andymccurdy** [comment]
`StrictRedis` follows the same argument structure as the official Redis commands. `Redis` was an earlier version that switched some arguments around and exists to maintain backwards compatibility. See here: https://github.com/andymccurdy/redis-py/blob/master/README.rst#api-reference

**Comment by MrKiven** [comment]
In fact, we have a mixin class such as:

```python
def build_volatile_props_mixin(redis_client):

    class VolatilePropsMixin(object):
        # ..

        def save_props(self, expire):
            redis_client.setex(key, v, expire)

```
So, I run into a bug that `redis_client` is instance of `StrictRedis`...

Now, I need to fix it to adpat it.
