### ISSUE TITLE
urlparse ValueError since some special character in netloc

### ISSUE THREAD

**Issue by MrKiven** [andymccurdy/redis-py#799]
In Python source code `urlparse.py`:

```python
if (('[' in netloc and ']' not in netloc) or (']' in netloc and '[' not in netloc)):
    raise ValueError("Invalid IPv6 URL")
```

Now, we use random username or password, the dsn may like:

`redis://username:pass[word@localhost:6379/0`

This case will raise `ValueError("Invalid IPv6 URL")`.

To fix this, we use regular expression from module:  `sqlalchemy.engine.url.py`.
https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/engine/url.py#L199

Will redis-py fix it too?

**Comment by andymccurdy** [comment]
You should urlencode the password. Something like:

```python
from urllib.parse import quote
import redis

password = 'pass[word'
encoded_password = quote(password, safe="")
r = redis.from_url(f'redis://:{encoded_password}@localhost:6379/0', decode_components=True)
print(r.connection_pool.connection_kwargs)
```
