### ISSUE TITLE
ZREVRANGEBYSCORE doesn't allow LIMIT ?

### ISSUE THREAD

**Issue by toddcurry** [andymccurdy/redis-py#804]
I'm confused.   Below is a perfectly legitimate Redis command, which will pull 1 and only one record back from my sorted set:  the value with the highest weight.

ZREVRANGEBYSCORE myset +inf -inf WITHSCORES LIMIT 0 1

Why isn't this possible via python?  It doesn't appear that the "LIMIT" is implemented by my examination of the code.  The limit is a pretty critical feature of the function -- so critical, it is part of the title of the function page on Redis:  https://redis.io/commands/zrevrangebyscore 

Perhaps there is another way?...    Thanks

**Comment by bbayles** [comment]
Use the `start` `num` keyword arguments to do this:

```python
redis.zrevrangebyscore('TestCollection',  400, 100, start=1, num=2)
```

The redis-cli tool reports:
```
111480785038.545746 [0 127.0.0.1:42476] "ZREVRANGEBYSCORE" "TestCollection" "400" "100" "LIMIT" "1" "2"

```

**Comment by Grokzen** [comment]
@andymccurdy Issue seems to be resolved. Consider close this one.
