### ISSUE TITLE
Why there is no monitoring method

### ISSUE THREAD

**Issue by githublaohu** [andymccurdy/redis-py#805]
Want to pass monitoring statistics related information。

Found that redis-py did not have this method

**Comment by MrKiven** [comment]
how about `redis_client.info()` ?

**Comment by githublaohu** [comment]
Info( ) statistics are not comprehensive, monitoring need to provide more detailed information to monitor the use of redis

chinaese? 
用汉语交流可以好。

**Comment by miketheman** [comment]
What other statistics would you expect to see beyond what redis info returns?

**Comment by githublaohu** [comment]
Such as read/write ratio, hot spot data

**Comment by miketheman** [comment]
I don't think either of these is something that the redis database would provide, and would be curious to know if the maintainer(s) would be interested in calculated values for read/write ratio from some sort of  extended info command.

I doubt "hot spot" would ever be included in this library, as it would require some state to be stored to determine this.

**Comment by AngusP** [comment]
This was PR'd ages ago in #194, would now need review before it could be merged as things have changed and there's a conflict

**Comment by gyermolenko** [comment]
Aforementioned PR was merged, so the issue is outdated now
