### ISSUE TITLE
Ｒelease new version contains geo and so on

### ISSUE THREAD

**Issue by Brightcells** [andymccurdy/redis-py#807]
Since 2.10.5 released on 2015-11-03, some new features has added.

Why not release a new version contains these new features on PyPI.

I think we need install latest version by ``pip install redis``, not ``pip install -e git+https://github.com/andymccurdy/redis-py.git#egg=redis-py``.

**Comment by mbande** [comment]
Yes, please make it happen @andymccurdy :)

**Comment by andymccurdy** [comment]
2.10.6 is on PyPI now!
