### ISSUE TITLE
run_in_thread not working 

### ISSUE THREAD

**Issue by wiwengweng** [andymccurdy/redis-py#811]
Hi, I am new to redis client and now using it to make a logger.

here is my scene on Windows 10:
1. I have redis setup, using the python-redis-log module to publish all the logs to redis. 
2. The channel simply is working and I can subscribe to the channel and get the logs.
3. I setup the client and a callback function(to log all the data to log file) like this

````
def task_queue(q):
    while True:
        rdp.get_message() # trigger handler
        if q:
             queue message handler
        else:
             sleep(0.01)

def my_handler(message):
    # simply handle the message and log to file.

pool = redis.ConnectionPool(host='localhost', port=6379)
r = redis.StrictRedis(connection_pool=pool)
rdp = r.pubsub()
rdp.subscribe(**{'my:channel': my_handler})

if __name__ == '__main__':
    q = _q()
    p = _p(name='p', target=task_queue, args=(q,))
    p.start()
    p.join()
````
This works for me. and I can log the logs to file.

Then I change  connection and subscribe to be a function. and make it work as run_in_thread, like this:

````
def task_queue(q):
    while True:
        # rdp.get_message() # we don't need this any more??
        if q:
             queue message handler
        else:
             sleep(0.01)

def my_handler(message):
    # simply handle the message and log to file.

def event_loop():
    pool = redis.ConnectionPool(host='localhost', port=6379)
    r = redis.StrictRedis(connection_pool=pool)
    rdp = r.pubsub()
    rdp.subscribe(**{'my:channel': my_handler})
    thread = rdp.run_in_thread(sleep_time=0.001) # will run a thread and handle the get_message function?


if __name__ == '__main__':
    event_loop()
    q = _q()
    p = _p(name='p', target=task_queue, args=(q,))
    p.start()
    p.join()
````

but this won't work, and seems that the handler is not triggered. Can you help with this?? TIA ^_^

**Comment by andymccurdy** [comment]
Apologies for not responding when you wrote this. Hope you figured out what was going on by now. If you haven't, please feel free to re-open.
