### ISSUE TITLE
Python 3 bug: sometimes the response to DEL is 'OK'

### ISSUE THREAD

**Issue by NotSqrt** [andymccurdy/redis-py#814]
Hi !

I'm porting my code base to python 3, and just faced this issue:

```
  File "/my-env/lib/python3.5/site-packages/redis/client.py", line 842, in delete
    return self.execute_command('DEL', *names)
  File "/my-env/lib/python3.5/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/my-env/lib/python3.5/site-packages/redis/client.py", line 588, in parse_response
    return self.response_callbacks[command_name](response, **options)
ValueError: invalid literal for int() with base 10: b'OK'
```

This `DEL` command is run among multiple pipelines.
It happens for both `PythonParser` and `HiredisParser`.

If you need more details, I can try to isolate the succession of commands that fail.

Thanks!

**Comment by andymccurdy** [comment]
Are you perhaps using multiple versions of Redis server in your environment? `DELETE` commands used to return `OK` when only one key could be deleted at a time. At some point, Redis server started accepting multiple keys for the `DELETE` command and changed the return value from `OK` to the number of keys deleted.

**Comment by NotSqrt** [comment]
There's a single version of redis installed on my machine : `v=3.0.7` from https://launchpad.net/~chris-lea/+archive/ubuntu/redis-server

My tests run perfectly well under python 2.7, but fail randomly under python 3.5.

**Comment by NotSqrt** [comment]
After further investigation, it seems linked to my own code:
I have a context manager in my tests that start a thread to monitor commands with a class adapted from #194 , to assert the number of commands of my tests.

If I disable this monitor, the `ValueError` no longer happens.

Did you identify potential threading issues with python 3 in redis-py ?

**Comment by NotSqrt** [comment]
I switched from re-using the connections provided by django_redis to a new instance of `StrictRedis`, which seems to solve my issue.

Thanks !
