### ISSUE TITLE
set & mset fails when memory is about to be full but available

### ISSUE THREAD

**Issue by NirmalVatsyayan** [andymccurdy/redis-py#817]
Hi,

I faced an issue, might be doing something wrong, kindly assist on this.

When i try to use mset or set command on a redis using StrictRedis client, it gives me following error.

redis.exceptions.ResponseError: OOM command not allowed when used memory > 'maxmemory'.

But when i see redis server, it isn't full. About 5% of memory is still free.  Kindly let me know if i am missing something.

Thanks

**Comment by andymccurdy** [comment]
redis-py is only returning what the server returns. In this case, the server is returning `OOM command not allowed when used memory > 'maxmemory'`.

I'd suggest posting on the redis-dev mailing list. Closing this since it's not a redis-py issue.
