### ISSUE TITLE
Lock.acquire() might cause clients could not acquire the lock forever

### ISSUE THREAD

**Issue by jackyfkc** [andymccurdy/redis-py#818]
In code [do_acquire()](https://github.com/andymccurdy/redis-py/blob/2.10.5/redis/lock.py#L120)

It is possible that the client crash between `setnx` and `pexpire`, in this case, the timeout does not effect. Other clients will failed to acquire the lock forever.

A solution is when a client fails to get the lock, the client should check the expiration on the lock, and if it is not set, set it.

Refers to book `Redis in Action`, section 6.2.5 Locks with timeouts

**Comment by fnavarrogonzalez** [comment]
I think you create the lock without a timeout https://github.com/andymccurdy/redis-py/blob/2.10.5/redis/lock.py#L17 and you don't release the lock after use it?

**Comment by Jackyele** [comment]
A simple solution is using newly version of `set` with option `NX` and `PX`, supported in Redis 2.6.12 and later

**Comment by Jackyele** [comment]
@andymccurdy

**Comment by Mocramis** [comment]
This seems solved since 2014 by 2139d817f58fbecc1b708d488af5ba514f3329cd (3.0.0)

**Comment by andymccurdy** [comment]
Thanks for pointing that out. Yes, this should have been resolved in 3.0. Please re-open if it wasn't.
