### ISSUE TITLE
Regression issue from 2.10.3 to 2.10.5: connection.py encode to unicode instead of str

### ISSUE THREAD

**Issue by tw-bert** [andymccurdy/redis-py#820]
We recently upgraded redis-py from 2.10.3 to 2.10.5 and had to apply a hotfix for this issue.
The strings we send through redis-py are of a custom and variable encoding, and may contains characters that can't be interpreted by unicode. 
redis-py is just a middle man in our scenario, and should be agnostic about string encodings.

Note: the strings originate from a non-python process, which has a python 2.7 interpreter embedded. The non-python process feeds the python interpreter with str type. redis-py sends it to redis. This means that it is not trivial for us (and possibly cpu costly, huge amounts of data involved) to convert the str to bytes before handing it over to redis-py.

Please change (`connection.py`):

```
        elif not isinstance(value, basestring):
            value = unicode(value)
```
back to:
```
        elif not isinstance(value, basestring):
            value = str(value)
```
Kind regards, TW

**Comment by andymccurdy** [comment]
We changed this for a reason. Calling `str(value)` throws an exception if the string representation contains characters that can't be implicitly converted to bytes. Calling `unicode(value)` matches a caller's expectations when passing an object that defines `__unicode__` (or `__str__` in Py3).

You're paying the cost to convert to bytes somewhere, whether that's in your code or within redis-py. redis-py knows how to deal with both byte representations and any standard encoding Python knows how to deal with. If you're doing something custom, you should be converting it to something that Python knows how to deal with before sending it into a Python process.

**Comment by tw-bert** [comment]
Hi Andy, thanks for your reply.

I'm not talking about a string representation of an object, it's actually a str, for example `'\x80'`.
The code that used to work and now fails, is something like `unicode('\x80')`, which raises an exception (and rightfully so) . It used to be `str('\x80')` in redis-py 2.10.3.
But I understand that the change is for a reason. I'll look into it in more detail to come up with a solution that meets both requirements.

**Comment by andymccurdy** [comment]
The only the way in Py2 that `unicode()` gets called is if you're passing a value that's not a `str` or `unicode` already. `isinstance(value, basestring)` tests against both `str` and `unicode` on Python 2.

What type of object are you passing?

**Comment by tw-bert** [comment]
Ah, that must be it. In this scenario, sometimes it's a `bytearray()` . That's probably where the exception was thrown. So it used to be `str(bytearray)` which would always succeed.

What do you suggest?

**Comment by andymccurdy** [comment]
Ya, if you always call `str(bytearray)` before passing your value into redis-py you should be good to go.

**Comment by tw-bert** [comment]
I agree, and that's no extra conversion. Thank you, this issue is closed.
