### ISSUE TITLE
Version 2.10.6?

### ISSUE THREAD

**Issue by edevil** [andymccurdy/redis-py#823]
Is there a tentative date for the release of the next version? I'm already using the new changes in the ConnectionPool.from_url that correctly parses the timeout values as floats, but it would be better to use a released version. :)

**Comment by tuukkamustonen** [comment]
I am after the very same feature. 2.10.5 was released over a year ago and there are also several other fixes in master.

Ping @andymccurdy.

**Comment by gjcarneiro** [comment]
Me too, I assume this is why there is this [fork](https://pypi.python.org/pypi/redispy/3.0.0) on github and PyPI, with higher version number!

**Comment by baileyparker** [comment]
Is this repo no longer maintained @andymccurdy?

**Comment by edevil** [comment]
https://twitter.com/andymccurdy/status/735713770446585857

**Comment by joshowen** [comment]
Hey @andymccurdy any thoughts on moving the project to https://github.com/jazzband/?

**Comment by andymccurdy** [comment]
2.10.6 is on PyPI now!

**Comment by Shemeikka** [comment]
Would it be possible to add this new release to this repository's releases page? It currently has 2.10.5 as the latest version.
