### ISSUE TITLE
Consider making the incrbyfloat value parameter mandatory 

### ISSUE THREAD

**Issue by blutack** [andymccurdy/redis-py#832]
Firstly, thanks for redis-py!

I recently had a rather silly bug where due to misplaced parenthesis I was calling incrbyfloat with a single parameter (the key). I was surprised to find that incrbyfloat (and several other functions) take amount as an optional argument, defaulting to 1.0. This isn't consistent with raw redis, which will return an error if the increment argument is missing.

I appreciate that the API attempts to knock some of the edges off redis (such as the KEYS * default value), but in this case I think there might be an argument for making it a mandatory value. I would argue that in the case where you do wish to increment by a float value of 1.0, most developers would pass this explicitly rather than relying on the implicit behavior of redis-py.

I'm happy to submit a patch if you think there is any merit in this argument, although obviously it would be a breaking change if anyone is relying on the default behavior.

Thanks!

**Comment by andymccurdy** [comment]
Sorry for the late reply. At this time I'd prefer not to make breaking API changes. The default value was added here to be consistent with `incr()` and `incrby()`.
