### ISSUE TITLE
WRONGTYPE - Key with colons

### ISSUE THREAD

**Issue by george-mengelberg** [andymccurdy/redis-py#835]
Hello,
I am encountering WRONGKEY errors under the following circumstances:
- redis-cli trying to read keys added by redis-py (key = 'frontend:test.ufam.jp')
- redis-py client trying to read keys added by redis-cli (key = 'frontend:test.ufam.jp')

Each client is able to successfully read keys they created.  Here is a [simplified example](http://pastebin.com/uewuwdFa) showing a call to keys() then using the value in a call to lrange() which causes an error.

Any suggestions or insight as to what may be going wrong would be much appreciated.

Environment:
- Ubuntu: Ubuntu 16.04.1 LTS
- Python Redis version: redis (2.10.5)
- redis-server: 3:3.0.7-1chl1~precise1

**Comment by andymccurdy** [comment]
`WRONGKEY` indicates that you tried to to perform an operation on a value of a different type. In your example, it looks like you're trying to perform the list operation `LRANGE` on a key, but the error indicates that the value stored at that key isn't a Redis list.

**Comment by george-mengelberg** [comment]
You are correct sir.  Using p.type(k.pop()) (line 6) indicates it is a 'string', but a Type check in redis-cli indicates it is a 'list'.

I am not sure they redis-cli and redis-py would return different types for the same key.

**Comment by andymccurdy** [comment]
In your example you're using Python's builtin `type()` on the key name which will always be a string. To see the same value that redis-cli shows you'd want to use `r.type(keyname)` instead.
