### ISSUE TITLE
unexpected keyword argument 'socket_connect_timeout'

### ISSUE THREAD

**Issue by markwingerd** [andymccurdy/redis-py#838]
UnixDomainSocketConnection fails if it's given socket_connect_timeout as shown in this issue with celery:
"Invalid Arguments for task test.add: __init__() got an unexpected keyword argument 'socket_connect_timeout'"
https://github.com/celery/celery/issues/2903

**Comment by andymccurdy** [comment]
Ya, whoops missed this one. Thanks.
