### ISSUE TITLE
Redis Sentinel With SSL

### ISSUE THREAD

**Issue by Patchett** [andymccurdy/redis-py#840]
Hello,
I am attempting to setup 2 slaves and a master with redis sentinel. The redis/sentinel instances will be in a secure datacenter, so we do not have to worry about encrypting the traffic between them. However, I have clients that will be talking to the redis/sentinel instances from outside of the secure datacenter. That traffic will have to go over the internet. I am wondering if there is a way to use the built in SSL with sentinel such that my client connections will be encrypted when they talk to any of the redis/sentinel instances?

**Comment by yakhira** [comment]
why closed?
