### ISSUE TITLE
Different code same version

### ISSUE THREAD

**Issue by aerogelio** [andymccurdy/redis-py#841]
I'm not sure what I'm going to report, but it would be nice to take a look at it.

Although the versions installed since "pip" and "source" are the same 2.10.5, only with installation from source I could use the pubsub_channels() functions and others similary.

**Comment by NoneGG** [comment]
Maybe these functions are merged in redis-py's master branch recently and not released in 2.10.5 ?

**Comment by AngusP** [comment]
ad8e232487a1b9e2f17b361cc4f87740df2134f9 is version 2.10.5, the repository is ahead of that reference by a number of commits including b786d3825db87b9940305cf87297dad73953b691 where the `PUBSUB *` subcommands were added.

I don't think @andymccurdy is planning on a release any time soon?

**Comment by andymccurdy** [comment]
2.10.6 is on PyPI now!
