### ISSUE TITLE
proposal: docker

### ISSUE THREAD

**Issue by steenzout** [andymccurdy/redis-py#843]
@andymccurdy I said on Twitter that I could help but I didn't get any reply back on what exactly so here is my proposal.

I can see you have several Vagrant related stuff, I imagine, to setup test environments, correct?

I'm willing to port this to docker and
tweak travis-ci to do whatever tests you do / run against.

let me know if you are interested so I don't waste my time.

**Comment by RoeyPrat** [comment]
Hi @steenzout,
If you are still up to it, we would like your help in moving to dockerized dev env.
Let me know if you can, otherwise we will re-assign.
Cheers!

**Comment by abrookins** [comment]
I could also take a crack at this if steenzout isn’t available.

**Comment by RoeyPrat** [comment]
In the interest of moving this forward, I'm re-assigning this to @abrookins.
Let me know if you have any questions.

**Comment by abrookins** [comment]
Roger that. I’ll start taking a look.

**Comment by abrookins** [comment]
I think we did this one!

**Comment by andymccurdy** [comment]
We did! Forgot to close this.
