### ISSUE TITLE
Crashed in subprocess

### ISSUE THREAD

**Issue by YiiGuxing** [andymccurdy/redis-py#844]
```python
import redis
import threading
import multiprocessing

r = redis.Redis(db=3)


def _thread():
    r.set("pys", "thread")
    print ">>> thread"


def _process():
    r.set("pys1", "process")
    print ">>> process"


t = threading.Thread(target=_thread)
t.setDaemon(True)
t.start()
p = multiprocessing.Process(target=_process)
p.daemon = True
p.start()
p2 = multiprocessing.Process(target=_process)
p2.daemon = False
p2.start()

t.join()
p.join()
p2.join()
```
> Process:               Python [1568]
> Version:               2.7.13 (2.7.13)
> Code Type:             X86-64 (Native)
> Parent Process:        Python [1566]
> Responsible:           Python [1568]
> OS Version:            Mac OS X 10.12.2 (16C67)
> Crashed Thread:        0  Dispatch queue: com.apple.main-thread

This code can make python subprocess crash. How can i avoid it？Thanks.

**Comment by andymccurdy** [comment]
This was fixed in redis-py 3.0+
