### ISSUE TITLE
Connection reset error with large data during set operation

### ISSUE THREAD

**Issue by chandu-atina** [andymccurdy/redis-py#850]
We are trying to SET pickled object of size 2.3GB into redis through redis-py package. Encountered the following error.

> BrokenPipeError: [Errno 32] Broken pipe
> redis.exceptions.ConnectionError: Error 104 while writing to socket. Connection reset by peer.

I would like to understand the root cause. Is it due to input/output buffer limitation at server side or client side ? Is it due to any limitations on RESP protocol?  Is single value (bytes) of 2.3 Gb allowed to store into Redis ?

> import redis
> r = redis.StrictRedis(host='10.X.X.X', port=7000, db=0)
> pickled_object = pickle.dumps(obj_to_be_pickled)
> r.set('some_key', pickled_object)

**Client Side Error**
>BrokenPipeError: [Errno 32] Broken pipe
> /usr/local/lib/python3.4/site-packages/redis/connection.py(544)send_packed_command()
-> self._sock.sendall(item)

**Server Side Error**
> 31164:M 04 Apr 06:02:42.334 - Protocol error from client: id=95 addr=10.2.130.144:36120 fd=11 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=16384 qbuf-free=16384 obl=42 oll=0 omem=0 events=r cmd=NULL

> 31164:M 04 Apr 06:07:09.591 - Protocol error from client: id=96 addr=10.2.130.144:36139 fd=11 name= age=9 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=40 qbuf-free=32728 obl=42 oll=0 omem=0 events=r cmd=NULL

Redis Version : 3.2.8 / 64 bit

**Comment by iamwithnail** [comment]
Did you ever get a resolution to this?  Having similar issues.

**Comment by chandu-atina** [comment]
As per RESP protocol max size that can be stored in Redis is 512MB

Storing  a value greater than 512MB is practically not possible

**Comment by healiseu** [comment]
Hi, I have run into the same problem:
```python
redis.exceptions.ConnectionError: Error 104 while writing to socket. Connection reset by peer
```
And this is some [code][1] that you can run in order to reproduce this error. 

* **For 500k floats** the pipeline, i.e. `rdb.zadd('FloatNDX', **flt_scores)` seems to work fine although I am not satisfied from the write performance (5 seconds).
* **For 1,000,000 floats** the pipeline breaks down and I get the error above

Nevertheless if you try a different RESP python client e.g. [nok/redis-resp][2] for bulk insertion with a command like the following

```sh
python -m resp -i zadd_data.csv -r "ZADD {0} {1} {2}" | redis-cli --pipe
```
The pipeline works without any errors and in my environment I managed to load successfully the data on redis server in 10.357sec

Therefore I guess this error has to do with the volume of data and the specific implementation details of redis-py client. 

Moreover I think many python-redis users and also many ORM packages that are dependent on redis-py will benefit if you manage to improve the writing speed of pipeline although I can understand that this is an issue which is dependent on redis server optimization.

[1]: https://gist.github.com/healiseu/5cc83248a4cad47c92c8a106cd0b1dc3
[2]: https://github.com/nok/redis-resp

**Comment by pembo13** [comment]
I seem to suddenly be getting this error, and I don't have any clue on how attack it.

**Comment by pembo13** [comment]
I'm getting this while waiting for a set of Celery tasks to complete. The tasks themselves complete, but the code just dies here with redis.

**Comment by vibhavagarwal5** [comment]
@pembo13 I've been getting the same error. Any solutions?

**Comment by bewing** [comment]
I'm also seeing this when attempting to a large chord operation in Celery, waiting on 500+ tasks to complete causes an exception, but breaking it into smaller chunks and processing separately without issue.

```python
  File "/usr/local/lib/python2.7/dist-packages/celery/result.py", line 697, in get
    on_interval=on_interval,
  File "/usr/local/lib/python2.7/dist-packages/celery/result.py", line 815, in join_native
    on_message, on_interval):
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/asynchronous.py", line 142, in iter_native
    for _ in self._wait_for_pending(result, no_ack=no_ack, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/asynchronous.py", line 255, in _wait_for_pending
    on_interval=on_interval):
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/asynchronous.py", line 56, in drain_events_until
    yield self.wait_for(p, wait, timeout=1)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/asynchronous.py", line 65, in wait_for
    wait(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/redis.py", line 127, in drain_events
    message = self._pubsub.get_message(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 3135, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 3036, in parse_response
    return self._execute(connection, connection.read_response)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 3013, in _execute
    return command(*args)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 637, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 290, in read_response
    response = self._buffer.readline()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 224, in readline
    self._read_from_socket()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 199, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')
Fri Jul  5 14:34:41 UTC 2019
```

redis 3.2.1 and celery 4.3.0

**Comment by pembo13** [comment]
@vibhavagarwal5 no leads at all unfortunately.

**Comment by thushv89** [comment]
Facing a similar issue. I found [this GitHub gist](https://gist.github.com/amgorb/c38a77599c1f30e853cc9babf596d634) if it helps. I am still testing it so will update the comment if this solves the issue.

**Comment by 15astro** [comment]
I am not getting the slave buffer error in redis logs but the same error redis.exceptions.ConnectionError: Error 104 while writing to socket. Connection reset by peer in application logs.

Is increasing the slave buffer going to help?

**Comment by thushv89** [comment]
Hi @15astro,

I was getting the same `redis.exceptions.ConnectionError: Error 104 while writing to socket. Connection reset by peer in` error and I was getting the buffer error in `redis` logs. So I'm not entirely sure if that's the case with your problem.
