### ISSUE TITLE
'StrictRedis' object has no object called 'geoadd'

### ISSUE THREAD

**Issue by kshamazingade** [andymccurdy/redis-py#851]
` import redis `

` conn = redis.StrictRedis(host="localhost", port=6379, db=0)`
` conn.geoadd('location', 12.97, 77.59, 'Bangalore') `

I printed the contents of StrictRedis by doing:
`print dir(StrictRedis)` and 'geoadd' was missing from the contents.

**Comment by baileyparker** [comment]
The most recent version of redis-py available on pip is [2.10.5](https://pypi.python.org/pypi/redis), which was released on [November 2, 2015](https://github.com/andymccurdy/redis-py/releases). `geoadd` and friends weren't added until https://github.com/andymccurdy/redis-py/commit/4c331411b6f761226cdefb90250912db325d01e4 (11 months ago).

See #823.

You can either use the [fork](https://pypi.python.org/pypi/redispy/3.0.0) mentioned in that issue (preferred) or `pip install git+https://github.com/andymccurdy/redis-py.git`.

**Comment by schlitzered** [comment]
you could also give http://pyredis.readthedocs.io a try, which is a from scratch python 3 redis client implementation.

**Comment by andymccurdy** [comment]
2.10.6 is on PyPI now!
