### ISSUE TITLE
Documentation for setex is wrong

### ISSUE THREAD

**Issue by radzhome** [andymccurdy/redis-py#853]
https://redis-py.readthedocs.io/en/latest/#redis.Redis.setex

Should be `setex(name, time, value)`

proof:

```
>>> s.setex('hi', 1000, 100)
True
>>> s.get('hi')
'100'
>>> s.ttl('hi')
988L
>>> s.ttl('hi')
983L
>>> s.ttl('hi')
982L
```

**Comment by andymccurdy** [comment]
That's why the docs also suggest using the `StrictRedis` client class instead of the `Redis` client class: https://redis-py.readthedocs.io/en/latest/#redis.StrictRedis.psetex

**Comment by radzhome** [comment]
Yeah my bad, I was using `StrictRedis`
