### ISSUE TITLE
Redis-py hang up several time when redis host is down

### ISSUE THREAD

**Issue by dayusor** [andymccurdy/redis-py#854]
When the redis host turns unreachable through the network, or the host is down, the commands do not respect the timeout given on the class instance

`StrictRedis(connection_pool=pool, socket_timeout=1, socket_connect_timeout=1)`

Is there a way to handle this?

Thanks in advance

**Comment by schlitzered** [comment]
if you are not bound to python 2.x you could give http://pyredis.readthedocs.io a try

**Comment by rfyiamcool** [comment]
+1
