### ISSUE TITLE
Using sudo with pip is hazardous, remove the recommendation

### ISSUE THREAD

**Issue by altendky** [andymccurdy/redis-py#858]
Mixing pip package management with system package management (apt-get etc) can cause significant issues with the entire Python installation.  It is not uncommon for people to come into #python with damaged installations after having used sudo with pip.  I presume the same goes for the other global installation methods.  The general recommendation is to use virtualenv's for isolation.

Anyways, please consider removing the recommendation of using sudo from the readme.

Cheers,
-kyle

**Comment by itamarhaber** [comment]
Makes sense to me 👍
