### ISSUE TITLE
Fix re-used connections after fork (again)

### ISSUE THREAD

**Issue by stefanmh** [andymccurdy/redis-py#863]
When fork()ing a process having a `Redis` object, the child inherits the file descriptors.
To prevent a race, the child correctly refuses to use the inherited connections (see https://github.com/andymccurdy/redis-py/commit/b8dd22455dc4f16eef28e848fc05b0b723022899). It thus calls `close()` on those fd-s (good), but also `shutdown()` (bad), thus breaking the socket for the parent.

See e.g. http://www.unixguide.net/network/socketfaq/2.6.shtml:

>   Generally the difference between close() and shutdown() is: close()
  closes the socket id for the process but the connection is still
  opened if another process shares this socket id.  The connection stays
  opened both for read and write, and sometimes this is very important.
  shutdown() breaks the connection for all processes sharing the socket
  id.  Those who try to read will detect EOF, and those who try to write
  will reseive SIGPIPE, possibly delayed while the kernel socket buffer
  will be filled.

**Comment by rolette** [comment]
Same issues as #732. I submitted a fix for it (#784) that we've been running for months, but it hasn't been merged in.

**Comment by andymccurdy** [comment]
This is now resolved. Sorry for the amount of time that it took.

**Comment by andymccurdy** [comment]
3.2.0 has been released with these fixes.
