### ISSUE TITLE
redis client scan is stateful

### ISSUE THREAD

**Issue by azman0101** [andymccurdy/redis-py#869]
Hi,

I've read on redis documentation that redis SCAN is stateless
https://redis.io/commands/scan#multiple-parallel-iterations

On the basis of my own observations, https://redis-py.readthedocs.io/en/latest/#redis.StrictRedis.scan is stateful.

This is a bit confusing.

**Comment by andymccurdy** [comment]
All state is stored in the cursor that Redis returns. No state is stored within redis-py nor the Redis server. The scan functions return a tuple of `(cursor, [keys...])`. When calling a scan function again with the intent of continuing the iteration, passing the cursor will instruct the server to resume where it previously left off.

Most people prefer the `scan_iter` functions which return a generator that remembers the cursor automatically for you.
