### ISSUE TITLE
Can you permit adding type stubs for redis-py to typeshed?

### ISSUE THREAD

**Issue by CrazyPython** [andymccurdy/redis-py#870]
https://github.com/python/typeshed

> NOTE: When you're contributing a new stub for a package that you did not develop, please obtain consent of the package owner (this is specified in PEP 484). The best way to obtain consent is to file an issue in the third-party package's tracker and include the link to a positive response in your PR for typeshed.

**Comment by Daenyth** [comment]
@andymccurdy Can you sign off on this? Having stubs for redis would help quite a bit.

**Comment by andymccurdy** [comment]
Sure, go for it.

**Comment by Daenyth** [comment]
@CrazyPython I'll be working on these here: https://github.com/Daenyth/typeshed

If you're interested I'd be happy to add you as a contributor.
