### ISSUE TITLE
Handling of variable numbers of Arguments

### ISSUE THREAD

**Issue by mirko-lelansky** [andymccurdy/redis-py#873]
Hallo here I have a sample example which uses the rpush command to write a python list to redis which is from the method signature possible. But when I later call rpop on the same list it returns only one element which contains the string representation of the list. The value of result should "b" and not "['a', 'b']". See the following code. This seems the same problem like in issue #471 .

```python
import redis

def main():

conn = redis.StrictRedis()
conn.rpush("mylist", ["a", "b"])
result = conn.rpop("mylist")
```

**Comment by andymccurdy** [comment]
When passing multiple values to RPUSH (or any other command that allows a variable number of args), pass them like this:

```python
conn.rpush("mylist", *["a", "b"])
```
