### ISSUE TITLE
[Documentation] Setex arguments in documentation not correspond with implementation

### ISSUE THREAD

**Issue by jfhuete** [andymccurdy/redis-py#874]
In the documentation explained that the setex method is called setex(name, value, time) but in the code the definition of setex is setex(name, time, value). The arguments time and value there are in diferent order.

regards!

**Comment by albinowax** [comment]
Just got caught out by this myself. I'd submit a pull request to fix it if I could find the right page to edit..

**Comment by andymccurdy** [comment]
You're probably using the `Redis` class rather than the `StrictRedis` class. There's info on this already here: https://github.com/andymccurdy/redis-py#api-reference

Look at the last section of the API Reference.

**Comment by albinowax** [comment]
I'm definitely using StrictRedis. I'm using the debian packaged version of pyredis though, so I guess it could be related to that.

**Comment by andymccurdy** [comment]
StrictRedis has always had the same argument order as the Redis server. Can you point me at a link to the Debian package you’re using?

**Comment by albinowax** [comment]
This is the one: https://packages.debian.org/stretch/python3-redis
