### ISSUE TITLE
Best way to increase EXPIRE time with low overhead?

### ISSUE THREAD

**Issue by SnowySailor** [andymccurdy/redis-py#875]
I've thought up two ways. One of them definitely works and the other might work better if it's even possible to do.

The first way is to take the expire time with `pttl(key)` and then just add to it before resetting the expire time with `pexpire(key, newTime)`. I did some tests and it seems like over 15 of those calls you're losing about 50-70ms off of your key's expire time.

The other way is with pipelines. Perhaps something like
```py
with red.pipeline() as pipe:
    expireTime = pipe.pttl(key)
    expireTime = expireTime + 3000
    pipe.pexpire(key, expireTime)
    pipe.execute()
```
The only issue is that when you're wanting to add to `expireTime` you can't because it isn't an int, it's a StrictPipeline object. It seems like you can access the value when you do `pipe.get(key)` (example was given in documentation) but that's probably something different.

Does anyone know of a good way to increase the expire time very quickly so that you don't have very much time "lost?" Thanks.

**Comment by Seojiwoong** [comment]
How about using 'expireat' or 'pexpireat'?
If you want expire key after 3000ms, you jjust expireat(nowTimestamp+3000)
maybe this is better way
