### ISSUE TITLE
hmget returns a list without keep the field order

### ISSUE THREAD

**Issue by ssforpp** [andymccurdy/redis-py#876]
Sometimes **hmget** returns a list of values that don't match the order of fields.

How to reproduce the issue:
```
redis_client.hmset('hkey', {'field1': 'some value', 'field2': 2})
print(redis_client.hmget('hkey', {'field1', 'field2'}))
```
Sometimes, it returns `[b'2', b'some value']`. 

It works fine when I execute the command using redis-cli. 

redis-py version: 2.10.5. 
hiredis-py: 0.2.0
Redis version: 3.0.7

**Comment by jackieleng** [comment]
Isn't this because you're using a `dict` in the hmset and a `set` in the hmget, both of which are unordered datastructures? Maybe use an `OrderedDict`?

**Comment by andymccurdy** [comment]
The `dict` entry has nothing to do with it. The order is specified by the second argument of `hmget`.

@ssforpp you need to pass a list or tuple instead of a string. For example, the following code will always return field1 before field2:

```python
print(redis_client.hmget('hkey', ['field1', 'field2']))
```

**Comment by andymccurdy** [comment]
Closing this as it seems like everything is working fine within redis-py.
