### ISSUE TITLE
redis.srandmember returns one member when number = 0

### ISSUE THREAD

**Issue by a1exwang** [andymccurdy/redis-py#881]
The document says:

> srandmember(name, number=None)[source]
If number is None, returns a random member of set name.
If number is supplied, returns a list of number random memebers of set name. Note this is only available when running Redis 2.6+.

But if I use redis.srandmember(key, 0), it returns one elememt.

I think there is a bug in redis/client.py:1647, 
```
number and [number] or []
```

**Comment by andymccurdy** [comment]
thanks! merged.
