### ISSUE TITLE
r.get('foo') returns b'bar

### ISSUE THREAD

**Issue by nsantiago2719** [andymccurdy/redis-py#884]
I'm just testing the package and followed the example at the readme docs like making connection, setting a value on 'foo' with 'bar' and getting it. But the return value is different it says it should return just 'bar' but in mine it returns "**b'bar**" . I don't know if that's normal though. anyway I also tried accessing the data through `redis-cli` and it just returns me `bar`

**Comment by andymccurdy** [comment]
Sounds like you're on Python 3. You should specify `decode_responses=True` as an additional argument when creating the connection if you want string values to automatically be decoded for you.

Apologizes that this isn't in the docs anywhere.

**Comment by nsantiago2719** [comment]
Nope it's fine.
