### ISSUE TITLE
[Question] Set many things at once

### ISSUE THREAD

**Issue by thenets** [andymccurdy/redis-py#889]
Hi.

I don't know if this exist in Redis core, but I want know if is possible to set multiple things at once.
I need to set 2000 registries on Redis database and I don't how can I do it with only one request to server database. This is possible?

Thanks.

**Comment by carltongibson** [comment]
Check out the [docs for Pipelining](https://redis.io/topics/pipelining). `redis-py` provides the [`pipeline` method](https://redis-py.readthedocs.io/en/latest/#redis.Redis.pipeline) to make use of this.

**Comment by thenets** [comment]
I found it 30min ago and the "hmset" and "pipeline". The combination of both solve my problem!! :D
Thanks. The Redis is solving a lot of my optimization problems. Awesome tool.
