### ISSUE TITLE
zrange with score_cast_func=int throws ValueError: invalid literal for long() with base 10

### ISSUE THREAD

**Issue by genbits** [andymccurdy/redis-py#891]
When a sorted set contains certain floats, conversion to `int` throws:
`ValueError: invalid literal for long() with base 10`

To reproduce:

    redis:6379>  zadd myset 1.00000000000003 test

    r = redis.StrictRedis()
    r.zrange('myset', 0, -1, withscores=True, score_cast_func=int)
    ValueError: invalid literal ...

I override it manually by not using the `score_cast_func` and converting the score strings using `int(float(...))`

**Comment by andymccurdy** [comment]
I don't really have a solution for this. When I first added `score_cast_func`, I was envisioning someone might want to use Python's `Double.double` for greater precision.

Using the default `score_cast_func=float`, you can always convert the values to `int`s in your code where you need them.
