### ISSUE TITLE
rebloom support

### ISSUE THREAD

**Issue by viehwegerlib** [andymccurdy/redis-py#898]
Is the [rebloom](https://redislabs.com/blog/rebloom-bloom-filter-datatype-redis/) implementation, i.e. fast Bloom filters in Redis, supported?

Thanks!

**Comment by andymccurdy** [comment]
It's not directly supported because it's a 3rd party module. However, you can still use it via redis-py like so:

```python
r = redis.StrictRedis(...)
r.execute_command('BF.ADD', 'bloom', 'mark')
```

**Comment by viehwegerlib** [comment]
awesome, thanks.

i can add multiple values like so

```python
r.execute_command('BF.MADD', 'bloom', [i for i in range(int(1e5))])
````

however, trying to query with multiple values returns just one value

```python
r.execute_command('BF.MEXISTS', 'bloom', [1, 27, 1000001])
# returns [0]
```

how can I get the expected result, i.e. `[1, 1, 0]`?

**Comment by andymccurdy** [comment]
`execute_command` takes pieces via `*args`. Never pass a list or tuple directly as one of the arguments. Instead:

```python
r.execute_command('BF.MADD', 'bloom', *[i for i in range(int(1e5))])
# and 
r.execute_command('BF.MEXISTS', 'bloom', *[1, 27, 1000001])
```

**Comment by viehwegerlib** [comment]
perfect, thank you!

**Comment by volleyball26** [comment]
> `execute_command` takes pieces via `*args`. Never pass a list or tuple directly as one of the arguments. Instead:
> 
> ```python
> r.execute_command('BF.MADD', 'bloom', *[i for i in range(int(1e5))])
> # and 
> r.execute_command('BF.MEXISTS', 'bloom', *[1, 27, 1000001])
> ```

thank you!
