### ISSUE TITLE
TypeError: lrem() got an unexpected keyword argument 'num'

### ISSUE THREAD

**Issue by arthurlogilab** [andymccurdy/redis-py#900]
I'm switching a project from standalone redis to redis with sentinel and I am getting the following error : 

```
client.lrem(PENDING_KEY, data, num=1)
[snip]
TypeError: lrem() got an unexpected keyword argument 'num'
```

Looking at https://github.com/andymccurdy/redis-py/blob/master/redis/client.py I realize that ```lrem``` has different signatures in Redis and StrictRedis... which, first off, feels odd. Maybe there is a reason for that. If so, maybe the documentation should reflect that.

I guess, I have to switch to StrictRedis (better and more recent according to the docs), and change the class of my get_master_for awaiting the changes in the code client side https://github.com/andymccurdy/redis-py/blob/master/redis/sentinel.py#L246 Are there side effects to be expected in that case ?

**Comment by andymccurdy** [comment]
The docs do reflect the differences between `Redis` and `StrictRedis`: https://github.com/andymccurdy/redis-py#api-reference (the last section showing differences between Redis and StrictRedis). `Redis` continues to exist only for backwards compatibility.

The Sentinel client will return `StrictRedis` instances by default, which I would advise using. If you must continue to use the `Redis` class, simply changing the `redis_class` parameter on the `master_for` and `slave_for` functions will do the trick.
