### ISSUE TITLE
Sentinel ConnectionError race condition during failover

### ISSUE THREAD

**Issue by dizzyfingerz** [andymccurdy/redis-py#903]
I'm having some issues with redis-py Sentinel in a high-availability asynchronous work queue project design. For starters, here's my code (simplified):

    from redis.sentinel import Sentinel
    
    sentinel = Sentinel(sentinels=SENTINEL_HOSTS, socket_timeout=0.1)
    r = sentinel.master_for('redis-sentinel-cluster')
    
    while True:
        item = r.rpop('work-queue')
        if item is None:
             break
        else:
            # do work on the item
    
        continue

Now, as it stands, redis-py has some good retry logic in the  for determining which redis connection to use. 

Basically, if the socket fails, try and get a new one:

1. https://github.com/andymccurdy/redis-py/blob/master/redis/sentinel.py#L44-L45

2. https://github.com/andymccurdy/redis-py/blob/master/redis/sentinel.py#L99-L108

And it requests the current master from the existing sentinels:

3. https://github.com/andymccurdy/redis-py/blob/master/redis/sentinel.py#L204-L223

---

This works fine so long as the outage (and new master election) is completed before the next redis call attempt. 

However, if a redis failure occurs—and say my sentinels have a 5 second timeout before they elect a new one—the redis call will fail, and the Sentinel connection will request a new master but the existing master gets returned! Which results in a ConnectionError.

Obviously, I can wrap my redis calls in ConnectionError try/excepts and sleep or retry appropriately, but is there a cleaner way to do this using the existing connection params of redis-py?

Ideally, this sentinel redis connection would only throw a ConnectionError if a certain period has elapsed, and still no masters are available.

If this is not possible as is, can the SentinelManagerConnection class have this as optional behavior? 

FYI: This is a nearly identical copy of [this SO post](https://stackoverflow.com/questions/46180510/redis-py-sentinel-connectionerror-race-condition-during-failover)

**Comment by rolette** [comment]
`SentinelConnectionPool` is your friend. Just make sure you look through the current pull requests for a couple of important fixes that haven't been merged into the master yet.
