### ISSUE TITLE
no notification about deleted key in case of flushdb

### ISSUE THREAD

**Issue by joelazar** [andymccurdy/redis-py#907]
Hi,

I noticed that if I subscribe for a key change events and if this key get removed by a flushdb command, then there is no notification about the key disappearance from the pubsub object. However, if I capture its connection I see that there is a notification packet arrives from redis though.
Is it intended? I didn't find any restrictions about the subscriptions.
Do you need any example code or capture?

Thanks in advanced. Joe

**Comment by andymccurdy** [comment]
Example code and redis-py/redis-server version would be great.

redis-py doesn't impose any restrictions on any events.

**Comment by joelazar** [comment]
redis-server --version
Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=687a2a319020fa42

redis started this way:
redis-server --notify-keyspace-events KEA

[example code](https://gist.github.com/joelazar/1f24145a45c135c2404ec1123caae976)
