### ISSUE TITLE
Missing keys created using pipeline()

### ISSUE THREAD

**Issue by radzhome** [andymccurdy/redis-py#908]
Hi, so I am having issues with pipelining. The problem is that no errors are thrown by redis-py but there is an intermittent issue where keys are not actually written to redis. There are no key evictions and back to back write, read often shows the keys were not written so I have to try writing again and checking if they exist until it works. 

```
def bulk_store(broker_id, tix, expiry=None):
    pipe = kache_write_conn.pipeline()  # Strict Redis conn
    for ticket in tix:
        pipe.hset(str(broker_id) + ':' +  ticket['id'], 'ticket_data', ujson.dumps(ticket))
        if expiry:
            pipe.expire(ticket_key, expiry)

    pipe.execute()
    return True
```

The issue is more apparent when there is more load on the redis server. I would expect that redis-py by default throws an error if the command does not succeed. Any way to make pipelining to redis ensure keys were written? Anything I can do on the server side to help troubleshoot?

**Comment by andymccurdy** [comment]
The first thing I'd check is the expiry. If you pass a non-positive value (0 or a negative number), expire will immediately delete the key from Redis. If you're passing a datetime object as the expiry, you need to make sure that the object is still the future for every iteration of your ticket loop.

You could check out the `MONITOR` command in a redis-cli instance connected to the server. This will show you every command from every client that's being issued. You should be able to get a sense whether the `HSET` is happening at all and what value is being used to set the expire time.

**Comment by radzhome** [comment]
Closing the issue, not related to redis. Looks like the keys were getting deleted by another external process.

**Comment by radzhome** [comment]
The expiry was not being set on these particular keys.. there was another job removing stuff from cache and then db, but the db deletes were failing at times due to locking. 

When I isolated the problem it was quite clear that it wasn't redis. Thanks for the reply though, appreciate it.

I was using `MONITOR` and `INFO` to see what was going on at the moment, and also looking for oom key eviction issues.
