### ISSUE TITLE
Reconnect to redis if got ReadOnlyError | sentinel

### ISSUE THREAD

**Issue by Arfey** [andymccurdy/redis-py#935]
related https://github.com/andymccurdy/redis-py/issues/688

Maybe need add auto retry to commands (set, get etc.) when got `ReadOnlyError`? Because more client initialization sentinel only once and when master changed to slave raise `ReadOnlyError`. One `try: except` and  `for i in range(RETRY_COUNT)` in lib better than many `try: except` in a client code.

what do you think?

**Comment by axot** [comment]
Not only about the use of sentinel, for example during failover process, the master node will also changes to replica, and if you use DNS as an endpoint of master node, this error has a high probability of occurring.

So I'm suggesting to handle ReadOnlyError in [retry mechanism](https://github.com/redis/redis-py/pull/1494), any thought or advice?
