### ISSUE TITLE
ConnectionPool.get_connection: what is the `command` argument good for?

### ISSUE THREAD

**Issue by vlcinsky** [andymccurdy/redis-py#936]
```
from redis import ConnectionPool
pool = ConnectionPool.from_url("redis://")
con = pool.get_connection()
```
The last line failed as it expects `command` argument.

This was a surprise, what shall I do with a command when asking for a connection?

Anyway, the code shows, the argument is really required, but it is never used as seen in [here](https://github.com/andymccurdy/redis-py/blob/master/redis/connection.py#L960).

**Comment by zeebonk** [comment]
Are you sure you really want to fiddle around with connections yourself? Its not a common use-case as you can just pass the entire pool to the constructor of clients:

    pool = redis.ConnectionPool(host='localhost', port=6379, db=0)
    r = redis.Redis(connection_pool=pool)`

**Comment by vlcinsky** [comment]
@zeebonk I am sure I dont want to fiddle. In my app I use exactly the lines you proposed which I found soon after reporting the issue.

Anyway I felt the piece of code I refer to in my issue is confusing (asking for unexpected type of argument and then not using it).

**Comment by andymccurdy** [comment]
The command name argument is so that other, third party connection pools can return an appropriate connection based on the command being executed. For instance, a connection pool that works with Redis cluster might choose to return a specific connection based on the command being run.
