### ISSUE TITLE
does this lib support the asyncio for asynchrous ?

### ISSUE THREAD

**Issue by ray1888** [andymccurdy/redis-py#937]
i want to use redis pubsub to collector cmd for tunnel , but what i need , it must be asynchrously , can it run well with asyncio await ? i don't want it to be blocked

**Comment by itdaniher** [comment]
No, try aioredis or asyncio-redis, two libraries that work with aio.

**Comment by laixintao** [comment]
@andymccurdy I think this issue can be closed, because other packages like @itdaniher  can do this job well.

But I'm wondering is there any lib that support synchronous and asynchronous ?

**Comment by NoneGG** [comment]
@ray1888 Besides two nice choices referred by @itdaniher , may be you can have a try on my client ported from redis-py [aredis](https://github.com/NoneGG/aredis). Besides single node and sentinel, redis cluster is also supported.

**Comment by ray1888** [comment]
thank alot . issue close
