### ISSUE TITLE
Multithreading is slow compared to multi process

### ISSUE THREAD

**Issue by moagarw** [andymccurdy/redis-py#942]
Hi,

We have a python web app running on ACS using K8s. While doing performance testing we are realizing that our Redis response times are better when we have more python processes with less worker threads vs more worker threads and less processes. 

Machine is octa core - 28GB ram machine.
OS is "Ubuntu 14.04.4 LTS"

We are using a connection pool per process with no maximum connection limits. We are using this constructor  - 

redis  = StrictRedis.from_url(
        <redis_url>,
        db=0
    )

The test setup has a simple REST api which does a ping() to redis. We use apache benchmark to load test that api (ab -n 10000 -c 600 -k <url> )

The two configurations we are testing - 

120 pods (processes) and 16 unicorn workers (threads) - 
95% redis response time - 6 ms
max created connections per process - 9
12 pods (processes) and 160 workers (threads) - 
95% redis response time - ~70 ms
max created connections per process - 14

I have already checked the ulimits of our machine, cpu/ram usage and nothing is of an issue. Network IO is also not that different in both cases.

I dont think GIL should be an issue as this is network IO. Also from more debugging logs i can confirm that time taken is more in read_response() and not in connect().

One thing is was expecting was that with less number of processes, number of _created_connections should have gone up by same proportions, but that does not seem to be the case. There is just a marginal increase. Just 9 to 14

We want to ideally have less number of processes to have better dev ops management (deployment latency, monitoring etc.)

Any guidance on why more processes is helping better performance then more threads ?

**Comment by NoneGG** [comment]
@moagarw 
I am not so sure, but i think it is another GIL issue, more threads, more conflict on GIL, and then more time wasted on waking threads and check.
I found an article explains it well [link](https://callhub.io/understanding-python-gil/)

`time taken is more in read_response() and not in connect().`

Actually `connect` only create a TCP connection while `read_response` will wait for response from redis and parse it. 

`number of _created_connections should have gone up by same proportions, but that does not seem to be the case.`

I think it is the effect of connection pool.

**Comment by moagarw** [comment]
@NoneGG : for a given load if 120 processes system creates approximately 11 * 120 redis connections .. should not for given 12 process system, number of connections be 110*12 ?? Since there is no maximum connection limit set, why the size of connection pool is not increasing  with lesser number of processes and same input load. I think the system downgrade is happening because of less number of overall redis connections getting created in the later case.

Also from what i have read around GIL, for CPU intensive systems, GIL is a problem and multiprocessing is preferred over multi threading but for IO intensive systems GIL is not a problem. Is not thats why gunicorn/gevent are popular in python world.

**Comment by Grokzen** [comment]
@moagarw For better understanding of the GIL/thread/multiprocessing problem i would suggest that you watch the video talks from Dave Beazley about python and gil. He goes through this in detail and compares solutions to each other and why they behave the way they do.

The 2 best i know is https://www.youtube.com/watch?v=Obt-vMVdM8s and specially this one https://www.youtube.com/watch?v=MCs5OvhV9S4

**Comment by coleifer** [comment]
> I dont think GIL should be an issue as this is network IO.

Have you profiled this? You may be spending a lot of time encoding commands and decoding responses, hence using CPU, hence the GIL is your limiting factor. Using hiredis might help speed up response parsing, fwiw.
