### ISSUE TITLE
zadd raises TypeError exception

### ISSUE THREAD

**Issue by nitingupta89** [andymccurdy/redis-py#954]
When i try 
to update score of non-existing field like this:
`r.zadd('fooset', 'xx', 'INCR', 10, 'bar')`
OR 
to update score of existing field like this:
`r.zadd('fooset', 'xx', 'INCR', 10, 'zoo')`

ZADD returns None and method is raising
`TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

**Comment by Chronial** [comment]
This is a duplicate of https://github.com/andymccurdy/redis-py/issues/649

**Comment by andymccurdy** [comment]
Fixed in redis-py 3.0
