### ISSUE TITLE
How to release stuck lock

### ISSUE THREAD

**Issue by M1hacka** [andymccurdy/redis-py#962]
I use [redis.Lock() ](http://redis-py.readthedocs.io/en/latest/#redis.StrictRedis.lock) like:
```Python
l = settings.REDIS.lock(name, blocking_timeout=expires)

if not l.acquire():
      # Expired
      return

try:
    return self.task_body(*args, **kwargs)
finally:
    if l:
        l.release()
```
Once (I have't found the reason), the thread escaped without releasing it. And now I have a stuck lock. If I create lock object like above and call `l.acquire(False)` it writes `False` (lock is acquired). If I call `l.release()` it raises not acquired exception.

**Questions:**
1) Is the any way to limit lock acquire time? And release it if time has passed?
2) How to release stuck lock? I can change the name, but it's strange solution to my mind...

**Comment by JokerQyou** [comment]
I was just reading the source code to understand how the lock mechanism works and I saw this issue.

1. If you want a lock to be automatically released after some time, you can use the `timeout` argument (when calling `lock()`);
2. From [the source code](https://github.com/andymccurdy/redis-py/blob/master/redis/lock.py#L143) there's an underlying validation for an internal token. So if you can get into Redis, you should be able to clear the lock key manually.

**Comment by M1hacka** [comment]
@JokerQyou thanks, I've already found it out from source too =) Forgot about this issue opened, closing.
