### ISSUE TITLE
`StrictRedis.from_url` does not document support for `rediss://` scheme

### ISSUE THREAD

**Issue by remeika** [andymccurdy/redis-py#963]
This covers a subset of #780.

The method [`StrictRedis.from_url`](https://github.com/andymccurdy/redis-py/blob/71b69ed31a615305c0af18c34a764eee410586bf/redis/client.py#L462) accepts URLs with protocol `rediss://`. But documentation does not reflect this.

**Comment by remeika** [comment]
Fixed!

**Comment by andymccurdy** [comment]
The best kind of issue!
