### ISSUE TITLE
Support for bytes as keys

### ISSUE THREAD

**Issue by suola** [andymccurdy/redis-py#965]
Is redis-py supposed to support bytes as keys? If yes, at least `blpop` and `brpop` are broken since they listify scalar `keys` argument based on test for `isinstance(keys, basestring)` where `basestring` is `str` in python3.

This results in e.g. the following code snippet to block forever w/ py3 (`blpop()` splits key to `[b'a', b'b', b'c']`)

```python
import redis
r = redis.StrictRedis()
r.lpush(b'abc', b'v')
r.blpop(b'abc')
```

This could be solved by replacing the `isinstance` construct w/ e.g. `keys = redis.client.list_or_args(keys, None)`.

**Comment by andymccurdy** [comment]
Fixed in redis-py 3.0
