### ISSUE TITLE
Error in jython

### ISSUE THREAD

**Issue by vad** [andymccurdy/redis-py#97]
If i try to use redis-py in jython, i get an error with the socket module:

File "/Users/vad/Source/Envs/jython/Lib/site-packages/redis/client.py", line 64, in connect
sock.setsockopt(socket.SOL_TCP, socket.TCP_NODELAY, 1)
AttributeError: 'module' object has no attribute 'SOL_TCP'

Full traceback on:
https://gist.github.com/784227#file_redis_py%20in%20jython

**Comment by vaethis** [comment]
I had to resolve the issue by changing socket.SOL_TCP to socket.IPPROTO_TCP and it worked.
