### ISSUE TITLE
Python3.5 vs Python3.6 hscan_iter different sort result

### ISSUE THREAD

**Issue by nooperpudd** [andymccurdy/redis-py#978]
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
```
redis_client = redis.StrictRedis()
In [4]: for item in redis_client.hscan_iter("BB"):
   ...:     print(item)
   ...:
(b'3', b'c')
(b'1', b'a')
(b'4', b'd')
(b'2', b'b')
```
Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28)
```
redis_client = redis.StrictRedis()
for item in redis_client.hscan_iter("BB"):
    ...:     print(item)
    ...:
(b'1', b'a')
(b'2', b'b')
(b'3', b'c')
(b'4', b'd')
```

**Comment by nooperpudd** [comment]
https://stackoverflow.com/questions/39980323/are-dictionaries-ordered-in-python-3-6

**Comment by andymccurdy** [comment]
I don't believe this has anything to do with Python. As far as I'm aware, the Redis `SCAN` commands do not define an order that values are returned in.
