### ISSUE TITLE
No Module named version

### ISSUE THREAD

**Issue by bevywise** [andymccurdy/redis-py#981]
Hello, 

I am bulding a redis plugin for [MQTTRoute](https://www.bevywise.com/mqtt-broker/) like the [Mongo DB](https://github.com/bevywise-networks/mqttroute-mongodb-connector/) connector. 

when I run the redis client as an independent entity, it works. But when I run as a plugin,  I get a **no module named version**  error. I have the module version installed in the server.  I have also set the system path using the following line and then calling the import.  

sys.path.append('/usr/local/lib/python2.7/dist-packages')

The module redis and the version is available in the path. 

Appreciate your help. 

Thanks.

**Comment by andymccurdy** [comment]
How are you installing redis-py? Did you use `pip`? I would advise against messing with `sys.path`.

**Comment by bevywise** [comment]
Thanks for the quick reply. 

Yes. We use pip to install the redis.py. 

If we did not set the sys.path, the import of redis itself is failing. The same is for the other connectors of mqttroute also. 

Thanks.

**Comment by andymccurdy** [comment]
Manually messing with `sys.path` is probably not what you want to be doing.  Do you have a file named `redis.py` somewhere? If so, and if it's in a location on your python path, it is likely getting found and loaded before redis-py.

**Comment by bevywise** [comment]
There is no redis.py on the machine.  There is redis folder in the path and the files of redis-py inside it. 

The python default path is not getting set when run as a plugin.  Can you advice me with an alternative to set the path outside the executable ?

**Comment by andymccurdy** [comment]
Typically 3rd party libs get installed to a `site-packages` directory relative to the `python` executable. Likely something like `../lib/python3.6/site-packages`. The `python` executable is hard coded to look in this location (relative to itself). This will represented by one of the paths listed in `sys.path` prior to any manual manipulation. This is also where `pip` should (by default) install modules.

Let's back up a bit though. When you launch `python` on this host machine and type `import redis`, what happens? If it imports, can you see `redis.StrictRedis`?

**Comment by bevywise** [comment]
Yes. I am able to see the redis.StrictRedis on the Python prompt.  BTW I am using python 2.7. 

Running a python independently does not have any issues.  

But when I import it and call it from an executable it is causing the issue.

**Comment by andymccurdy** [comment]
Ok, so I don’t believe this is a redis-py issue. If you can `import redis` and see `redis.StrictRedis`, redis-py is installed correctly and client classes can be called and instantiated.

I’m not familiar with mqttroute so I can’t comment on what it’s trying to do. Sorry.
