### ISSUE TITLE
Faster way to iterate all keys and values in db

### ISSUE THREAD

**Issue by jonathan-kosgei** [andymccurdy/redis-py#984]
I have a db with about 350,000 keys. Currently my code just loops through all keys and gets its value from the db. 

However this takes almost 2 minutes to do, which seems really slow, `redis-benchmark` gave 100k reqs/3s.

I've looked at pipelining but I need each value returned so that I end up with a dict of key, value pairs.

At the moment I'm thinking of using threading in my code if possible to speed this up, is this the best way to handle this usecase?

Here's the code I have so far.
```
import redis, timeit
start_time = timeit.default_timer()
count = redis.Redis(host='127.0.0.1', port=6379, db=9)
keys = api_count.keys()

data = {}

for key in keys:
    value = count.get(key)
    if value:
        data[key.decode('utf-8')] = int(value.decode('utf-8'))

elapsed = timeit.default_timer() - start_time

print('Time to read {} records: '.format(len(keys)), elapsed)
```

**Comment by jonathan-kosgei** [comment]
Thank you! `decode_responses` alone is priceless. And the rest of the code looks so much better than what I was doing! Thanks!

I had some time to test a few things since posting this and I came up with the code below, it takes about 6s for about 380k keys.

I had some hesitations about using HMSET because I read it was O(N), and it seemed counter-intuitive to store all my data in one key, but since you've mentioned it I'll definitely try it. Might you know how much faster it would be? From past experience?

```
def get_all(all_keys):
    pipe = api_count.pipeline()
    for key in all_keys:
        pipe.get(key)
    values = pipe.execute()
    values = [int(value.decode('utf-8')) if not value is None else None for value in values]
    return dict(zip(all_keys, values))
```

**Comment by jonathan-kosgei** [comment]
By adding `count=1000000` to your code it completes in about 8 seconds for about 550k keys. Thanks!

**Comment by kg-2** [comment]
@jonathan-kosgei by removing None from the values list you're messing up the key, value pairs. Keys after the first removed index will be paired with the wrong value and the last <num of values removed> keys won't be in the dict at all

**Comment by jonathan-kosgei** [comment]
You are right, I checked what we have in production and it seems we caught that bug.

**Comment by justinTM** [comment]
use [`scan_iter`](https://github.com/redis/redis-py/blob/883fca7199a7ab7adc583b9ee324a9e44d0909eb/redis/commands/cluster.py#L713):
```python
spark_redis_parallel = ForeachWriter(key_prefix="my_key_prefix")
spark_redis_parallel.open()
count = 0
for data in spark_redis_parallel.rc.scan_iter(f"{spark_redis_parallel.key_prefix}:*", count=1000000):
    count += len(data)
print(count)
```
Command took 33.97 seconds
```console
114545800
```
