### ISSUE TITLE
How to assign connection timeout using redis.Redis.rpush(key,val)?

### ISSUE THREAD

**Issue by tianwei1992** [andymccurdy/redis-py#998]
r = redis.Redis(host=redis_host, port=redis_port, db=redis_db, password=redis_password)
result = r.rpush(key, value)

These codes work fine when the connection to my Redis can be established, however it will block aout 4 or 5 seconds before  raising an exception when the connection can't be established.For me ,the blocking time is too long and what I want is that once failing to establish the connection, exceptions can be raised within 1 second.
I have tried to pass some args to the function "rpush" ,but it doesn't have any other optional args

**Comment by grumps** [comment]
`[rpush` is a redis command,](https://redis.io/commands/rpush) it's not feasible to change a connection/socket time out per command that would establish a connection for every command and cause significant overhead. 

Instead you should set your timeout when you initialize your connection which is done via the `Redis` object.
https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L492

**Comment by tianwei1992** [comment]
Get it ！Thank you very much~
